//! What a consumable restores, from `gm-handbook/consumables.txt`.
//!
//! Generated by `tools/dump_itemdata.py` from the client's own `Item.wz` **`spec`** nodes -
//! a different child from the `info` node the rest of `itemdata.txt` comes out of, which is
//! why this was missing for so long: every earlier pass read `info` and `spec` was never
//! looked at.
//!
//! # The unit, and it is two different units
//!
//! `hp`/`mp` are **flat amounts**. `hpR`/`mpR` are **percentages of the maximum**. A few
//! items carry both. `CLAUDE.md` has a section on exactly this class of mistake - three bugs
//! in one month were a correct number in the wrong unit, and all three read on screen as
//! "the feature is broken" rather than as a wrong number.
//!
//! # A missing table is not an empty one
//!
//! `Config::map_exists` was once fail-open on an empty field table, with its only warning on
//! stderr where nothing reads it, and that silently removed the `!map` guard for a day. So
//! this reports its state on **stdout**, in both directions, unconditionally.

use std::collections::HashMap;
use std::path::Path;

/// What one item restores when it is used.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Restores {
    /// A flat number of HP.
    pub hp: u32,
    /// A flat number of MP.
    pub mp: u32,
    /// A percentage of maximum HP, 0..=100.
    pub hp_percent: u32,
    /// A percentage of maximum MP, 0..=100.
    pub mp_percent: u32,
}

impl Restores {
    /// Nothing at all - the value for an item with no row.
    pub fn is_nothing(&self) -> bool {
        *self == Restores::default()
    }

    /// How much HP this actually restores for a character with `max_hp`, flat plus percent.
    ///
    /// The caller still has to cap the result at the missing amount: an item that heals 100
    /// on a character missing 3 heals 3, and telling the client otherwise would put a number
    /// above the maximum into the HP field.
    pub fn hp_for(&self, max_hp: u32) -> u32 {
        self.hp.saturating_add(max_hp.saturating_mul(self.hp_percent) / 100)
    }

    /// The MP half of [`Self::hp_for`].
    pub fn mp_for(&self, max_mp: u32) -> u32 {
        self.mp.saturating_add(max_mp.saturating_mul(self.mp_percent) / 100)
    }
}

/// Every item that restores something.
#[derive(Debug, Clone, Default)]
pub struct Consumables {
    by_id: HashMap<u32, Restores>,
    source: String,
    /// Lines that did not parse, kept so the banner can say how many rather than swallowing
    /// them.
    problems: usize,
}

impl Consumables {
    /// Load the table. A missing file is legal and yields an empty table.
    pub fn load(path: &Path) -> Self {
        let source = path.display().to_string();
        match std::fs::read_to_string(path) {
            Ok(text) => Consumables { source, ..Self::parse(&text) },
            Err(_) => Consumables { source, ..Default::default() },
        }
    }

    /// Parse the TSV-ish `itemId, hp, mp, hpR, mpR` body.
    pub fn parse(text: &str) -> Self {
        let mut by_id = HashMap::new();
        let mut problems = 0;
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let f: Vec<&str> = line.split(',').map(str::trim).collect();
            if f.len() != 5 {
                problems += 1;
                continue;
            }
            let parsed: Option<(u32, u32, u32, u32, u32)> = (|| {
                Some((
                    f[0].parse().ok()?,
                    f[1].parse().ok()?,
                    f[2].parse().ok()?,
                    f[3].parse().ok()?,
                    f[4].parse().ok()?,
                ))
            })();
            match parsed {
                Some((id, hp, mp, hp_percent, mp_percent)) => {
                    by_id.insert(id, Restores { hp, mp, hp_percent, mp_percent });
                }
                None => problems += 1,
            }
        }
        Consumables { by_id, source: String::new(), problems }
    }

    /// What `item_id` restores. `None` means the item restores nothing - which is a
    /// different answer from "this client has no such item", and the caller distinguishes
    /// them.
    pub fn get(&self, item_id: u32) -> Option<Restores> {
        self.by_id.get(&item_id).copied()
    }

    pub fn is_empty(&self) -> bool {
        self.by_id.is_empty()
    }

    pub fn len(&self) -> usize {
        self.by_id.len()
    }

    /// One line for the startup banner, different in each state, always printed.
    pub fn banner(&self) -> String {
        let from = if self.source.is_empty() { "(no file)" } else { self.source.as_str() };
        if self.by_id.is_empty() {
            return format!(
                "maplecw-world: consumables: NONE LOADED from {from}. Every potion and food \
                 item will be refused with a notice rather than healing. Regenerate with: \
                 python tools/dump_itemdata.py"
            );
        }
        format!(
            "maplecw-world: consumables: {} items restore something, from {from}{}",
            self.by_id.len(),
            if self.problems > 0 {
                format!(" ({} unreadable line(s))", self.problems)
            } else {
                String::new()
            }
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "# itemId, hp, mp, hpR, mpR\n\
                          2000000, 100, 0, 0, 0\n\
                          2010000, 30, 0, 0, 0\n\
                          2000003, 0, 0, 100, 100\n\
                          rubbish\n";

    #[test]
    fn the_red_potion_and_the_apple_come_back_with_the_numbers_the_wz_gives_them() {
        let c = Consumables::parse(SAMPLE);
        assert_eq!(c.get(2_000_000).unwrap().hp, 100, "Red Potion");
        assert_eq!(c.get(2_010_000).unwrap().hp, 30, "Roger's Apple, and its own tooltip");
        assert_eq!(c.len(), 3);
        assert!(c.get(9_999_999).is_none(), "an item with no row restores nothing");
    }

    /// The two units are not interchangeable, and this is the test that says so.
    #[test]
    fn a_percentage_scales_with_the_maximum_and_a_flat_amount_does_not() {
        let c = Consumables::parse(SAMPLE);
        let potion = c.get(2_000_000).unwrap();
        assert_eq!(potion.hp_for(50), 100, "flat: the same on a small character");
        assert_eq!(potion.hp_for(5000), 100, "flat: and the same on a large one");

        let elixir = c.get(2_000_003).unwrap();
        assert_eq!(elixir.hp_for(50), 50, "100% of 50");
        assert_eq!(elixir.hp_for(5000), 5000, "100% of 5000");
        assert_eq!(elixir.mp_for(200), 200);
    }

    /// A missing file degrades to an empty table and a loud banner, never to a panic.
    #[test]
    fn a_missing_file_is_empty_and_says_so_on_stdout() {
        let c = Consumables::load(Path::new("no/such/consumables.txt"));
        assert!(c.is_empty());
        assert!(c.banner().contains("NONE LOADED"), "{}", c.banner());
        assert!(c.get(2_000_000).is_none());
    }

    #[test]
    fn an_unreadable_line_is_counted_rather_than_swallowed() {
        let c = Consumables::parse(SAMPLE);
        assert_eq!(c.problems, 1);
    }
}
