//! What a mob drops when it dies: a per-template table, plus a global one for events.
//!
//! The **field** side - an item lying on the ground, its object id, expiry, and picking it
//! back up - is `crate::drops`. This module only answers *what* falls, never *where* it
//! goes or *how long* it stays.
//!
//! # Where the data comes from, and what is ours
//!
//! `data/drops.txt`, generated by `tools/scrape_drops.py` from the community database at
//! `meowdb.com/msclassic`. It is **committed rather than gitignored**, unlike everything in
//! `gm-handbook/`: that data is regenerated from the client's own WZ at will, and this
//! cannot be regenerated without network access to a third-party site that may change or
//! disappear. It is authored source in the same sense `data/shops.txt` is.
//!
//! **The chances are v83's (2026-10-01).** meowdb gives, per monster, a list of items and a
//! community *vote score* - no drop rates at all - so the chances used to be a flat policy per
//! category, and scrolls and early equipment fell several times more often than on any classic
//! server (`research/drop-rates-vs-v83-2026-10-01.md`). `tools/v83_drops.py` now takes each
//! matched mob's chances, and the items meowdb was missing, from Cosmic's v83 tables, and puts
//! meowdb-only rows at the v83 median for their category. The vote score stays in its column.
//!
//! # The rate, and the scale, are v83's too
//!
//! Chances are held in **parts per million**, as Cosmic's `drop_data` holds them: a v83
//! equipment row is `0.1287%` and a global Chaos Scroll `0.005%`, neither of which the old
//! basis points could express. The server's drop rate multiplies every **per-mob** chance; the
//! **global** table is rolled at its own chance whatever the rate, as Cosmic's
//! `dropGlobalItemsFromMonsterOnMap` does - a global row is a deliberately rare item, and a 5x
//! event should not make it five times less rare.
//!
//! # Two tables, checked in one order
//!
//! The owner: *"when a mob dies, it checks for its mob specific drop table and any global drop
//! table"*. The global table is for event items - there are no events yet, so it is empty,
//! and it exists now so that adding one is a data change rather than a code change.
//!
//! Rolls are **independent**, not a weighted pick of one winner: a mob may drop nothing, or
//! several things, which is how this game behaves.

use std::collections::HashMap;
use std::path::Path;

/// A level-scaled meso drop, for a mob whose table has no authored meso row.
///
/// The owner, 2026-08-30: *"some mobs ... never drops mesos. This must be a bug as all
/// non-job advancement and tutorial mobs should drop varying amounts of mesos dependent on
/// their level."* They are right, and the scale of it is that **only 23 of the 170 mobs with a
/// drop table have a meso row at all** - Slime (template 7) has seventeen item rows and not
/// one of them is mesos.
///
/// # The numbers are FITTED to this project's own authored rows, not invented
///
/// Those 23 rows are consistent enough to read a rule off, and every one of them is at 100%
/// chance:
///
/// ```text
///   level     authored      level*18/10   level*22/10
///       7      12 - 14        12            15
///      30      50 - 60        54            66
///      50      92 - 110       90           110
///      90     162 - 198      162           198
/// ```
///
/// So `min = level * 1.8`, `max = level * 2.2`, and the default lands on top of the hand
/// authored numbers rather than beside them. **[D]** from 18 usable rows.
///
/// Level 0 returns `None` rather than zero mesos: a template with no level is a mob this
/// server knows nothing about, and inventing a drop for it would hide that.
pub fn level_meso_range(level: u32) -> Option<(u32, u32)> {
    if level == 0 {
        return None;
    }
    // Floor at 1, because `level * 18 / 10` is 1 at level 1 and a drop of zero mesos is a
    // drop that draws nothing - the same failure as a zero-price shop row.
    let min = (level * 18 / 10).max(1);
    let max = (level * 22 / 10).max(min);
    Some((min, max))
}

/// The `itemId` that means **mesos** rather than an item.
///
/// Zero is not a real item id in this game - ids are `1xxxxxx`..`5xxxxxx` - so it is free to
/// use as a marker, and it keeps mesos in the same table as everything else rather than
/// inventing a parallel file for one row per mob. `min_qty`/`max_qty` are then the amount.
pub const MESOS: u32 = 0;

/// The line prefix that means "this row belongs to the global table".
pub const GLOBAL_KEY: &str = "*";

/// Chances are stored in **parts per million**, 0..=1 000 000 - v83's own scale (Cosmic's
/// `drop_data.chance`) - so `0.0001%` is representable and no float ever decides a drop.
pub const PER_MILLION: u32 = 1_000_000;

/// **The least a quest-only item drops at, before the server's drop rate**: 5% (the owner,
/// 2026-10-04). [`DropTables::raise_quest_item_floor`].
pub const QUEST_ITEM_FLOOR_PPM: u32 = 50_000;

/// One row: an item this mob can drop, and how likely it is.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DropEntry {
    /// The game's item id, or [`MESOS`].
    pub item_id: u32,
    /// 0..=[`PER_MILLION`]. v83's where the mob matched, a v83 category median otherwise -
    /// see the module docs. Nobody has official per-mob rates.
    pub chance_ppm: u32,
    /// Inclusive. For [`MESOS`] this is the amount, not a stack size.
    pub min_qty: u32,
    /// Inclusive, and never below `min_qty` - the loader swaps them if a row has it backwards.
    pub max_qty: u32,
    /// The community vote score the chance was derived from. Kept so the policy can be
    /// recomputed from the file instead of from the network.
    pub score: i32,
    /// For the log line and for reading the file by eye. Not sent to the client.
    pub name: String,
}

impl DropEntry {
    /// Did this entry drop? `roll` is any number; only `roll % PER_MILLION` is used.
    ///
    /// `chance_ppm == 0` never drops and `chance_ppm >= PER_MILLION` always does, both
    /// without consuming the roll's meaning - a table with a typo'd 0 is silent rather than
    /// surprising.
    pub fn hits(&self, roll: u64) -> bool {
        self.hits_at(roll, store::rates::Rate::NORMAL)
    }

    /// Did this entry drop, with the server's drop rate applied?
    ///
    /// **The rate scales the chance, not the quantity.** A 2x drop event means twice as
    /// likely, which is what the phrase means everywhere in this game family; doubling the
    /// stack size instead would be a different feature wearing the same name.
    ///
    /// The scaled chance is **capped at certainty**. Without the cap a 40% row at 3x would be
    /// 120%, and `chance_ppm >= PER_MILLION` already means "always" - so the cap is what the
    /// comparison would do anyway, written down where it can be read.
    pub fn hits_at(&self, roll: u64, rate: store::rates::Rate) -> bool {
        if self.chance_ppm == 0 {
            // A typo'd 0 stays silent at every rate. Multiplying nothing is still nothing,
            // and `Rate::apply`'s floor-at-1 must not turn a disabled row into a live one.
            return false;
        }
        let chance = rate.apply(u64::from(self.chance_ppm)).min(u64::from(PER_MILLION));
        if chance >= u64::from(PER_MILLION) {
            return true;
        }
        (roll % u64::from(PER_MILLION)) < chance
    }

    /// How many, given a second roll. Inclusive of both ends.
    pub fn quantity(&self, roll: u64) -> u32 {
        let span = u64::from(self.max_qty.saturating_sub(self.min_qty)) + 1;
        self.min_qty + (roll % span) as u32
    }
}

/// One thing that actually dropped.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Rolled {
    /// The item id, or [`MESOS`].
    pub item_id: u32,
    /// How many. For [`MESOS`], the amount.
    pub quantity: u32,
}

impl Rolled {
    /// Mesos are not an item and must not be put in a bag slot.
    pub fn is_mesos(&self) -> bool {
        self.item_id == MESOS
    }
}

/// Every mob's drop table, and the global one.
#[derive(Debug, Clone, Default)]
pub struct DropTables {
    per_mob: HashMap<u32, Vec<DropEntry>>,
    global: Vec<DropEntry>,
    /// Lines that would not parse, kept rather than discarded so a bad file is visible in
    /// the startup banner instead of silently dropping a mob's whole table.
    pub problems: Vec<String>,
}

impl DropTables {
    /// Read `data/drops.txt`. A missing file is **not** an error: it yields empty tables and
    /// one problem line, and mobs simply drop nothing.
    ///
    /// Degrading rather than failing is deliberate. This is the only data file sourced from
    /// a third party, so it is the one most likely to be absent on a fresh clone, and a
    /// channel that refuses to start because a fan site's export is missing would be a
    /// worse failure than mobs that drop nothing.
    pub fn load(path: &Path) -> Self {
        match std::fs::read_to_string(path) {
            Ok(text) => Self::parse(&text),
            Err(e) => DropTables {
                problems: vec![format!("{}: {e} - no mob will drop anything", path.display())],
                ..Default::default()
            },
        }
    }

    /// `templateId | itemId | chance% | minQty | maxQty | score | name`
    ///
    /// `#` starts a comment, blank lines are skipped, and a template of `*` puts the row in
    /// the global table. The chance is a **percentage** in the file because that is what a
    /// human editing it will expect; it is stored in parts per million.
    pub fn parse(text: &str) -> Self {
        let mut out = DropTables::default();
        for (n, raw) in text.lines().enumerate() {
            let line = raw.split('#').next().unwrap_or("").trim();
            if line.is_empty() {
                continue;
            }
            let cols: Vec<&str> = line.split('|').map(str::trim).collect();
            if cols.len() < 5 {
                out.problems.push(format!("line {}: needs at least 5 columns", n + 1));
                continue;
            }
            let entry = match parse_entry(&cols) {
                Ok(e) => e,
                Err(why) => {
                    out.problems.push(format!("line {}: {why}", n + 1));
                    continue;
                }
            };
            if cols[0] == GLOBAL_KEY {
                out.global.push(entry);
            } else {
                match cols[0].parse::<u32>() {
                    Ok(t) => out.per_mob.entry(t).or_default().push(entry),
                    Err(e) => out.problems.push(format!("line {}: template id: {e}", n + 1)),
                }
            }
        }
        out
    }

    /// **Raise every row `is_quest_only` names to at least `floor_ppm`**, before the drop rate.
    /// Returns the rows it raised, for the startup banner.
    ///
    /// The owner, 2026-10-04: *"make sure any and all quest only item drops have at least 5% drop
    /// rate base before our server's 5x multiplier is applied"* - after Broken Mirror Glass
    /// (Stirge, 0.9%) made quest 10309's twenty pieces a ~440-kill grind at 5x. Applied at load
    /// rather than written into `data/drops.txt`, so a re-scrape cannot quietly undo it.
    ///
    /// **A `0` row is left at 0**: zero is how a row is opted out, and a floor that turned an
    /// opt-out into a drop would be a surprise nobody asked for. Mesos are never quest items.
    pub fn raise_quest_item_floor(&mut self, floor_ppm: u32, is_quest_only: impl Fn(u32) -> bool) -> Vec<(Option<u32>, DropEntry)> {
        let mut raised = Vec::new();
        let rows = self
            .per_mob
            .iter_mut()
            .flat_map(|(t, rows)| rows.iter_mut().map(move |e| (Some(*t), e)))
            .chain(self.global.iter_mut().map(|e| (None, e)));
        for (template, e) in rows {
            if e.item_id != MESOS && e.chance_ppm > 0 && e.chance_ppm < floor_ppm && is_quest_only(e.item_id) {
                raised.push((template, e.clone()));
                e.chance_ppm = floor_ppm;
            }
        }
        raised.sort_by_key(|(t, e)| (*t, e.item_id));
        raised
    }

    /// Roll everything this mob can drop: **its own table, then the global one**.
    ///
    /// `next` supplies randomness and is called twice per entry - once to decide, once for
    /// the quantity - so a test can hand it a fixed sequence and get a fixed answer. It is a
    /// closure rather than an RNG type because the session's generator is private to the
    /// session, and because a drop table has no business owning one.
    ///
    /// Every entry is rolled independently. A mob can drop nothing at all, and often will.
    pub fn roll(&self, template_id: u32, next: &mut dyn FnMut() -> u64) -> Vec<Rolled> {
        self.roll_at(template_id, store::rates::Rate::NORMAL, next)
    }

    /// Roll this mob's table with the server's drop rate applied to every chance.
    ///
    /// **Both rolls are consumed whether or not the entry hits**, exactly as before - the
    /// quantity roll is only taken on a hit. Changing which rolls are drawn would make the
    /// same seed produce different drops at 1x, and the tests that pin the sequence would
    /// start failing for a reason unrelated to the rate.
    pub fn roll_at(
        &self,
        template_id: u32,
        rate: store::rates::Rate,
        next: &mut dyn FnMut() -> u64,
    ) -> Vec<Rolled> {
        let mine = self.per_mob.get(&template_id).map(Vec::as_slice).unwrap_or(&[]);
        let mut out = Vec::new();
        // The mob's own table at the server's rate, then the global one at its own chance
        // (module docs: v83 never scaled its global drops).
        let rated = mine.iter().map(|e| (e, rate));
        let global = self.global.iter().map(|e| (e, store::rates::Rate::NORMAL));
        for (entry, rate) in rated.chain(global) {
            if entry.hits_at(next(), rate) {
                out.push(Rolled { item_id: entry.item_id, quantity: entry.quantity(next()) });
            }
        }
        out
    }

    /// Whether this mob has an **authored** meso row, at any chance.
    ///
    /// The question is deliberately "is there a row", not "did it hit": an authored row is a
    /// statement about this mob, and a `0` chance is how a mob is opted OUT of mesos. If this
    /// asked whether a roll succeeded, a 0-chance row would silently fall through to the
    /// level default and the opt-out would be unwritable.
    pub fn has_meso_row(&self, template_id: u32) -> bool {
        self.per_mob
            .get(&template_id)
            .is_some_and(|rows| rows.iter().any(|r| r.item_id == MESOS))
    }

    /// This mob's own table, for a GM command or a test.
    pub fn for_mob(&self, template_id: u32) -> &[DropEntry] {
        self.per_mob.get(&template_id).map(Vec::as_slice).unwrap_or(&[])
    }

    /// The global table - event items, rolled for every mob whatever it is.
    pub fn global(&self) -> &[DropEntry] {
        &self.global
    }

    /// Every mob's table, in template order - for the drop-table page (`crate::dropweb`).
    pub fn mobs(&self) -> Vec<(u32, &[DropEntry])> {
        let mut out: Vec<(u32, &[DropEntry])> = self.per_mob.iter().map(|(t, rows)| (*t, rows.as_slice())).collect();
        out.sort_by_key(|(t, _)| *t);
        out
    }

    /// How many mobs have a table, for the startup banner.
    pub fn mobs_with_drops(&self) -> usize {
        self.per_mob.len()
    }

    /// Every row, for the banner and for `!drops`.
    pub fn total_entries(&self) -> usize {
        self.per_mob.values().map(Vec::len).sum::<usize>() + self.global.len()
    }
}

fn parse_entry(cols: &[&str]) -> Result<DropEntry, String> {
    let item_id: u32 = cols[1].parse().map_err(|e| format!("item id: {e}"))?;
    let chance_ppm = parse_percent(cols[2])?;
    let min_qty: u32 = cols[3].parse().map_err(|e| format!("min qty: {e}"))?;
    let max_qty: u32 = cols[4].parse().map_err(|e| format!("max qty: {e}"))?;
    let score: i32 = cols.get(5).and_then(|s| s.parse().ok()).unwrap_or(0);
    let name = cols.get(6).unwrap_or(&"").to_string();
    // A row with the ends the wrong way round is a transcription slip, not a reason to drop
    // the row: `quantity` would otherwise compute a span from a saturating subtraction and
    // silently always return the larger number.
    let (min_qty, max_qty) = if min_qty > max_qty { (max_qty, min_qty) } else { (min_qty, max_qty) };
    Ok(DropEntry { item_id, chance_ppm, min_qty, max_qty, score, name })
}

/// `"40"` -> 400 000 ppm, `"0.1287"` -> 1287 ppm. Four decimal places, which is the
/// resolution of parts per million; anything finer is rounded rather than rejected.
fn parse_percent(s: &str) -> Result<u32, String> {
    let v: f64 = s.parse().map_err(|e| format!("chance: {e}"))?;
    if !(0.0..=100.0).contains(&v) {
        return Err(format!("chance {v} is not a percentage between 0 and 100"));
    }
    Ok((v * 10_000.0).round() as u32)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// **The three scrolls are in the global table at exactly 1 basis point each.**
    ///
    /// The owner, 2026-09-09: *"These 3 items will be added to the global drop table at a 0.01%
    /// drop rate each."* Two of the three, since Event Trophy was dropped later the same day
    /// for not stacking. 0.01% is 1 bp - `parse_percent` multiplies by 100 and
    /// [`BASIS_POINTS`] is 10 000 - so the rate is exact rather than rounded, and this test
    /// says so in basis points rather than trusting the percentage in the file.
    ///
    /// It also guards the fragility the file's own header warns about: these rows are hand
    /// written into a generated file, so a re-scrape would delete them and the scrolls would
    /// stop dropping silently. This test is what turns that into a failure.
    /// **Every Ligator owes a coupon.** The owner, 2026-09-22: *"the coupon drop from Ligators
    /// should be a 100% drop rate."*
    ///
    /// `4001001` is stage 1 of First Time Together: each member is asked for a number of
    /// coupons, so the stage is a counting exercise and a percentage would make it a
    /// lottery. Asserted in basis points AND by rolling, because "100 in the file" and "it
    /// always drops" are two different claims and only the second one is the requirement.
    ///
    /// Like the scrolls below, this is a hand edit in a generated file: a re-scrape would
    /// put the old 6% back. This test is what turns that into a failure rather than a party
    /// standing in stage 1 wondering why nothing drops.
    #[test]
    fn the_ligator_always_drops_its_party_quest_coupon() {
        let tables = DropTables::load(std::path::Path::new("../../data/drops.txt"));
        assert!(tables.problems.is_empty(), "{:?}", tables.problems);
        let row = tables
            .for_mob(crate::firsttime::LIGATOR)
            .iter()
            .find(|e| e.item_id == crate::firsttime::COUPON)
            .unwrap_or_else(|| panic!("the Ligator has no {} row at all", crate::firsttime::COUPON))
            .clone();
        assert!(
            row.chance_ppm >= PER_MILLION,
            "{} ppm is not certain - stage 1 counts coupons, it does not gamble for them",
            row.chance_ppm
        );
        assert_eq!((row.min_qty, row.max_qty), (1, 1), "one coupon per Ligator");
        // And it actually drops, for every roll the generator can produce.
        for roll in [0u64, 1, 9_999, 10_000, u64::MAX] {
            assert!(row.hits(roll), "roll {roll} must still drop it");
        }
    }

    /// **Every mob on the last stage drops a Pass, every time, and the King Slime's shoes
    /// are not in the table.** The owner, 2026-09-23: *"All of these mobs should guarantee a Pass
    /// drop each."* The stage is ten kills for ten Passes, so a miss is a party that cannot
    /// finish. And the Squishy Shoes come from `session/firsttime.rs`, one per member and
    /// each only theirs - a scraped 1% row beside that would be a second, shared pair.
    /// `data/drops.txt` is regenerated by a scrape; this is what makes a rescrape that puts
    /// the old rows back fail rather than ship.
    #[test]
    fn the_last_stage_always_drops_passes_and_never_shared_shoes() {
        let tables = DropTables::load(std::path::Path::new("../../data/drops.txt"));
        assert!(tables.problems.is_empty(), "{:?}", tables.problems);
        for mob in [800_001u32, 800_002, crate::firsttime::KING_SLIME] {
            let row = tables
                .for_mob(mob)
                .iter()
                .find(|e| e.item_id == crate::firsttime::PASS)
                .unwrap_or_else(|| panic!("mob {mob} has no Pass row"))
                .clone();
            assert!(row.chance_ppm >= PER_MILLION, "mob {mob}: {} ppm is not certain", row.chance_ppm);
            assert_eq!((row.min_qty, row.max_qty), (1, 1), "mob {mob}: one Pass each");
            for roll in [0u64, 1, 9_999, 10_000, u64::MAX] {
                assert!(row.hits(roll), "mob {mob}: roll {roll} must still drop it");
            }
            // The owner, 2026-09-24: *"The only thing they should drop are Passes and mesos."* The
            // scrape had given all three a 6% Coupon row - stage 1's item, on stage 5.
            let others: Vec<u32> =
                tables.for_mob(mob).iter().map(|e| e.item_id).filter(|&i| i != crate::firsttime::PASS && i != MESOS).collect();
            assert!(others.is_empty(), "mob {mob} drops {others:?} besides Passes and mesos");
        }
        assert!(
            !tables.for_mob(crate::firsttime::KING_SLIME).iter().any(|e| e.item_id == crate::firsttime::SLIME_SHOES),
            "the shoes are per member, in code - not a shared row"
        );
    }

    /// **The global table is exactly the four backported scrolls, at the owner's odds**, and the two
    /// repurposed scrolls are in no table at all. The owner, 2026-10-01: *"Remove Scroll of
    /// Secrets and Treasure Scroll from global drop tables"*, then Innocence 1 in 1000, Chaos and
    /// Pure Clean Slate 1 in 500 each, Lucky Day 1 in 1000.
    ///
    /// **The dialogue quotes these numbers, so the quote is tied to the file here.**
    /// `crate::scrollnpc::nothing_to_use` renders `scrolls::GLOBAL_SCROLLS`; this is what stops
    /// the two drifting apart. Editing either side alone fails.
    #[test]
    fn the_global_table_is_the_four_backported_scrolls() {
        let tables = DropTables::load(std::path::Path::new("../../data/drops.txt"));
        assert!(tables.problems.is_empty(), "{:?}", tables.problems);
        let global: Vec<(u32, u32, u32, u32)> =
            tables.global.iter().map(|e| (e.item_id, e.chance_ppm, e.min_qty, e.max_qty)).collect();
        let want: Vec<(u32, u32, u32, u32)> =
            crate::scrolls::GLOBAL_SCROLLS.iter().map(|&(id, ppm)| (id, ppm, 1, 1)).collect();
        assert_eq!(global, want);
        assert_eq!(
            crate::scrolls::GLOBAL_SCROLLS.map(|(_, p)| 1_000_000 / p),
            [1_000, 500, 500, 1_000],
            "Innocence, Chaos, Pure Clean Slate, Lucky Day"
        );
        for id in crate::scrolls::REPURPOSED {
            let mobs: Vec<u32> =
                tables.per_mob.iter().filter(|(_, rows)| rows.iter().any(|e| e.item_id == id)).map(|(t, _)| *t).collect();
            assert!(mobs.is_empty(), "{id} still drops from {mobs:?}");
        }
    }

    /// **`4001009` Event Trophy must not drop from anything, anywhere.**
    ///
    /// The owner, 2026-09-09: *"Now that we got rid of Event Trophy's function, make sure that it
    /// is no longer dropping globally."*
    ///
    /// The global row was deleted, and a grep of `data/drops.txt` says so. That grep is not
    /// this test. `CLAUDE.md`'s standing rule is to **enumerate before you filter**, and the
    /// question "does it drop" has two tables behind it, not one: a per-mob row would keep it
    /// dropping while the global table looked clean, and no amount of reading the global
    /// section would show that.
    ///
    /// So this walks **every entry of both tables** and requires the id to appear in neither.
    /// It is also the guard against the file's own documented fragility - these rows are hand
    /// written into a generated file, and a re-scrape that reintroduced the item would
    /// otherwise be silent.
    #[test]
    fn the_event_trophy_drops_from_nothing_at_all() {
        const EVENT_TROPHY: u32 = 4_001_009;
        let tables = DropTables::load(std::path::Path::new("../../data/drops.txt"));
        assert!(tables.problems.is_empty(), "{:?}", tables.problems);

        assert!(
            !tables.global.iter().any(|e| e.item_id == EVENT_TROPHY),
            "4001009 is still in the GLOBAL table"
        );
        let mobs: Vec<u32> = tables
            .per_mob
            .iter()
            .filter(|(_, rows)| rows.iter().any(|e| e.item_id == EVENT_TROPHY))
            .map(|(template, _)| *template)
            .collect();
        assert!(mobs.is_empty(), "4001009 still drops from mob template(s) {mobs:?}");

        // **The control: this search can find something.** An assertion that nothing matches
        // is worthless if the walk is broken - `per_mob` empty, or the file unread - and both
        // failures look exactly like a pass. `4000001` Snail Shell is in the per-mob table and
        // the Chaos Scroll is in the global one, so each half is proved able to speak.
        assert!(
            tables.per_mob.values().any(|rows| rows.iter().any(|e| e.item_id == 4_000_001)),
            "the per-mob walk found no Snail Shell, so it could not have found a trophy either"
        );
        assert!(
            tables.global.iter().any(|e| e.item_id == 2_049_100),
            "the global walk found no Chaos Scroll, so it proves nothing about 4001009"
        );
    }

    const SAMPLE: &str = "\
# templateId | itemId | chance% | minQty | maxQty | score | name
2 | 0       | 100 | 2 | 2  | 1 | mesos
2 | 4000001 | 40  | 1 | 1  | 9 | Snail Shell
2 | 1302000 | 1   | 1 | 1  | 3 | Sword
* | 2022000 | 5   | 1 | 3  | 0 | Event Candy
";

    /// **A quest-only row below 5% is raised to 5%; nothing else moves** - not an ordinary
    /// item, not a quest item already above the floor, not a `0` opt-out, not mesos.
    #[test]
    fn quest_only_rows_are_raised_to_the_floor_and_nothing_else_is() {
        let mut t = DropTables::parse(
            "17 | 0 | 40 | 32 | 48 | 0 | mesos\n\
             17 | 4031007 | 0.9 | 1 | 1 | 3 | Broken Mirror Glass\n\
             17 | 4010001 | 0.9 | 1 | 1 | 7 | Iron Ore\n\
             20 | 4031075 | 0 | 1 | 1 | 2 | opted out\n\
             20 | 4031013 | 60 | 1 | 1 | 2 | already common\n",
        );
        let quest = |id: u32| id >= 4_031_000;
        let raised = t.raise_quest_item_floor(QUEST_ITEM_FLOOR_PPM, quest);
        assert_eq!(raised.len(), 1, "{raised:?}");
        assert_eq!((raised[0].0, raised[0].1.chance_ppm), (Some(17), 9_000), "the row as it was");
        let chance = |m: u32, id: u32| t.for_mob(m).iter().find(|e| e.item_id == id).unwrap().chance_ppm;
        assert_eq!(chance(17, 4_031_007), 50_000);
        assert_eq!(chance(17, 4_010_001), 9_000, "not a quest item");
        assert_eq!(chance(17, MESOS), 400_000);
        assert_eq!(chance(20, 4_031_075), 0, "an opt-out stays out");
        assert_eq!(chance(20, 4_031_013), 600_000, "a floor never lowers");
        assert!(t.raise_quest_item_floor(QUEST_ITEM_FLOOR_PPM, quest).is_empty(), "idempotent");
    }

    #[test]
    fn a_table_parses_into_a_mob_half_and_a_global_half() {
        let t = DropTables::parse(SAMPLE);
        assert!(t.problems.is_empty(), "{:?}", t.problems);
        assert_eq!(t.for_mob(2).len(), 3);
        assert_eq!(t.global().len(), 1, "the `*` row is global, not mob 2's");
        assert_eq!(t.mobs_with_drops(), 1);
        assert_eq!(t.total_entries(), 4);
        assert_eq!(t.for_mob(2)[0].item_id, MESOS);
        assert_eq!(t.for_mob(2)[1].name, "Snail Shell");
    }

    #[test]
    fn a_percentage_becomes_parts_per_million() {
        assert_eq!(parse_percent("100").unwrap(), 1_000_000);
        assert_eq!(parse_percent("40").unwrap(), 400_000);
        assert_eq!(parse_percent("0.1287").unwrap(), 1_287, "a v83 equipment row");
        assert_eq!(parse_percent("0.005").unwrap(), 50, "v83's global Chaos Scroll");
        assert_eq!(parse_percent("0").unwrap(), 0);
        assert!(parse_percent("101").is_err(), "a percentage cannot exceed 100");
        assert!(parse_percent("-1").is_err());
    }

    /// **The global table is rolled for every mob, including one with no table of its own.**
    /// That is the whole point of it: an event item drops from anything.
    #[test]
    fn the_global_table_is_rolled_even_for_an_unknown_mob() {
        let t = DropTables::parse(SAMPLE);
        // Always-hit rolls: 0 % 1 000 000 = 0, which is below every non-zero chance.
        let mut always = || 0u64;
        let got = t.roll(9_999_999, &mut always);
        assert_eq!(got.len(), 1, "only the global row exists for an unknown mob");
        assert_eq!(got[0].item_id, 2_022_000);
    }

    #[test]
    fn a_mob_rolls_its_own_table_then_the_global_one() {
        let t = DropTables::parse(SAMPLE);
        let mut always = || 0u64;
        let got = t.roll(2, &mut always);
        let ids: Vec<u32> = got.iter().map(|r| r.item_id).collect();
        assert_eq!(ids, vec![MESOS, 4_000_001, 1_302_000, 2_022_000], "own table first");
    }

    /// A roll that misses everything drops nothing - a mob that always drops is not a mob.
    #[test]
    fn nothing_drops_when_every_roll_misses() {
        let t = DropTables::parse(SAMPLE);
        // 999 999 is above every chance in the sample except the 100% mesos row.
        let mut never = || 999_999u64;
        let got = t.roll(2, &mut never);
        assert_eq!(got.len(), 1, "only the guaranteed row survives: {got:?}");
        assert!(got[0].is_mesos());
    }

    #[test]
    fn quantity_covers_both_ends_inclusively() {
        let e = DropEntry {
            item_id: 2_022_000,
            chance_ppm: PER_MILLION,
            min_qty: 1,
            max_qty: 3,
            score: 0,
            name: String::new(),
        };
        assert_eq!(e.quantity(0), 1);
        assert_eq!(e.quantity(1), 2);
        assert_eq!(e.quantity(2), 3);
        assert_eq!(e.quantity(3), 1, "and it wraps rather than exceeding max");
    }

    /// A backwards row is repaired, not dropped and not silently always-max.
    #[test]
    fn a_backwards_quantity_range_is_swapped() {
        let t = DropTables::parse("7 | 4000001 | 10 | 5 | 2 | 0 | Backwards\n");
        assert!(t.problems.is_empty());
        let e = &t.for_mob(7)[0];
        assert_eq!((e.min_qty, e.max_qty), (2, 5));
    }

    /// **A zero chance never drops**, so a typo'd row is silent rather than surprising.
    #[test]
    fn a_zero_chance_never_hits_and_a_full_one_always_does() {
        let zero = DropEntry {
            item_id: 1,
            chance_ppm: 0,
            min_qty: 1,
            max_qty: 1,
            score: 0,
            name: String::new(),
        };
        let full = DropEntry { chance_ppm: PER_MILLION, ..zero.clone() };
        for roll in [0u64, 1, 5_000, 999_999, u64::MAX] {
            assert!(!zero.hits(roll), "zero chance hit on {roll}");
            assert!(full.hits(roll), "full chance missed on {roll}");
        }
    }

    /// A bad line is reported and the rest of the file still loads. A drop table that
    /// silently loses a mob because of one typo is worse than one that says so.
    #[test]
    fn a_bad_line_is_reported_and_the_others_survive() {
        let t = DropTables::parse("2 | 4000001 | 40 | 1 | 1\nnonsense\n3 | 4000000 | 5 | 1 | 1\n");
        assert_eq!(t.problems.len(), 1, "{:?}", t.problems);
        assert_eq!(t.for_mob(2).len(), 1);
        assert_eq!(t.for_mob(3).len(), 1);
    }

    /// **The level formula is checked against the rows it was fitted to.**
    ///
    /// Eighteen of the 23 authored meso rows in `data/drops.txt`, level and range as written
    /// by hand. If someone changes the multipliers, this says by how much they have moved
    /// away from the numbers a person chose - which a formula on its own cannot.
    ///
    /// The tolerance is +/-5 mesos or 12%, whichever is larger. That is not a fudge: the
    /// authored rows are themselves rounded and disagree with each other by a few percent
    /// at the same level, so a tighter bound would be asserting noise.
    #[test]
    fn the_level_meso_formula_lands_on_the_hand_authored_rows() {
        // (level, authored min, authored max)
        const AUTHORED: &[(u32, u32, u32)] = &[
            (7, 12, 14),
            (10, 18, 23),
            (11, 19, 23),
            (14, 25, 30),
            (17, 30, 35),
            (19, 36, 44),
            (22, 40, 48),
            (28, 48, 57),
            (30, 50, 60),
            (35, 63, 77),
            (50, 92, 110),
            (53, 95, 116),
            (58, 109, 124),
            (59, 106, 129),
            (80, 148, 176),
            (90, 162, 198),
        ];
        let near = |got: u32, want: u32| {
            let slack = std::cmp::max(5, want * 12 / 100);
            got.abs_diff(want) <= slack
        };
        for &(level, want_min, want_max) in AUTHORED {
            let (min, max) = level_meso_range(level).expect("a levelled mob has a range");
            assert!(near(min, want_min), "level {level}: min {min} vs authored {want_min}");
            assert!(near(max, want_max), "level {level}: max {max} vs authored {want_max}");
            assert!(min <= max, "level {level}: min {min} above max {max}");
        }

        // Never zero: a drop of no mesos is a drop that draws nothing on screen.
        assert_eq!(level_meso_range(1), Some((1, 2)));
        // And a mob with no level is a mob we know nothing about - say so rather than invent.
        assert_eq!(level_meso_range(0), None);
    }

    /// **An authored row wins, and "authored" means it EXISTS, not that it hit.**
    ///
    /// This is what makes a `0`-chance row an opt-out. If the check asked whether a roll
    /// succeeded, a 0-chance row would fall through to the level default every time and the
    /// opt-out would be unwritable - which is how the tutorial and job-advancement mobs the owner
    /// excluded are meant to be excluded.
    #[test]
    fn an_authored_meso_row_is_respected_even_at_zero_chance() {
        let t = DropTables::parse(
            "7 | 4000006 | 40 | 1 | 1 | 10 | Squishy Liquid\n\
             9 | 0 | 0 | 1 | 1 | 1 | mesos (opted out)\n\
             10 | 0 | 100 | 5 | 5 | 1 | mesos\n",
        );
        // Slime's shape: item rows, no meso row at all -> the default applies.
        assert!(!t.has_meso_row(7), "a mob with only item rows has no meso row");
        // Opted out with a zero chance -> still authored, so the default must NOT apply.
        assert!(t.has_meso_row(9), "a zero-chance row is still a row, and it means 'no mesos'");
        assert!(t.has_meso_row(10));
        // A mob with no table at all is not authored either.
        assert!(!t.has_meso_row(999));
    }

    /// **The server's rate scales a mob's own table and never the global one** - v83's rule
    /// (Cosmic `dropGlobalItemsFromMonsterOnMap`). A roll of 15% against a 10% mob row and a
    /// 10% global row: at 2x the mob row hits (20%) and the global one still misses.
    #[test]
    fn the_rate_scales_a_mobs_table_but_not_the_global_one() {
        let t = DropTables::parse("2 | 4000001 | 10 | 1 | 1 | 0 | Snail Shell\n* | 4031065 | 10 | 1 | 1 | 0 | Scroll of Secrets\n");
        let roll = |rate| {
            let mut fifteen = || 150_000u64;
            t.roll_at(2, rate, &mut fifteen).iter().map(|r| r.item_id).collect::<Vec<_>>()
        };
        assert!(roll(store::rates::Rate::NORMAL).is_empty(), "15% misses both at 1x");
        assert_eq!(roll(store::rates::Rate::from_per_cent(200)), vec![4_000_001], "2x: the mob row only");
    }

    /// **The file is v83's**: a guard against a re-scrape quietly putting the old policy back.
    /// Snail (template 2) carries v83's numbers - the shell at 60%, mesos 4-6 at 40%, no equipment
    /// above v83's 0.1287% - and no scroll anywhere in a mob table reaches 1%.
    #[test]
    fn the_drop_file_carries_v83_chances() {
        let tables = DropTables::load(std::path::Path::new("../../data/drops.txt"));
        assert!(tables.problems.is_empty(), "{:?}", tables.problems);
        let snail = tables.for_mob(2);
        let shell = snail.iter().find(|e| e.item_id == 4_000_001).expect("Snail Shell");
        assert_eq!(shell.chance_ppm, 600_000);
        let mesos = snail.iter().find(|e| e.item_id == MESOS).expect("a v83 meso row");
        assert_eq!((mesos.chance_ppm, mesos.min_qty, mesos.max_qty), (400_000, 4, 6));
        assert!(snail.iter().filter(|e| e.item_id > 0 && e.item_id < 2_000_000).all(|e| e.chance_ppm <= 1_287));
        let scrolls: Vec<(u32, u32, u32)> = tables
            .per_mob
            .iter()
            .flat_map(|(m, rows)| rows.iter().map(move |e| (*m, e.item_id, e.chance_ppm)))
            .filter(|&(m, i, c)| m < 700_000 && (2_040_000..2_050_000).contains(&i) && c >= 10_000)
            .collect();
        assert!(scrolls.is_empty(), "scroll rows at 1% or more: {scrolls:?}");
        // The owner, 2026-10-01: *"The non-tutorial Jr. Sentinel should not drop the Jr. Sentinel
        // Shellpiece quest item, but rather the regular etc item."* Two items share the name:
        // 4000000 is the tutorial's quest item, 4000067 the monster's part.
        let jr = tables.for_mob(1_001);
        assert!(jr.iter().any(|e| e.item_id == 4_000_067), "the field Jr. Sentinel drops its own shellpiece");
        assert!(!jr.iter().any(|e| e.item_id == 4_000_000), "and not the tutorial's quest item");
        assert!(tables.for_mob(1).iter().any(|e| e.item_id == 4_000_000), "the tutorial one still does");
        // The owner, 2026-10-01: *"things such as Wand for Magic Attack scrolls do not drop, but
        // they should drop from things like Mano."* v83's Mano does; this client renumbered its
        // scrolls, so they only arrive through `tools/v83_drops.py`'s scroll pairing.
        for wand in [2_043_701u32, 2_043_702] {
            assert!(
                tables.for_mob(700_004).iter().any(|e| e.item_id == wand && e.chance_ppm > 0),
                "Mano must drop Wand Magic Attack Scroll {wand}"
            );
        }
    }

    #[test]
    fn a_missing_file_is_empty_tables_and_a_problem_not_a_panic() {
        let t = DropTables::load(Path::new("data/definitely-not-here.txt"));
        assert_eq!(t.total_entries(), 0);
        assert_eq!(t.problems.len(), 1);
        assert!(t.roll(2, &mut || 0).is_empty());
    }
}
