//! What a mob drops when it dies: a per-template table, plus a global one for events.
//!
//! The **field** side - an item lying on the ground, its object id, expiry, and picking it
//! back up - is `crate::drops`. This module only answers *what* falls, never *where* it
//! goes or *how long* it stays.
//!
//! # Where the data comes from, and what is ours
//!
//! `data/drops.txt`, generated by `tools/scrape_drops.py` from the community database at
//! `meowdb.com/msclassic`. It is **committed rather than gitignored**, unlike everything in
//! `gm-handbook/`: that data is regenerated from the client's own WZ at will, and this
//! cannot be regenerated without network access to a third-party site that may change or
//! disappear. It is authored source in the same sense `data/shops.txt` is.
//!
//! **The item ids are real and the chances are not.** The source gives, per monster, a list
//! of items and a community *vote score* - no drop rates at all. Mesos are the exception:
//! those carry a real `min`, `max` and `dropChancePct`. So every item chance in that file is
//! **our policy**, computed by one function in the scraper from the item's category, and the
//! raw score is kept in a column so the policy can be changed without scraping again.
//!
//! # Two tables, checked in one order
//!
//! The owner: *"when a mob dies, it checks for its mob specific drop table and any global drop
//! table"*. The global table is for event items - there are no events yet, so it is empty,
//! and it exists now so that adding one is a data change rather than a code change.
//!
//! Rolls are **independent**, not a weighted pick of one winner: a mob may drop nothing, or
//! several things, which is how this game behaves.

use std::collections::HashMap;
use std::path::Path;

/// The `itemId` that means **mesos** rather than an item.
///
/// Zero is not a real item id in this game - ids are `1xxxxxx`..`5xxxxxx` - so it is free to
/// use as a marker, and it keeps mesos in the same table as everything else rather than
/// inventing a parallel file for one row per mob. `min_qty`/`max_qty` are then the amount.
pub const MESOS: u32 = 0;

/// The line prefix that means "this row belongs to the global table".
pub const GLOBAL_KEY: &str = "*";

/// Chances are stored in **basis points**, 0..=10000, so `0.01%` is representable and no
/// float ever decides whether an item dropped.
pub const BASIS_POINTS: u32 = 10_000;

/// One row: an item this mob can drop, and how likely it is.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DropEntry {
    /// The game's item id, or [`MESOS`].
    pub item_id: u32,
    /// 0..=[`BASIS_POINTS`]. **Our policy, not measured** - see the module docs.
    pub chance_bp: u32,
    /// Inclusive. For [`MESOS`] this is the amount, not a stack size.
    pub min_qty: u32,
    /// Inclusive, and never below `min_qty` - the loader swaps them if a row has it backwards.
    pub max_qty: u32,
    /// The community vote score the chance was derived from. Kept so the policy can be
    /// recomputed from the file instead of from the network.
    pub score: i32,
    /// For the log line and for reading the file by eye. Not sent to the client.
    pub name: String,
}

impl DropEntry {
    /// Did this entry drop? `roll` is any number; only `roll % BASIS_POINTS` is used.
    ///
    /// `chance_bp == 0` never drops and `chance_bp >= BASIS_POINTS` always does, both
    /// without consuming the roll's meaning - a table with a typo'd 0 is silent rather than
    /// surprising.
    pub fn hits(&self, roll: u64) -> bool {
        if self.chance_bp == 0 {
            return false;
        }
        if self.chance_bp >= BASIS_POINTS {
            return true;
        }
        (roll % u64::from(BASIS_POINTS)) < u64::from(self.chance_bp)
    }

    /// How many, given a second roll. Inclusive of both ends.
    pub fn quantity(&self, roll: u64) -> u32 {
        let span = u64::from(self.max_qty.saturating_sub(self.min_qty)) + 1;
        self.min_qty + (roll % span) as u32
    }
}

/// One thing that actually dropped.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Rolled {
    /// The item id, or [`MESOS`].
    pub item_id: u32,
    /// How many. For [`MESOS`], the amount.
    pub quantity: u32,
}

impl Rolled {
    /// Mesos are not an item and must not be put in a bag slot.
    pub fn is_mesos(&self) -> bool {
        self.item_id == MESOS
    }
}

/// Every mob's drop table, and the global one.
#[derive(Debug, Clone, Default)]
pub struct DropTables {
    per_mob: HashMap<u32, Vec<DropEntry>>,
    global: Vec<DropEntry>,
    /// Lines that would not parse, kept rather than discarded so a bad file is visible in
    /// the startup banner instead of silently dropping a mob's whole table.
    pub problems: Vec<String>,
}

impl DropTables {
    /// Read `data/drops.txt`. A missing file is **not** an error: it yields empty tables and
    /// one problem line, and mobs simply drop nothing.
    ///
    /// Degrading rather than failing is deliberate. This is the only data file sourced from
    /// a third party, so it is the one most likely to be absent on a fresh clone, and a
    /// channel that refuses to start because a fan site's export is missing would be a
    /// worse failure than mobs that drop nothing.
    pub fn load(path: &Path) -> Self {
        match std::fs::read_to_string(path) {
            Ok(text) => Self::parse(&text),
            Err(e) => DropTables {
                problems: vec![format!("{}: {e} - no mob will drop anything", path.display())],
                ..Default::default()
            },
        }
    }

    /// `templateId | itemId | chance% | minQty | maxQty | score | name`
    ///
    /// `#` starts a comment, blank lines are skipped, and a template of `*` puts the row in
    /// the global table. The chance is a **percentage** in the file because that is what a
    /// human editing it will expect; it is stored in basis points.
    pub fn parse(text: &str) -> Self {
        let mut out = DropTables::default();
        for (n, raw) in text.lines().enumerate() {
            let line = raw.split('#').next().unwrap_or("").trim();
            if line.is_empty() {
                continue;
            }
            let cols: Vec<&str> = line.split('|').map(str::trim).collect();
            if cols.len() < 5 {
                out.problems.push(format!("line {}: needs at least 5 columns", n + 1));
                continue;
            }
            let entry = match parse_entry(&cols) {
                Ok(e) => e,
                Err(why) => {
                    out.problems.push(format!("line {}: {why}", n + 1));
                    continue;
                }
            };
            if cols[0] == GLOBAL_KEY {
                out.global.push(entry);
            } else {
                match cols[0].parse::<u32>() {
                    Ok(t) => out.per_mob.entry(t).or_default().push(entry),
                    Err(e) => out.problems.push(format!("line {}: template id: {e}", n + 1)),
                }
            }
        }
        out
    }

    /// Roll everything this mob can drop: **its own table, then the global one**.
    ///
    /// `next` supplies randomness and is called twice per entry - once to decide, once for
    /// the quantity - so a test can hand it a fixed sequence and get a fixed answer. It is a
    /// closure rather than an RNG type because the session's generator is private to the
    /// session, and because a drop table has no business owning one.
    ///
    /// Every entry is rolled independently. A mob can drop nothing at all, and often will.
    pub fn roll(&self, template_id: u32, next: &mut dyn FnMut() -> u64) -> Vec<Rolled> {
        let mine = self.per_mob.get(&template_id).map(Vec::as_slice).unwrap_or(&[]);
        let mut out = Vec::new();
        for entry in mine.iter().chain(self.global.iter()) {
            if entry.hits(next()) {
                out.push(Rolled { item_id: entry.item_id, quantity: entry.quantity(next()) });
            }
        }
        out
    }

    /// This mob's own table, for a GM command or a test.
    pub fn for_mob(&self, template_id: u32) -> &[DropEntry] {
        self.per_mob.get(&template_id).map(Vec::as_slice).unwrap_or(&[])
    }

    /// The global table - event items, rolled for every mob whatever it is.
    pub fn global(&self) -> &[DropEntry] {
        &self.global
    }

    /// How many mobs have a table, for the startup banner.
    pub fn mobs_with_drops(&self) -> usize {
        self.per_mob.len()
    }

    /// Every row, for the banner and for `!drops`.
    pub fn total_entries(&self) -> usize {
        self.per_mob.values().map(Vec::len).sum::<usize>() + self.global.len()
    }
}

fn parse_entry(cols: &[&str]) -> Result<DropEntry, String> {
    let item_id: u32 = cols[1].parse().map_err(|e| format!("item id: {e}"))?;
    let chance_bp = parse_percent(cols[2])?;
    let min_qty: u32 = cols[3].parse().map_err(|e| format!("min qty: {e}"))?;
    let max_qty: u32 = cols[4].parse().map_err(|e| format!("max qty: {e}"))?;
    let score: i32 = cols.get(5).and_then(|s| s.parse().ok()).unwrap_or(0);
    let name = cols.get(6).unwrap_or(&"").to_string();
    // A row with the ends the wrong way round is a transcription slip, not a reason to drop
    // the row: `quantity` would otherwise compute a span from a saturating subtraction and
    // silently always return the larger number.
    let (min_qty, max_qty) = if min_qty > max_qty { (max_qty, min_qty) } else { (min_qty, max_qty) };
    Ok(DropEntry { item_id, chance_bp, min_qty, max_qty, score, name })
}

/// `"40"` -> 4000 bp, `"0.1"` -> 10 bp. Two decimal places, which is the resolution of
/// basis points; anything finer is rounded rather than rejected.
fn parse_percent(s: &str) -> Result<u32, String> {
    let v: f64 = s.parse().map_err(|e| format!("chance: {e}"))?;
    if !(0.0..=100.0).contains(&v) {
        return Err(format!("chance {v} is not a percentage between 0 and 100"));
    }
    Ok((v * 100.0).round() as u32)
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "\
# templateId | itemId | chance% | minQty | maxQty | score | name
2 | 0       | 100 | 2 | 2  | 1 | mesos
2 | 4000001 | 40  | 1 | 1  | 9 | Snail Shell
2 | 1302000 | 1   | 1 | 1  | 3 | Sword
* | 2022000 | 5   | 1 | 3  | 0 | Event Candy
";

    #[test]
    fn a_table_parses_into_a_mob_half_and_a_global_half() {
        let t = DropTables::parse(SAMPLE);
        assert!(t.problems.is_empty(), "{:?}", t.problems);
        assert_eq!(t.for_mob(2).len(), 3);
        assert_eq!(t.global().len(), 1, "the `*` row is global, not mob 2's");
        assert_eq!(t.mobs_with_drops(), 1);
        assert_eq!(t.total_entries(), 4);
        assert_eq!(t.for_mob(2)[0].item_id, MESOS);
        assert_eq!(t.for_mob(2)[1].name, "Snail Shell");
    }

    #[test]
    fn a_percentage_becomes_basis_points() {
        assert_eq!(parse_percent("100").unwrap(), 10_000);
        assert_eq!(parse_percent("40").unwrap(), 4_000);
        assert_eq!(parse_percent("0.1").unwrap(), 10);
        assert_eq!(parse_percent("0").unwrap(), 0);
        assert!(parse_percent("101").is_err(), "a percentage cannot exceed 100");
        assert!(parse_percent("-1").is_err());
    }

    /// **The global table is rolled for every mob, including one with no table of its own.**
    /// That is the whole point of it: an event item drops from anything.
    #[test]
    fn the_global_table_is_rolled_even_for_an_unknown_mob() {
        let t = DropTables::parse(SAMPLE);
        // Always-hit rolls: 0 % 10000 = 0, which is below every non-zero chance.
        let mut always = || 0u64;
        let got = t.roll(9_999_999, &mut always);
        assert_eq!(got.len(), 1, "only the global row exists for an unknown mob");
        assert_eq!(got[0].item_id, 2_022_000);
    }

    #[test]
    fn a_mob_rolls_its_own_table_then_the_global_one() {
        let t = DropTables::parse(SAMPLE);
        let mut always = || 0u64;
        let got = t.roll(2, &mut always);
        let ids: Vec<u32> = got.iter().map(|r| r.item_id).collect();
        assert_eq!(ids, vec![MESOS, 4_000_001, 1_302_000, 2_022_000], "own table first");
    }

    /// A roll that misses everything drops nothing - a mob that always drops is not a mob.
    #[test]
    fn nothing_drops_when_every_roll_misses() {
        let t = DropTables::parse(SAMPLE);
        // 9999 % 10000 = 9999, above every chance in the sample except the 100% mesos row.
        let mut never = || 9_999u64;
        let got = t.roll(2, &mut never);
        assert_eq!(got.len(), 1, "only the guaranteed row survives: {got:?}");
        assert!(got[0].is_mesos());
    }

    #[test]
    fn quantity_covers_both_ends_inclusively() {
        let e = DropEntry {
            item_id: 2_022_000,
            chance_bp: 10_000,
            min_qty: 1,
            max_qty: 3,
            score: 0,
            name: String::new(),
        };
        assert_eq!(e.quantity(0), 1);
        assert_eq!(e.quantity(1), 2);
        assert_eq!(e.quantity(2), 3);
        assert_eq!(e.quantity(3), 1, "and it wraps rather than exceeding max");
    }

    /// A backwards row is repaired, not dropped and not silently always-max.
    #[test]
    fn a_backwards_quantity_range_is_swapped() {
        let t = DropTables::parse("7 | 4000001 | 10 | 5 | 2 | 0 | Backwards\n");
        assert!(t.problems.is_empty());
        let e = &t.for_mob(7)[0];
        assert_eq!((e.min_qty, e.max_qty), (2, 5));
    }

    /// **A zero chance never drops**, so a typo'd row is silent rather than surprising.
    #[test]
    fn a_zero_chance_never_hits_and_a_full_one_always_does() {
        let zero = DropEntry {
            item_id: 1,
            chance_bp: 0,
            min_qty: 1,
            max_qty: 1,
            score: 0,
            name: String::new(),
        };
        let full = DropEntry { chance_bp: BASIS_POINTS, ..zero.clone() };
        for roll in [0u64, 1, 5_000, 9_999, u64::MAX] {
            assert!(!zero.hits(roll), "zero chance hit on {roll}");
            assert!(full.hits(roll), "full chance missed on {roll}");
        }
    }

    /// A bad line is reported and the rest of the file still loads. A drop table that
    /// silently loses a mob because of one typo is worse than one that says so.
    #[test]
    fn a_bad_line_is_reported_and_the_others_survive() {
        let t = DropTables::parse("2 | 4000001 | 40 | 1 | 1\nnonsense\n3 | 4000000 | 5 | 1 | 1\n");
        assert_eq!(t.problems.len(), 1, "{:?}", t.problems);
        assert_eq!(t.for_mob(2).len(), 1);
        assert_eq!(t.for_mob(3).len(), 1);
    }

    #[test]
    fn a_missing_file_is_empty_tables_and_a_problem_not_a_panic() {
        let t = DropTables::load(Path::new("data/definitely-not-here.txt"));
        assert_eq!(t.total_entries(), 0);
        assert_eq!(t.problems.len(), 1);
        assert!(t.roll(2, &mut || 0).is_empty());
    }
}
