//! The floor, so a drop lands somewhere a player can actually reach it.
//!
//! `gm-handbook/footholds.txt` is 94 089 line segments across 426 maps, generated by
//! `tools/dump_portals.py` out of the client's own `Map.wz` `foothold` nodes. **Nothing read
//! it until this module existed**, which is why an item that fell off the edge of a ledge was
//! drawn in mid-air and could never be picked up.
//!
//! # The bug this exists to fix, stated as the client sees it
//!
//! The server states a drop's resting position and the client puts it there. It does not
//! simulate a fall. Today a kill's drops are placed at `(mob.x + k * DROP_STAGGER_PX,
//! mob.y)` - `crates/world/src/session/combat.rs` shadows `x` inside the loop and **never
//! touches `y`** - so every drop keeps the corpse's height no matter how far sideways it
//! went.
//!
//! That is only invisible while the ground is flat. The client's pick-up sweep is a box of
//! `x-0x19..x+0x19` by `y-0x32..y+0x0a` around the player (`research/item-drop.md`, read off
//! the listing), so an item more than **10 pixels below the player's feet** is outside it and
//! cannot be collected however long anyone stands on it. On screen that is indistinguishable
//! from the item not existing.
//!
//! **Measured, no client run spent:** replaying today's placement over every mob spawn point
//! in `gm-handbook/mobs.txt` at the four stagger offsets the kill path actually uses gives
//! 39 712 placements, of which **11 487 are not on any surface** and **3 255 miss by more
//! than the 10 pixels the client's own box allows**. The worst is 2 915 pixels. The working
//! is in `research/drop-placement.md`.
//!
//! # A smaller y is HIGHER UP, and that is measured rather than assumed
//!
//! Getting this backwards inverts the whole rule silently, so it is not taken on trust:
//!
//! * Every map image's `info` node carries `VRTop` and `VRBottom`. Enumerated over **all 426**
//!   map images: **413 have `VRTop < VRBottom`, 13 carry no VR bounds at all, and not one has
//!   `VRTop >= VRBottom`.** The client's own name for the smaller number is *Top*. **[L]**
//! * The pick-up box above is asymmetric - 50 pixels one way, 10 the other - around the
//!   player's position, which is at their feet. The 50 is the side the body is on. **[L]**
//! * Of 10 236 `life` entries that name a foothold, **10 235 sit exactly on it**. The single
//!   exception is NPC 419 on map 10003108, placed at `cy` 1273 on foothold 263 whose y is
//!   1573 - a hovering NPC, 300 px *above* its anchor, and "above" is the numerically smaller
//!   number. **[L]**
//!
//! So: to fall is to gain y, and a platform "above" has a smaller y than the drop.
//!
//! # A foothold is a segment, and a third of them are sloped
//!
//! Of the 94 089 rows: **31 220 are walls** (`x1 == x2`), 35 292 are flat floors, and
//! **27 577 are sloped** (`y1 != y2`). Nothing is degenerate and no map repeats a foothold id.
//!
//! The sloped third is why [`Foothold::surface_y`] interpolates instead of reading `y1`.
//! Reading `y1` would be right 35 292 times and wrong 27 577 times, and wrong by less than an
//! icon's height most of the time - the exact shape of a bug that looks like bad luck.
//!
//! # What this module does NOT use
//!
//! `prev` and `next` are parsed and kept because the file has them, and nothing here reads
//! them. Placing a drop is a question about one vertical line, not about a walk.

use std::collections::HashMap;
use std::path::Path;

/// How far above a drop a platform may be and still be "the platform above it".
///
/// **77 pixels**, and it comes from **this client's own physics table** rather than from a
/// fan site or from `ModernMapleSource` (which `CLAUDE.md` scores at 1 of 8 and which is not
/// consulted here at all):
///
/// ```text
/// target/release/wz-dump cat client-patched/Data/Map/Map_000.wz Physics.img
///     "gravityAcc": 2000.0,
///     "fallSpeed":   670.0,
///     "jumpSpeed":   555.0,
/// ```
///
/// A body launched at `v` against a constant `a` peaks at `v^2 / 2a`, so
/// `555 * 555 / (2 * 2000)` = **77.006** pixels.
///
/// # What is measured and what is not
///
/// **`jumpSpeed` and `gravityAcc` are [L]** - they are literally in the client's `Map.wz`.
/// **The 77 is [I] derived from them** by the closed-form projectile height. The client
/// integrates per frame rather than in closed form, so its true apex is a hair under 77; this
/// is a threshold for "could a player have got up there", not a simulation, and one pixel of
/// slack in a 77-pixel threshold changes no outcome the player can see.
///
/// # The unit check, because `CLAUDE.md` says to make it
///
/// Three bugs this month were a right number in a wrong unit. These are pixels per second and
/// pixels per second squared: `walkSpeed` 125 and `fallSpeed` 670 are a plausible walk and a
/// plausible terminal velocity in those units and in no other, and 77 px is a little over one
/// character's height, which is what a jump in this game looks like. Had the unit been wrong
/// the answer would have been absurd rather than plausible.
///
/// The owner's rule is the reason a jump height is the threshold at all: *"it should fall onto the
/// platform above it (since item will arc upwards about the same distance of a player's
/// jump)"*.
pub const JUMP_HEIGHT_PX: i32 = 77;

/// How many unparseable lines are kept for the banner before it starts counting instead.
///
/// `DropTables` keeps every problem line, and its file is 993 rows. This one is 94 089, and a
/// file that is garbage all the way down would otherwise put 94 089 lines into the startup
/// banner - which is the same as printing nothing, because nobody reads it.
const PROBLEMS_KEPT: usize = 8;

/// One floor segment, exactly as the WZ has it.
///
/// Coordinates are `i32` although every one of them measured fits in `i16` (the whole file
/// spans x `-5570..6338` and y `-4187..3900`). The wire fields are `i16`, so the conversion
/// back happens once, at the end, where it can be checked - see [`Footholds::landing`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Foothold {
    /// The WZ's own id for this segment, unique within its map (verified: 0 duplicates
    /// across all 94 089 rows). Carried so a log line and a test can name a landing.
    pub id: u32,
    pub x1: i32,
    pub y1: i32,
    pub x2: i32,
    pub y2: i32,
    /// The WZ's `prev`. **Nothing in this module reads it** - see the module docs.
    pub prev: i32,
    /// The WZ's `next`. **Nothing in this module reads it.**
    pub next: i32,
}

impl Foothold {
    /// Is this a wall rather than a floor?
    ///
    /// The file's own header says it: *"A wall is a segment with `x1 == x2`; those are
    /// somewhere to bump into rather than somewhere to stand, and the server skips them when
    /// placing a drop."* 31 220 of the 94 089 rows are walls.
    ///
    /// A wall is never a landing surface, and that is not a policy choice - a vertical segment
    /// has no single y at a given x, so there is nothing to land *on*.
    pub fn is_wall(&self) -> bool {
        self.x1 == self.x2
    }

    /// The surface height at `x`, or `None` if this segment is a wall or does not span `x`.
    ///
    /// The span is **inclusive at both ends**, which matters: where a floor stops at a cliff
    /// the wall's x and the floor's last x are the same number, and an exclusive bound there
    /// would open a one-pixel hole in the floor at the exact place drops go wrong.
    ///
    /// The interpolation divides, so a sloped segment can be up to **one pixel** off. That
    /// cannot matter: the client's pick-up box reaches 50 px above the player's feet and 10
    /// below, so a one-pixel error is inside the smaller tolerance seven times over.
    pub fn surface_y(&self, x: i32) -> Option<i32> {
        if self.is_wall() {
            return None;
        }
        let (lo, hi) = if self.x1 <= self.x2 { (self.x1, self.x2) } else { (self.x2, self.x1) };
        if x < lo || x > hi {
            return None;
        }
        // i64 so no product can overflow, whatever a future map does. The widest span in the
        // file is about 12 000 px and the greatest rise about 8 000.
        let dx = i64::from(self.x2) - i64::from(self.x1);
        let dy = i64::from(self.y2) - i64::from(self.y1);
        let y = i64::from(self.y1) + dy * (i64::from(x) - i64::from(self.x1)) / dx;
        Some(y as i32)
    }
}

/// How a drop got to where it came to rest.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Landed {
    /// It fell straight down onto the nearest floor below - the ordinary case, and the one
    /// that covers a drop that was already standing on the ground.
    Fell,
    /// It was inside terrain, and the platform above was within [`JUMP_HEIGHT_PX`].
    LiftedToPlatformAbove,
}

/// Where a drop comes to rest, and why.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Landing {
    /// Unchanged from the point asked about. **A drop never moves sideways here.** The arc
    /// already decided where it went; this module only decides how far it sank or rose.
    pub x: i16,
    /// The surface it came to rest on.
    pub y: i16,
    /// Which foothold it is lying on, by the WZ's own id.
    pub foothold: u32,
    /// How it got there.
    pub how: Landed,
    /// How far it moved, in pixels, always positive. Down for [`Landed::Fell`], up for
    /// [`Landed::LiftedToPlatformAbove`].
    pub moved: i32,
}

impl Landing {
    /// One line for `world.log`, in the style the rest of this crate uses.
    pub fn what(&self) -> String {
        match self.how {
            Landed::Fell => format!(
                "drop placement: fell {} px onto foothold {} at ({}, {})",
                self.moved, self.foothold, self.x, self.y
            ),
            Landed::LiftedToPlatformAbove => format!(
                "drop placement: clipped into terrain, lifted {} px onto the platform above \
                 (foothold {}) at ({}, {}) - within the {JUMP_HEIGHT_PX} px a player's jump \
                 reaches",
                self.moved, self.foothold, self.x, self.y
            ),
        }
    }
}

/// Every map's floor, keyed by map id.
///
/// Loaded once at startup and never mutated, exactly like [`crate::config::Config::fields`]
/// and [`crate::droptables::DropTables`]. Every query on it is a pure function of the table
/// and the point asked about, so all of it is a unit test.
#[derive(Debug, Clone, Default)]
pub struct Footholds {
    by_map: HashMap<u32, Vec<Foothold>>,
    /// Where it was read from, for the banner. Empty for a [`Default`] table.
    source: String,
    /// Lines that would not parse. Capped at [`PROBLEMS_KEPT`]; see [`Footholds::problems`].
    problems: Vec<String>,
    /// How many lines would not parse in total, including the ones not kept.
    problem_count: usize,
    walls: usize,
    floors: usize,
}

impl Footholds {
    /// Read `gm-handbook/footholds.txt`.
    ///
    /// **A missing file is not an error and must not be one.** `gm-handbook/` is generated
    /// and gitignored, so it can legitimately be absent on a fresh clone, and a channel that
    /// refuses to start because of it would be a worse failure than the one this module fixes.
    ///
    /// It degrades to **today's behaviour** - every query returns `None` and
    /// [`Footholds::rest_at`] hands back the caller's own fallback, which is where the mob
    /// died. It does not degrade to anything untested.
    ///
    /// # It must be LOUD, and on stdout
    ///
    /// `STATUS.md`, 2026-08-20: `Config::map_exists` was fail-open on an empty field table,
    /// *"so a missing generated file silently removes the `!map` guard. There **was** a
    /// warning for that, on **stderr**, where nothing reads it"* - `world.log.err`, which is
    /// not the file anyone opens while a client is running. It cost a client run and a crash.
    ///
    /// So this type does not warn; it hands the caller [`Footholds::banner`], a line that says
    /// which of the two states it is in either way, meant for `println!`. A banner that only
    /// speaks up when something is wrong is a banner nobody can tell apart from one that is
    /// not being printed at all.
    pub fn load(path: &Path) -> Self {
        match std::fs::read_to_string(path) {
            Ok(text) => Footholds { source: path.display().to_string(), ..Self::parse(&text) },
            Err(e) => Footholds {
                source: path.display().to_string(),
                problems: vec![format!("{}: {e}", path.display())],
                problem_count: 1,
                ..Default::default()
            },
        }
    }

    /// `map, id, x1, y1, x2, y2, prev, next`, `#` starting a comment.
    ///
    /// A short or unparseable row is skipped and counted rather than aborting the load: this
    /// file is regenerated from the client and one bad row must not cost every map its floor.
    pub fn parse(text: &str) -> Self {
        let mut out = Footholds::default();
        for (n, raw) in text.lines().enumerate() {
            let line = raw.split('#').next().unwrap_or("").trim();
            if line.is_empty() {
                continue;
            }
            let f: Vec<&str> = line.split(',').map(str::trim).collect();
            if f.len() < 6 {
                out.note_problem(n + 1, "needs at least 6 columns: map, id, x1, y1, x2, y2");
                continue;
            }
            let n32 = |i: usize| f.get(i).and_then(|v| v.parse::<i32>().ok());
            let (Some(map), Some(id), Some(x1), Some(y1), Some(x2), Some(y2)) =
                (n32(0), n32(1), n32(2), n32(3), n32(4), n32(5))
            else {
                out.note_problem(n + 1, "a column is not a whole number");
                continue;
            };
            let Ok(map) = u32::try_from(map) else {
                out.note_problem(n + 1, "a negative map id");
                continue;
            };
            let fh = Foothold {
                id: u32::try_from(id).unwrap_or(0),
                x1,
                y1,
                x2,
                y2,
                prev: n32(6).unwrap_or(0),
                next: n32(7).unwrap_or(0),
            };
            if fh.is_wall() {
                out.walls += 1;
            } else {
                out.floors += 1;
            }
            out.by_map.entry(map).or_default().push(fh);
        }
        // Sorted by id so that two footholds the same distance away break their tie the same
        // way on every run. Packet-order stability is a property this crate's tests pin.
        for list in out.by_map.values_mut() {
            list.sort_by_key(|f| f.id);
        }
        out
    }

    fn note_problem(&mut self, line: usize, why: &str) {
        self.problem_count += 1;
        if self.problems.len() < PROBLEMS_KEPT {
            self.problems.push(format!("line {line}: {why}"));
        }
    }

    /// **The startup line. Print it with `println!`, always, in both states.**
    ///
    /// See [`Footholds::load`] for why this exists rather than an `eprintln!` that fires only
    /// on failure.
    pub fn banner(&self) -> String {
        let from = if self.source.is_empty() { "(no file)" } else { self.source.as_str() };
        if self.is_empty() {
            return format!(
                "maplecw-world: footholds: NONE LOADED from {from}. Drops will land at the \
                 exact height the mob died at, which puts them inside terrain wherever the \
                 ground is not flat - and an item more than 10 px below the player's feet is \
                 outside the client's own pick-up box and can never be collected. Regenerate \
                 with: python tools/dump_portals.py"
            );
        }
        format!(
            "maplecw-world: footholds: {} segments across {} maps ({} floors, {} walls which \
             are never landed on)",
            self.len(),
            self.maps(),
            self.floors,
            self.walls
        )
    }

    /// Lines that would not parse, capped. Print them beside the banner.
    pub fn problems(&self) -> Vec<String> {
        let mut out = self.problems.clone();
        if self.problem_count > out.len() {
            out.push(format!("... and {} more unparseable lines", self.problem_count - out.len()));
        }
        out
    }

    /// How many segments were loaded, over every map.
    pub fn len(&self) -> usize {
        self.walls + self.floors
    }

    /// Is there no floor data at all? Then every query answers `None` - see
    /// [`Footholds::load`].
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// How many maps have any floor at all.
    pub fn maps(&self) -> usize {
        self.by_map.len()
    }

    /// Does this table know anything about that map?
    ///
    /// **Deliberately NOT a `map_exists`-style fail-open.** `Config::map_exists` answers
    /// `true` for everything when its table is empty, and that turned out to remove the
    /// `!map` guard entirely when the file went missing. Here the fail-open direction is the
    /// caller's fallback instead: an unknown map yields no landing, and the caller keeps the
    /// position it already had, which is the position the mob was standing on.
    pub fn has_map(&self, map: u32) -> bool {
        self.by_map.contains_key(&map)
    }

    /// Every foothold on a map, in id order. For tests and for a future consumer.
    pub fn on_map(&self, map: u32) -> &[Foothold] {
        self.by_map.get(&map).map(Vec::as_slice).unwrap_or(&[])
    }

    /// **Where a drop aimed at `(x, y)` actually comes to rest.** The whole point of the
    /// module, and a pure function of the table.
    ///
    /// # The owner's rule, and how these three lines cover it
    ///
    /// > *"Problem with mob drops, if they were to drop into the wall, please do not make it
    /// > so that it cannot be retrieved. If it clips into the wall, it should fall onto the
    /// > platform above it (since item will arc upwards about the same distance of a player's
    /// > jump). If it won't reach that platform, it should fall down to the next available
    /// > platform below."*
    ///
    /// Take the **nearest walkable surface** on the vertical line through `x`. If the nearest
    /// one is *above* the point, accept it only when the rise is within [`JUMP_HEIGHT_PX`];
    /// otherwise take the nearest one *below*.
    ///
    /// That is one comparison, and it reproduces every case rather than special-casing them:
    ///
    /// | the point is | nearest above | nearest below | answer |
    /// |---|---|---|---|
    /// | standing on flat ground | a ceiling, far | the ground itself, **0 px** | stays exactly where it is |
    /// | over the edge of a ledge | nothing, or far | the floor beneath, 60 px | falls 60 - items do fall |
    /// | clipped into a step | the step, 30 px | the cliff bottom, 200 px | **lifted 30 onto the step** |
    /// | clipped into a cliff face | the clifftop, 200 px | the cliff bottom, 400 px | too high to reach: **falls 400** |
    /// | between two floors, 40 up and 10 down | 40 | 10 | falls 10 - the nearer surface, and the physical one |
    ///
    /// **A tie goes to falling.** `da < db` rather than `<=`, because dropping is what an
    /// object does when nothing stops it, and because a rule that lifts an item on a tie
    /// would lift one that was already resting on the ground.
    ///
    /// # Why walls need no special case beyond being excluded
    ///
    /// A wall is not a surface, so [`Foothold::surface_y`] returns `None` for one and it never
    /// enters either candidate list. It does not additionally have to be *detected*: a point
    /// buried in a cliff face has the clifftop above it and the cliff bottom below it, and
    /// those two distances are what the rule already compares.
    ///
    /// # `None` means "keep what you had"
    ///
    /// Returned when the map is not in the table, when the table is empty, when nothing
    /// walkable spans that `x` at all, and when the only surface is above and out of jump
    /// reach. In every one of those the caller's own position is the better answer, because
    /// the caller's position is where the mob was standing and a mob stands on a foothold.
    /// [`Footholds::rest_at`] makes that the only thing a call site can do.
    pub fn landing(&self, map: u32, x: i16, y: i16) -> Option<Landing> {
        let list = self.by_map.get(&map)?;
        let (px, py) = (i32::from(x), i32::from(y));

        // (distance, foothold id, surface y). Ties break on the lower id so that two runs
        // over the same table place a drop identically.
        let mut below: Option<(i32, u32, i32)> = None;
        let mut above: Option<(i32, u32, i32)> = None;
        for fh in list {
            let Some(sy) = fh.surface_y(px) else { continue };
            let slot = if sy >= py { &mut below } else { &mut above };
            let d = (sy - py).abs();
            if slot.is_none_or(|(bd, bid, _)| d < bd || (d == bd && fh.id < bid)) {
                *slot = Some((d, fh.id, sy));
            }
        }

        let lift_is_better = match (above, below) {
            (Some((da, _, _)), Some((db, _, _))) => da < db && da <= JUMP_HEIGHT_PX,
            (Some((da, _, _)), None) => da <= JUMP_HEIGHT_PX,
            (None, _) => false,
        };
        let (moved, foothold, sy, how) = if lift_is_better {
            let (d, id, sy) = above?;
            (d, id, sy, Landed::LiftedToPlatformAbove)
        } else {
            let (d, id, sy) = below?;
            (d, id, sy, Landed::Fell)
        };
        // The wire carries i16. Every coordinate in the file fits (x -5570..6338, y
        // -4187..3900), so this cannot fire today; if a future map put one outside, refusing
        // and letting the caller keep its own position beats sending a wrapped number.
        let y = i16::try_from(sy).ok()?;
        Some(Landing { x, y, foothold, how, moved })
    }

    /// [`Footholds::landing`], reduced to the pair of numbers a drop packet wants.
    ///
    /// `fallback` is what today's code would have used - **the mob's own death position** for
    /// a kill, and the player's own position for an item dragged out of the bag. It is a
    /// parameter rather than `(x, y)` because for a kill those are not the same point: `x` is
    /// staggered sideways and may be over a void, while the corpse's position is a place a mob
    /// was standing and therefore certainly a floor.
    pub fn rest_at(&self, map: u32, x: i16, y: i16, fallback: (i16, i16)) -> (i16, i16) {
        match self.landing(map, x, y) {
            Some(l) => (l.x, l.y),
            None => fallback,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A small hand-written map, drawn here so the tests read as pictures rather than as
    /// numbers. **y grows downward** - see the module docs, where that is measured.
    ///
    /// ```text
    ///  y=100        A================                 (x 100..300)  a high ledge
    ///                               |
    ///  y=160                        | B               (x=300)       the cliff face, a WALL
    ///                               |
    ///  y=200                        C==============   (x 300..500)  the ground
    ///
    ///  y=400                                  D====   (x 600..800)  a low floor, no roof
    /// ```
    const MAP: u32 = 7;
    const FIXTURE: &str = "\
# map, id, x1, y1, x2, y2, prev, next
7, 1, 100, 100, 300, 100, 0, 2
7, 2, 300, 100, 300, 200, 1, 3
7, 3, 300, 200, 500, 200, 2, 0
7, 4, 600, 400, 800, 400, 0, 0
";

    fn fixture() -> Footholds {
        let t = Footholds::parse(FIXTURE);
        assert_eq!(t.len(), 4, "the fixture itself must parse, or every test below is vacuous");
        assert_eq!(t.walls, 1);
        assert_eq!(t.floors, 3);
        t
    }

    // ------------------------------------------------------------------------------
    // The rule
    // ------------------------------------------------------------------------------

    /// **Flat.** An item already standing on the ground does not move at all.
    #[test]
    fn a_drop_on_flat_ground_stays_where_it_is() {
        let t = fixture();
        let l = t.landing(MAP, 400, 200).expect("the ground is right there");
        assert_eq!((l.x, l.y), (400, 200));
        assert_eq!(l.foothold, 3);
        assert_eq!(l.how, Landed::Fell);
        assert_eq!(l.moved, 0, "a tie between 'lift' and 'stay' must not lift");
    }

    /// **The ledge edge - today's bug, in one assertion.** A mob dies at x=290 on the high
    /// ledge (y=100) and a drop staggers 20 px right, to x=310. Today it would be placed at
    /// (310, 100): 100 px above the floor, drawn in mid-air, and outside the client's pick-up
    /// box for anyone standing under it.
    #[test]
    fn a_drop_past_the_edge_of_a_ledge_falls_to_the_floor_below() {
        let t = fixture();
        let l = t.landing(MAP, 310, 100).expect("there is a floor under it");
        assert_eq!(l.y, 200, "it lands on the ground, not in the air at 100");
        assert_eq!(l.foothold, 3);
        assert_eq!(l.how, Landed::Fell);
        assert_eq!(l.moved, 100);
        assert_eq!(l.x, 310, "and it does NOT move sideways");
    }

    /// **Inside the wall.** A mob dies at x=310 on the ground (y=200) and a drop staggers 20
    /// px left, to x=290 - which is *under the high ledge*, 100 px inside the cliff. Today it
    /// would be placed at (290, 200) with the ledge's floor overhead, unreachable.
    ///
    /// The lift is 100 px, which is **more** than a jump, so the owner's second clause applies:
    /// *"If it won't reach that platform, it should fall down to the next available platform
    /// below."* There is nothing below at x=290, so nothing is claimed - the caller keeps the
    /// corpse's own position, which is a floor by construction.
    #[test]
    fn a_drop_buried_deeper_than_a_jump_does_not_teleport_up() {
        let t = fixture();
        // Read the drop out of the fixture rather than restating it, so that editing the
        // picture at the top cannot leave this test asserting something it no longer sets up.
        let ledge = t.on_map(MAP).iter().find(|f| f.id == 1).unwrap().y1;
        let ground = t.on_map(MAP).iter().find(|f| f.id == 3).unwrap().y1;
        assert!(ground - ledge > JUMP_HEIGHT_PX, "the fixture's lift must be out of reach");
        assert_eq!(t.landing(MAP, 290, 200), None);
        // ...and the call site therefore keeps what it had.
        assert_eq!(t.rest_at(MAP, 290, 200, (310, 200)), (310, 200));
    }

    /// **Inside the wall, within a jump.** The same geometry, 60 px in rather than 100:
    /// the ledge above is reachable, so the item goes up onto it. This is the owner's rule verbatim.
    #[test]
    fn a_drop_clipped_into_terrain_is_lifted_onto_the_platform_above() {
        let t = fixture();
        let l = t.landing(MAP, 290, 160).expect("the ledge overhead is within a jump");
        assert_eq!(l.y, 100, "up onto the ledge");
        assert_eq!(l.foothold, 1);
        assert_eq!(l.how, Landed::LiftedToPlatformAbove);
        assert_eq!(l.moved, 60);
    }

    /// The jump cap is a real boundary and is checked on both sides of itself, so a change to
    /// [`JUMP_HEIGHT_PX`] cannot pass this file unnoticed.
    #[test]
    fn the_lift_stops_exactly_at_a_players_jump() {
        let t = fixture();
        // The ledge is at y=100. A drop at 100 + JUMP is exactly reachable.
        let reach = 100 + JUMP_HEIGHT_PX as i16;
        let l = t.landing(MAP, 290, reach).expect("exactly a jump away");
        assert_eq!((l.y, l.how), (100, Landed::LiftedToPlatformAbove));
        // One pixel further down and it is not, and there is no floor below at x=290.
        assert_eq!(t.landing(MAP, 290, reach + 1), None);
    }

    /// **Falling beats a lift when the floor below is nearer**, even though the platform above
    /// is within a jump. An item between two surfaces does what an object does.
    #[test]
    fn the_nearer_surface_wins_and_a_tie_falls() {
        // A ceiling-and-floor pair 40 apart, with the point 10 above the floor.
        let t = Footholds::parse("9, 1, 0, 100, 200, 100, 0, 0\n9, 2, 0, 150, 200, 150, 0, 0\n");
        let l = t.landing(9, 100, 140).expect("both are within a jump");
        assert_eq!((l.y, l.how, l.moved), (150, Landed::Fell, 10));
        // Dead centre: 25 either way. The tie falls.
        let l = t.landing(9, 100, 125).unwrap();
        assert_eq!((l.y, l.how, l.moved), (150, Landed::Fell, 25));
        // Nearer the ceiling: now it lifts.
        let l = t.landing(9, 100, 110).unwrap();
        assert_eq!((l.y, l.how, l.moved), (100, Landed::LiftedToPlatformAbove, 10));
    }

    /// **No platform anywhere.** x=550 is between the ground (ends at 500) and the low floor
    /// (starts at 600). Nothing spans it, so nothing is claimed.
    #[test]
    fn a_drop_over_a_gap_with_no_floor_at_all_claims_nothing() {
        let t = fixture();
        assert_eq!(t.landing(MAP, 550, 200), None);
        assert_eq!(t.rest_at(MAP, 550, 200, (480, 200)), (480, 200), "the caller keeps its own");
    }

    /// **A map that is not in the table.** Not fail-open: no landing, so the caller keeps
    /// what it had. `Config::map_exists` answering `true` for everything on an empty table is
    /// the mistake this is deliberately not repeating.
    #[test]
    fn a_map_with_no_data_claims_nothing() {
        let t = fixture();
        assert!(!t.has_map(999));
        assert_eq!(t.landing(999, 400, 200), None);
        assert_eq!(t.rest_at(999, 400, 200, (400, 200)), (400, 200));
    }

    // ------------------------------------------------------------------------------
    // Walls, slopes and spans
    // ------------------------------------------------------------------------------

    /// A wall is never a landing surface. 31 220 of the 94 089 real rows are walls, so a rule
    /// that could stand on one would be wrong a third of the time.
    #[test]
    fn a_wall_is_never_landed_on() {
        let t = fixture();
        let wall = t.on_map(MAP).iter().find(|f| f.id == 2).unwrap();
        assert!(wall.is_wall());
        assert_eq!(wall.surface_y(300), None, "a vertical segment has no single height at x");
        // x=300 is the wall's x AND the inclusive end of both floors. A drop there lands on a
        // floor, never on the wall.
        let l = t.landing(MAP, 300, 150).expect("both floors touch x=300");
        assert_ne!(l.foothold, 2);
    }

    /// **Slopes interpolate.** 27 577 of the 94 089 real rows are sloped, so reading `y1`
    /// would be wrong on nearly a third of the floor in this game.
    #[test]
    fn a_sloped_floor_is_interpolated_not_read_off_one_end() {
        // Down 100 over 200 px, left to right.
        let t = Footholds::parse("5, 1, 0, 100, 200, 200, 0, 0\n");
        let fh = t.on_map(5)[0];
        assert_eq!(fh.surface_y(0), Some(100));
        assert_eq!(fh.surface_y(100), Some(150), "the middle, not either end");
        assert_eq!(fh.surface_y(200), Some(200));
        assert_eq!(fh.surface_y(201), None, "and it stops where it stops");
        assert_eq!(t.landing(5, 100, 0).unwrap().y, 150);
    }

    /// A segment written right-to-left is the same floor. The WZ has them both ways round.
    #[test]
    fn a_segment_written_backwards_spans_the_same_ground() {
        let t = Footholds::parse("5, 1, 200, 200, 0, 100, 0, 0\n");
        let fh = t.on_map(5)[0];
        assert_eq!(fh.surface_y(100), Some(150));
        assert_eq!(fh.surface_y(0), Some(100));
        assert_eq!(fh.surface_y(200), Some(200));
        assert_eq!(fh.surface_y(-1), None);
    }

    /// Both ends are inclusive. An exclusive bound would put a one-pixel hole in the floor at
    /// exactly the cliff edges where drops go wrong in the first place.
    #[test]
    fn a_span_includes_both_of_its_ends() {
        let t = fixture();
        assert_eq!(t.on_map(MAP)[0].surface_y(100), Some(100));
        assert_eq!(t.on_map(MAP)[0].surface_y(300), Some(100));
        assert_eq!(t.on_map(MAP)[0].surface_y(99), None);
        assert_eq!(t.on_map(MAP)[0].surface_y(301), None);
    }

    // ------------------------------------------------------------------------------
    // Loading, and being loud about it
    // ------------------------------------------------------------------------------

    /// **A missing file degrades to today's behaviour and says so on stdout.**
    #[test]
    fn a_missing_file_is_empty_loud_and_harmless() {
        let t = Footholds::load(Path::new("gm-handbook/there-is-no-such-file.txt"));
        assert!(t.is_empty());
        assert_eq!(t.landing(1, 0, 0), None, "every query answers 'keep what you had'");
        assert_eq!(t.rest_at(1, 999, 999, (5, 5)), (5, 5));
        let b = t.banner();
        assert!(b.contains("NONE LOADED"), "the banner must name the state: {b}");
        assert!(b.contains("dump_portals.py"), "and say how to fix it: {b}");
        assert!(!t.problems().is_empty());
    }

    /// A default table is the same shape, and its banner does not claim a filename it has not
    /// got.
    #[test]
    fn a_default_table_is_empty_and_still_says_so() {
        let t = Footholds::default();
        assert!(t.is_empty());
        assert!(t.banner().contains("NONE LOADED"));
    }

    /// A loaded table says how much it loaded. It is printed in both states on purpose: a
    /// banner that is silent when things are fine cannot be told apart from one that is not
    /// being printed at all, which is exactly how the `!map` guard went missing.
    #[test]
    fn a_loaded_table_reports_its_size() {
        let t = fixture();
        let b = t.banner();
        assert!(b.contains("4 segments"), "{b}");
        assert!(b.contains("1 maps"), "{b}");
        assert!(b.contains("3 floors"), "{b}");
        assert!(b.contains("1 walls"), "{b}");
        assert!(!b.contains("NONE LOADED"));
    }

    /// One bad row must not cost a map its floor, and the banner must not become 94 089 lines.
    #[test]
    fn bad_rows_are_skipped_and_counted_rather_than_printed_forever() {
        let mut text = String::from("7, 1, 100, 100, 300, 100, 0, 2\n");
        for i in 0..50 {
            text.push_str(&format!("this is not a foothold {i}\n"));
        }
        let t = Footholds::parse(&text);
        assert_eq!(t.len(), 1, "the good row survived");
        let p = t.problems();
        assert_eq!(p.len(), PROBLEMS_KEPT + 1, "capped, plus the 'and N more' line");
        assert!(p.last().unwrap().contains("and 42 more"), "{p:?}");
    }

    /// Comments and blank lines are ignored - the real file starts with four comment lines.
    #[test]
    fn the_real_files_header_parses_to_nothing() {
        let header = "# map, id, x1, y1, x2, y2, prev, next - generated by tools/dump_portals.py\n\
                      # A foothold is one floor SEGMENT between (x1,y1) and (x2,y2). A wall is\n\
                      \n";
        assert!(Footholds::parse(header).is_empty());
    }

    // ------------------------------------------------------------------------------
    // Against the real table, when it is there
    // ------------------------------------------------------------------------------

    /// **The drift instrument.** `gm-handbook/` is generated and gitignored, so this skips
    /// itself when the file is absent rather than failing a fresh clone - the same
    /// arrangement `store::inventory` and `net::quest` use for their generated tables.
    ///
    /// It exists because every number in this module's docs was measured off that file, and a
    /// regenerated file that disagreed with them would otherwise go unnoticed.
    #[test]
    fn the_real_table_has_the_shape_the_docs_claim() {
        let path = Path::new("../../gm-handbook/footholds.txt");
        if !path.exists() {
            eprintln!("skipped: {} is generated and gitignored", path.display());
            return;
        }
        let t = Footholds::load(path);
        assert_eq!(t.problems(), Vec::<String>::new(), "the generated file parses cleanly");
        assert_eq!(t.len(), 94_089);
        assert_eq!(t.maps(), 426);
        assert_eq!(t.walls, 31_220, "a third of the file is walls, and none is landed on");
        assert_eq!(t.floors, 62_869);

        // Map 1, x=740, has exactly two surfaces: foothold 7 at y=125 and foothold 24 at
        // y=365. A drop in the air between them at y=300 is 175 below the upper one - far
        // more than a jump - and 65 above the lower, so it falls. This is the whole rule
        // exercised on real data rather than on the fixture.
        let l = t.landing(1, 740, 300).expect("map 1 has floor under x=740");
        assert_eq!((l.y, l.foothold, l.how, l.moved), (365, 24, Landed::Fell, 65));
        // ...and from just under the upper platform it is lifted back onto it instead.
        let l = t.landing(1, 740, 125 + 40).expect("the platform above is within a jump");
        assert_eq!((l.y, l.foothold, l.how), (125, 7, Landed::LiftedToPlatformAbove));

        // The one property every landing must have, checked over a real map rather than a
        // fixture: whatever comes back is ON a foothold of that map, at that x.
        for x in (300..1200).step_by(37) {
            let Some(l) = t.landing(1, x, 300) else { continue };
            let fh = t.on_map(1).iter().find(|f| f.id == l.foothold).expect("a real foothold");
            assert_eq!(fh.surface_y(i32::from(x)), Some(i32::from(l.y)), "at x={x}");
            assert!(!fh.is_wall(), "never a wall, at x={x}");
        }
    }
}
