//! What a character has to be **holding** before each first-job skill will cast.
//!
//! The owner wants to test all 24 first-job skills across the four branches in one session. Half
//! of them are gated on a weapon and two on ammunition, and a client run costs a manual
//! launch - so the concrete item ids belong in the repo before they start, not in the middle
//! of the run.
//!
//! Nothing here is wired. See the `WIRE IT LIKE THIS` note at the bottom of this file for
//! the `!kit` GM command this table exists to feed.
//!
//! # Where every number in this file came from
//!
//! * **`[L]`** - read off this client. `gm-handbook/skills.txt` (generated by
//!   `tools/dump_skills.py` from `Data/Skill/Skill_000.wz`), `gm-handbook/items.txt`,
//!   `gm-handbook/itemdata.txt`, and - for the requirement fields, which the generated files
//!   do **not** carry - the `info` node of each weapon image read directly out of
//!   `client-patched/Data/Character/Weapon/Weapon_000.wz` with `target/release/wz-dump.exe`.
//! * **`[D]`** - derived from two or more of those.
//! * **`[I]`** - inferred. There is very little of it here and every instance says so.
//!
//! # The gates, measured. `weapon` is absent far more often than expected
//!
//! All 24 first-job skills were enumerated out of `gm-handbook/skills.txt` and their
//! `weapon`, `weapon2`, `weapon3`, `weapon4`, `bulletConsume`, `bulletCount` and
//! `noBulletConsume` columns collapsed across every level. **[L]** Only **five of the
//! twenty-four** carry a `weapon` column at all:
//!
//! | skill | id | `weapon` | `weapon2` | `bulletConsume` | `bulletCount` |
//! |---|---:|---:|---:|---:|---:|
//! | Arrow Blow | 3001001 | 45 | 46 | 1 | 1 |
//! | Double Shot | 3001002 | 45 | 46 | 2 | 2 |
//! | Power Knockback | 3001003 | 45 | 46 | - | - |
//! | Double Stab | 4001002 | 33 | - | - | - |
//! | Lucky Seven | 4001003 | 47 | - | **-** | 2 |
//!
//! The other nineteen have **every one of those seven columns empty**, and an empty cell in
//! that file means the property is absent from the WZ node, which is not the same as `0`.
//! So **no Warrior skill and no Magician skill is gated on a weapon** - including Power
//! Strike, Slash Blast, Energy Bolt and Magic Claw. **[L]**
//!
//! Every one of those columns is the same on all of a first-job skill's levels, so one
//! [`SkillGate`] per skill is a faithful description. **That is true of these 24 and not of
//! the file** - `3111002` Arrow Rain, a second-job skill, is `bulletConsume 7` at some levels
//! and `8` at others. The test below asserts the invariance only where this module relies on
//! it, and uses Arrow Rain as the control that its parse can see variation at all; an earlier
//! version asserted it file-wide and was wrong.
//!
//! ## `bulletCount` is not an ammunition requirement, and that trap is live
//!
//! Energy Bolt (2001002) carries `bulletCount = 1` and **no weapon column and no
//! `bulletConsume`** - it is a wand spell. `research/magician-first-job.md` reads the column
//! as *"projectiles per cast"* **[L]**, from Energy Bolt's own `common` node. So a
//! `bulletCount` says how many things fly out of the caster, not how many leave the bag.
//!
//! That matters for exactly one row above: **Lucky Seven has `bulletCount 2` and no
//! `bulletConsume` at all**, where Arrow Blow and Double Shot both carry one. Read off the
//! WZ alone, Lucky Seven is *not* gated on ammunition - see [`Piece::unlocks`] and the
//! honest hedge on the throwing stars in [`THIEF`].
//!
//! # The weapon-type numbering is the client's own, and [`crate::damage::WeaponClass`] owns it
//!
//! `research/damage-formula.md` §1.3: `FUN_14025e000` opens `lea eax,[r8-0x1e] / cmp eax,0x11
//! / ja`, so the client's weapon switch covers exactly **30..=47**, it is `itemId / 10000 -
//! 100`, and `Skill.wz` puts the same code in a skill's `weapon` field. **[L]** This module
//! does not restate that mapping - it calls [`crate::damage::WeaponClass::from_code`] and
//! [`crate::damage::WeaponClass::from_item_id`], and adds only the plain-English name
//! ([`weapon_name`]) that the enum does not carry.
//!
//! Every distinct `weapon` value anywhere in `skills.txt` is `{30, 31, 32, 33, 43, 44, 45,
//! 46, 47}` and every one of them resolves through `WeaponClass::from_code`. **[L]** - there
//! is no code in the skill archive that the damage module cannot name.
//!
//! # Ammunition lives in the USE tab, and that is now [L] rather than [I]
//!
//! **This was the question most likely to sink the run**, because "arrows go in USE" is a
//! memory of a different version of this game and `C:\Users\user\Desktop\ModernMapleSource`
//! has scored 1 of 8 lifetime here. It is settled off this client instead.
//!
//! `store::InventoryType::for_item` computes `itemId / 1_000_000` and its own doc block
//! marks that **[I]** for everything except the equip family: *"the family's usual convention
//! and nothing in this client has been read to confirm them"*. The client's own
//! `GetInventoryType` is `FUN_1403e8af0`, named in `crates/net/src/shop.rs`. Disassembled with
//! `tools/listing.py` (whose documented positive control on `0x140304100` was run first and
//! reproduced its three published read addresses exactly):
//!
//! ```text
//! 1403e8af6  mov  eax, 0x431bde83     ; the signed-division magic for /1000000:
//! 1403e8afb  imul ecx                 ;   ceil(2^50 / 10^6) = 1125899907, shift 18
//! 1403e8afd  mov  ebx, edx
//! 1403e8aff  sar  ebx, 0x12
//! 1403e8b09  cmp  ebx, 1              ; is it the equip family?
//! 1403e8b0c  jne  0x1403e8b63         ; NO  ->
//! 1403e8b63  mov  eax, ebx            ;        return itemId / 1000000, unmodified
//! 1403e8b6a  ret
//! ```
//!
//! **For every item id outside `1xxxxxx`, this client's own `GetInventoryType` returns
//! `itemId / 1_000_000` and nothing else.** **[L]** Arrows are `206xxxx`/`206 1xxx` and
//! throwing stars are `207xxxx`, so both return **2**, and `2` is the USE tab - which is
//! [L] separately, from the `0x0107` decode `net::inventory::CLIENT_INVENTORY_MOVE`
//! documents as `1 Equip, 2 Consume, 3 Install, 4 Etc, 5 Cash, 6 Decoration`.
//!
//! The `1xxxxxx` arm is the only one with more to it: it calls an item-template lookup and
//! returns **6** when the template's `+0x18` is non-zero, otherwise 1. That is the cash-equip
//! fork and it does not touch ammunition.
//!
//! So [`AMMUNITION_TAB`] is `Use`, and **the existing `!item` GM command already puts it
//! there** - `Session::gm_item` routes on `store::InventoryType::for_item`, which computes
//! the identical quotient. No new command is needed to get ammunition into the right tab.
//!
//! ## What is NOT established: whether a claw refuses to swing with an empty USE tab
//!
//! Stated plainly because it is the one thing here a client run could still contradict.
//! `.text` was scanned for the two byte forms of the throwing-star range test
//! (`imm32 0x001F95F0` and `disp32 -0x1F95F0`), **enumerated rather than filtered**: 14 byte
//! hits, of which **9 decode as real instructions** in `FUN_1402cf5c0` (the bundle encoder),
//! `FUN_140304450` (the bundle decoder), `FUN_1404ba100` and `FUN_141fa77a0` and
//! `FUN_141faecc0` (shop rows), `FUN_1403e1820`, `FUN_14039af80`, `FUN_140416840`,
//! `FUN_14115bf50`. The tenth, `FUN_14288e9a0`, is a byte pattern inside data and decodes as
//! no instruction at all.
//!
//! Every one of those is item bookkeeping. **None is an attack path.** But that is a negative
//! from a scan with a named blind spot, and `CLAUDE.md` is emphatic that such a negative
//! retracts nothing: **a fire-path bullet lookup would naturally walk the USE bag calling one
//! of those nine predicates rather than inline the constant**, so this enumeration cannot
//! rule one out. Hand the owner the stars regardless; they cost one `!item` line.
//!
//! # The requirement columns are missing from `equips.txt`, so they were read from the WZ
//!
//! `research/damage-formula.md` §6.4 records that `gm-handbook/equips.txt` is missing
//! columns, and **a requirement column is among them**: its header is `itemId, tuc, incSTR,
//! incDEX, incINT, incLUK, incMHP, incMMP, incSpeed, incJump, incWAT, incMAD, incPDD, incMDD,
//! incACC, incEVA, incCRT, incCRD, tradeBlock` - no `reqLevel`, no `reqSTR/DEX/INT/LUK`, no
//! `reqJob`. §6.4 names all of those explicitly as absent. **So "this item has no
//! requirement" is a claim `equips.txt` cannot support.**
//!
//! It is not left there. All **230** weapon images in `Character.wz/Weapon/Weapon_000.wz`
//! were read directly with `wz-dump` (0 unreadable) and every one carries `reqLevel`,
//! `reqSTR`, `reqDEX`, `reqINT`, `reqLUK` and `reqJob` in its `info` node. **[L]** The fields
//! vary properly - `reqLevel` takes 20 distinct values from 0 to 70 across the 230 - so this
//! is a reading, not a default. Every [`Requirements`] value below came from that scan.
//!
//! `reqJob` is a **bitmask**, not a job id: `1` Warrior, `2` Magician, `4` Bowman, `8` Thief,
//! `16` Pirate. **[D]**, and measured rather than assumed - all 13 bows and all 10 crossbows
//! are `4`, all 31 claws are `8`, all 8 staves are `2`, with no exceptions in any class; the
//! only values in the whole archive are `{0, 1, 2, 3, 4, 8, 9, 13}`, every one of them a
//! subset of those five bits; and **`16` never appears**, which independently reproduces
//! `damage-formula.md` §1.3's "this client has no pirates".
//!
//! # The branch that cannot be completed from a bare character, and it is two of them
//!
//! **There is no zero-requirement bow, crossbow or claw in this client.** The cheapest of
//! each, measured:
//!
//! | class | cheapest item | `reqLevel` | stat | `reqJob` |
//! |---|---|---:|---|---:|
//! | Bow | `1452000` War Bow | 10 | DEX 25 | 4 |
//! | Crossbow | `1462000` Crossbow | 10 | DEX 25 | 4 |
//! | Claw | `1472000` Garnier | 10 | LUK 25 | 8 |
//! | Dagger | `1332000` Razor | **5** | **none** | **0** |
//! | 1H Sword | `1302000` Sword | **0** | **none** | **0** |
//!
//! and **every one of the 11 throwing stars carries `reqLevel 10`**, where **no arrow carries
//! a requirement at all**. So the Bowman branch and the Lucky Seven half of the Thief branch
//! cannot be equipped by a level-1 character no matter which item is chosen, and substituting
//! something plausible would be inventing data this client does not have.
//!
//! **In practice this is not a blocker, and the reason is worth writing down.** A character
//! that reached a first job through this server's own advancement already satisfies both
//! gates: `crate::jobs::LEVEL_MINIMUM` is 10 and `crate::jobs::STAT_MINIMUM` is 35 in the
//! branch's own stat, and 35 > 25. **[D]** The gap is `!job`, which sets the job id directly
//! and bypasses that check - a character put into job 300 that way may hold DEX 4 and be
//! unable to equip anything it can cast with. That is what [`Requirements::met_by`] is for.

use net::opcode::Character;
use store::InventoryType;

use crate::damage::WeaponClass;

// ---------------------------------------------------------------------------------------
// Job bitmask
// ---------------------------------------------------------------------------------------

/// `reqJob` bit for a Warrior. **[D]** - see the module docs for the measurement.
pub const JOB_BIT_WARRIOR: u32 = 1;
/// `reqJob` bit for a Magician. **[D]**
pub const JOB_BIT_MAGICIAN: u32 = 2;
/// `reqJob` bit for a Bowman. **[D]**
pub const JOB_BIT_BOWMAN: u32 = 4;
/// `reqJob` bit for a Thief. **[D]**
pub const JOB_BIT_THIEF: u32 = 8;
/// `reqJob` bit for a Pirate. **Never set on any weapon in this client** - the archive's
/// values are all subsets of the four bits above, which is the same absence
/// `research/damage-formula.md` §1.3 reads out of the weapon switch. **[D]**
pub const JOB_BIT_PIRATE: u32 = 16;

/// The `reqJob` bit a job id satisfies. `0` for a beginner, which meets only `reqJob 0`.
///
/// Keyed on `job / 100` so a second-job id (`110`, `120`, `210`, …) resolves to its branch.
pub fn job_bit(job: u16) -> u32 {
    match job / 100 {
        1 => JOB_BIT_WARRIOR,
        2 => JOB_BIT_MAGICIAN,
        3 => JOB_BIT_BOWMAN,
        4 => JOB_BIT_THIEF,
        5 => JOB_BIT_PIRATE,
        _ => 0,
    }
}

// ---------------------------------------------------------------------------------------
// Requirements
// ---------------------------------------------------------------------------------------

/// What an item asks of the character before it can be worn.
///
/// **Every field is [L]**, read out of the item's own `info` node in
/// `Character.wz/Weapon/Weapon_000.wz` (weapons) or `Item.wz/Consume/0207.img` (throwing
/// stars) with `target/release/wz-dump.exe`. `gm-handbook/equips.txt` carries **none** of
/// these columns - see the module docs.
///
/// `0` means the property is zero or absent, and for a requirement those are the same thing:
/// a `reqDEX` of 0 and no `reqDEX` node both mean "asks nothing of DEX". That is deliberately
/// unlike the units trap in `crate::damage`, where `0` had to be distinguished from unset.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Requirements {
    pub level: u32,
    pub strength: u32,
    pub dexterity: u32,
    pub intelligence: u32,
    pub luck: u32,
    /// `reqJob`, a **bitmask** - see [`job_bit`]. `0` means any job.
    pub job_mask: u32,
}

impl Requirements {
    /// Asks for nothing at all.
    pub const NONE: Requirements = Requirements {
        level: 0,
        strength: 0,
        dexterity: 0,
        intelligence: 0,
        luck: 0,
        job_mask: 0,
    };

    /// Whether this item asks for nothing.
    pub fn is_free(&self) -> bool {
        *self == Requirements::NONE
    }

    /// Whether a character satisfies every clause.
    ///
    /// **This is what the client checks, not what this server checks.** The server has never
    /// validated an equip and does not start here; `research/equip-stats.md` establishes that
    /// the 125-byte equipped-item body carries **no requirement field at all** and that the
    /// client loads all six out of the WZ into `ITEMINFO` itself (`reqSTR -> +0x58` …
    /// `reqLevel -> +0x78`, and `FUN_14038c560` re-reads `reqLevel` live). **[L]**
    ///
    /// Whether the client then *refuses* an equip that fails is **not established here** and
    /// is worth one look on screen. Use this to warn, never to refuse - `CLAUDE.md`'s
    /// always-answer rule, and a GM command that silently declines is worse than one that
    /// hands over an item the client greys out.
    pub fn met_by(&self, level: u32, chr_job: u16, str_: u32, dex: u32, int: u32, luk: u32) -> bool {
        level >= self.level
            && str_ >= self.strength
            && dex >= self.dexterity
            && int >= self.intelligence
            && luk >= self.luck
            && (self.job_mask == 0 || self.job_mask & job_bit(chr_job) != 0)
    }

    /// The same check against a live character record.
    pub fn met_by_character(&self, chr: &Character) -> bool {
        self.met_by(
            chr.level,
            chr.job,
            u32::from(chr.strength),
            u32::from(chr.dexterity),
            u32::from(chr.intelligence),
            u32::from(chr.luck),
        )
    }

    /// Every clause this character fails, in plain words. Empty when [`Self::met_by`] holds.
    pub fn unmet_clauses(&self, chr: &Character) -> Vec<String> {
        let mut out = Vec::new();
        if chr.level < self.level {
            out.push(format!("level {} (has {})", self.level, chr.level));
        }
        for (want, has, label) in [
            (self.strength, u32::from(chr.strength), "STR"),
            (self.dexterity, u32::from(chr.dexterity), "DEX"),
            (self.intelligence, u32::from(chr.intelligence), "INT"),
            (self.luck, u32::from(chr.luck), "LUK"),
        ] {
            if has < want {
                out.push(format!("{label} {want} (has {has})"));
            }
        }
        if self.job_mask != 0 && self.job_mask & job_bit(chr.job) == 0 {
            out.push(format!("job mask {} (job {} is bit {})", self.job_mask, chr.job, job_bit(chr.job)));
        }
        out
    }
}

// ---------------------------------------------------------------------------------------
// The skill gates, straight out of gm-handbook/skills.txt
// ---------------------------------------------------------------------------------------

/// One skill's item gate, transcribed from `gm-handbook/skills.txt`. **[L]**
///
/// A test cross-checks every field of every row here against that file when it is present.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SkillGate {
    pub skill_id: u32,
    pub name: &'static str,
    /// The `weapon`, `weapon2`, `weapon3`, `weapon4` columns, in that order, with the empty
    /// ones dropped. **Empty means the skill has no weapon column at all**, which is
    /// nineteen of the twenty-four first-job skills.
    pub weapon_codes: &'static [u32],
    /// `bulletConsume`. `None` is an **absent column**, not zero - and the difference is the
    /// whole reason Lucky Seven is a separate case from Arrow Blow.
    pub bullet_consume: Option<u32>,
    /// `bulletCount`, i.e. **projectiles per cast**. `research/magician-first-job.md` reads
    /// it off Energy Bolt's `common` node. **[L]** This is *not* an ammunition requirement -
    /// Energy Bolt is a wand spell and carries `1`.
    pub bullet_count: Option<u32>,
}

impl SkillGate {
    /// Whether a weapon class satisfies this skill's `weapon` columns. A skill with no
    /// weapon column is castable with anything, including bare hands.
    pub fn castable_with(&self, class: Option<WeaponClass>) -> bool {
        if self.weapon_codes.is_empty() {
            return true;
        }
        class.is_some_and(|c| self.weapon_codes.contains(&c.code()))
    }
}

// ---------------------------------------------------------------------------------------
// A piece of the kit
// ---------------------------------------------------------------------------------------

/// Whether a piece is worn or fired.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PieceKind {
    /// Goes in the Equip tab and then into the weapon slot.
    Weapon(WeaponClass),
    /// Goes in the USE tab and is picked up by the client - see [`AMMUNITION_TAB`].
    Ammunition,
}

/// One item to hand over, with the evidence for its id in one place.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Piece {
    pub item_id: u32,
    /// The name **verbatim from `gm-handbook/items.txt`**, which is generated from this
    /// client's own `String.wz`. A test pins it against that file.
    pub name: &'static str,
    pub kind: PieceKind,
    /// How many to give. `1` for a weapon; for ammunition this is the item's own
    /// `info/slotMax` from `gm-handbook/itemdata.txt`, so the stack lands in **one** slot.
    pub quantity: u16,
    pub req: Requirements,
    /// The skills whose **`Skill.wz` `weapon` or `bulletConsume` column this piece
    /// satisfies**. Measured, and deliberately narrow: a piece that merely makes a skill
    /// *useful* is not listed here, only one the archive actually gates on.
    pub unlocks: &'static [u32],
    /// Why this item and not another, in one line a person reads.
    pub why: &'static str,
}

impl Piece {
    /// The weapon class, if this is a weapon.
    pub fn weapon_class(&self) -> Option<WeaponClass> {
        match self.kind {
            PieceKind::Weapon(c) => Some(c),
            PieceKind::Ammunition => None,
        }
    }

    /// The bag this piece belongs in, by the same arithmetic the client's own
    /// `GetInventoryType` uses - see the module docs.
    pub fn inventory_tab(&self) -> Option<InventoryType> {
        InventoryType::for_item(self.item_id)
    }

    /// The `!item` line that hands this piece over.
    pub fn gm_line(&self) -> String {
        format!("!item {} {}", self.item_id, self.quantity)
    }
}

/// The bag ammunition has to be in. **[L]** - `FUN_1403e8af0` returns `itemId / 1_000_000`
/// for every non-equip id, and `2` is Consume/USE. See the module docs for the listing.
pub const AMMUNITION_TAB: InventoryType = InventoryType::Use;

// ---------------------------------------------------------------------------------------
// A branch's whole kit
// ---------------------------------------------------------------------------------------

/// Everything one first-job branch needs in hand, and every skill it has.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Loadout {
    /// `100`, `200`, `300` or `400` - `crate::jobs::FIRST_JOBS` order.
    pub job: u16,
    /// The name this client's own `QuestData/10001.img` gives the job, matching
    /// `crate::jobs::FirstJob::job_name`.
    pub job_name: &'static str,
    /// What to hand over, in the order to hand it over. **Empty is a measurement**, not an
    /// omission - see [`MAGICIAN`].
    pub pieces: &'static [Piece],
    /// A second way to satisfy the same gates, when the archive offers one. The Bowman
    /// skills all carry `weapon2 = 46`, so a crossbow works everywhere a bow does.
    pub alternative: &'static [Piece],
    /// Every skill of this branch, with its measured gate. All six, always - a table that
    /// listed only the gated ones would not show that the other four are ungated.
    pub skills: &'static [SkillGate],
    /// The one thing about this branch that could still cost a run, or `None`.
    pub caveat: Option<&'static str>,
}

impl Loadout {
    /// The skills no item gates - castable the moment they are learned.
    pub fn ungated_skills(&self) -> impl Iterator<Item = &SkillGate> {
        self.skills.iter().filter(|s| s.weapon_codes.is_empty())
    }

    /// The skills that will not cast without a weapon of the right class.
    pub fn gated_skills(&self) -> impl Iterator<Item = &SkillGate> {
        self.skills.iter().filter(|s| !s.weapon_codes.is_empty())
    }

    /// Whether this branch needs no item at all to cast every one of its skills.
    pub fn needs_nothing(&self) -> bool {
        self.pieces.is_empty()
    }

    /// The `!item` lines that hand the whole kit over.
    pub fn gm_lines(&self) -> Vec<String> {
        self.pieces.iter().map(Piece::gm_line).collect()
    }

    /// Every piece this character could not equip, with the failing clauses.
    pub fn unequippable(&self, chr: &Character) -> Vec<(&Piece, Vec<String>)> {
        self.pieces
            .iter()
            .filter_map(|p| {
                let unmet = p.req.unmet_clauses(chr);
                if unmet.is_empty() { None } else { Some((p, unmet)) }
            })
            .collect()
    }
}

// ---------------------------------------------------------------------------------------
// 100 Warrior
// ---------------------------------------------------------------------------------------

/// `1302000` **Sword**, `gm-handbook/items.txt`. The only weapon class in this client with a
/// **completely free** entry: `reqLevel 0, reqSTR 0, reqDEX 0, reqINT 0, reqLUK 0, reqJob 0`,
/// `incWAT 17`, `attackSpeed 4`, read from `Weapon_000.wz/01302000.img/info`. **[L]**
const SWORD: Piece = Piece {
    item_id: 1_302_000,
    name: "Sword",
    kind: PieceKind::Weapon(WeaponClass::OneHandSword),
    quantity: 1,
    req: Requirements::NONE,
    unlocks: &[],
    why: "No Warrior skill has a weapon column, so this gates nothing. It is here because \
          the damage model multiplies the whole expression by total weapon attack - \
          crate::damage::physical_window - so a bare-handed Power Strike lands on the floor \
          of 1 and reads on screen as a broken skill. reqLevel 0 and no stat requirement is \
          the strongest 'he can definitely wear this' in the archive.",
};

/// The Warrior branch, job 100.
pub const WARRIOR: Loadout = Loadout {
    job: 100,
    job_name: "Swordsman",
    pieces: &[SWORD],
    alternative: &[],
    skills: &[
        SkillGate { skill_id: 1_000_000, name: "Improved HP Recovery", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 1_000_001, name: "Max HP Increase", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 1_000_002, name: "Precise Strikes", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 1_001_000, name: "Iron Body", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 1_001_001, name: "Power Strike", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 1_001_002, name: "Slash Blast", weapon_codes: &[], bullet_consume: None, bullet_count: None },
    ],
    caveat: Some(
        "Nothing gates a Warrior skill. If Power Strike will not fire, the cause is not the \
         weapon and looking for one will cost the run.",
    ),
};

// ---------------------------------------------------------------------------------------
// 200 Magician
// ---------------------------------------------------------------------------------------

/// The Magician branch, job 200. **`pieces` is empty and that is measured.**
///
/// All six Magician skills were checked column by column in `gm-handbook/skills.txt` and
/// **not one carries `weapon`, `weapon2`, `weapon3`, `weapon4`, `bulletConsume` or
/// `noBulletConsume`**. **[L]** The single non-empty cell anywhere in that group is Energy
/// Bolt's `bulletCount = 1`, which is projectiles per cast, not ammunition - see the module
/// docs.
///
/// So this row exists to say *"this branch needs no weapon, and that is measured"* rather
/// than to leave a hole someone fills in later with a wand.
/// # CORRECTED 2026-08-28: the wand is in the kit
///
/// This row used to carry `pieces: &[]` and a caveat reading *"the weapon-attack argument that
/// puts a Sword in the Warrior kit does not apply"*. **It does apply, through a different
/// field.** The owner asked for a Magician kit and got told they needed nothing:
/// *"The !kit command is not useful right now since I don't get a wand on my character."*
///
/// `crate::magic`'s own header has it: `MagicTotal` is `floor(INT / 2)` **plus equipment
/// `incMAD`**. The Wooden Wand's `incMAD` is **27** - the row read `incWAT 18` and stopped
/// there, which is the wrong column for the magic path. A wandless Magician runs the whole
/// formula on `floor(INT / 2)` alone, and that is precisely the arithmetic that made Magic
/// Claw draw a 1 on 2026-08-27.
///
/// The distinction the old row missed is the same one the Warrior row missed in the other
/// direction: **"carries no weapon column" is about whether the client REFUSES the cast, not
/// about whether the damage is any good.** No Magician skill is gated. Every Magician skill
/// is scaled.
pub const MAGICIAN: Loadout = Loadout {
    job: 200,
    job_name: "Magician",
    pieces: &[WOODEN_WAND],
    alternative: &[WOODEN_STAFF],
    skills: &[
        SkillGate { skill_id: 2_000_000, name: "Improved MP Recovery", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 2_000_001, name: "Max MP Increase", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 2_001_000, name: "Magic Guard", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 2_001_001, name: "Magic Armor", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 2_001_002, name: "Energy Bolt", weapon_codes: &[], bullet_consume: None, bullet_count: Some(1) },
        SkillGate { skill_id: 2_001_003, name: "Magic Claw", weapon_codes: &[], bullet_consume: None, bullet_count: None },
    ],
    caveat: Some(
        "NO Magician skill is gated on a weapon, so all six cast bare-handed - but every \
         attack among them SCALES on the wand. MagicTotal is floor(INT/2) plus equipment \
         incMAD, and the Wooden Wand's incMAD is 27. Without it the whole formula runs on \
         floor(INT/2) alone, which is how Magic Claw drew a 1. The wand is not free: \
         reqLevel 10 and INT 20, so raise INT before expecting to equip it.",
    ),
};

/// `1372000` **Wooden Wand**, `gm-handbook/items.txt`. `reqLevel 10, reqINT 20, reqJob 0`,
/// **`incMAD 27`**, `incWAT 18`, `attackSpeed 6`. **[L]**
///
/// The cheapest wand in this client. Every wand and staff was enumerated to establish that
/// and that **there is no free one**: the ladder starts at level 10 / INT 20 and the next rung
/// is level 15 / INT 30. `reqLevel 10` is met by anyone who has a first job at all, so INT is
/// the only real gate.
///
/// **`incMAD`, not `incWAT`, is the column that matters here.** `crate::magic` reads
/// `MagicTotal`; `crate::damage`'s weapon multiplier never enters the magic path.
const WOODEN_WAND: Piece = Piece {
    item_id: 1_372_000,
    name: "Wooden Wand",
    kind: PieceKind::Weapon(WeaponClass::Wand),
    quantity: 1,
    req: Requirements { level: 10, intelligence: 20, ..Requirements::NONE },
    // **Empty, and that is the field's meaning rather than an oversight.** `unlocks` is
    // "skills whose `weapon` column this class satisfies", and no Magician skill has one.
    // The wand's contribution is `incMAD`, which is scaling, not gating. A test asserts that
    // every `unlocks` entry really is gated, and it caught this being filled in.
    unlocks: &[],
    why: "Gates nothing, scales everything: incMAD 27 against a bare-handed MagicTotal of \
          floor(INT/2). This is the Magician's equivalent of the Warrior's sword.",
};

/// `1382000` **Wooden Staff**, `gm-handbook/items.txt`. `reqLevel 10, reqINT 20, reqJob 2`,
/// `incMAD 24`, `incWAT 20`. **[L]**
///
/// The alternative, and it is strictly worse for magic - 24 `incMAD` against the wand's 27 -
/// **and** it carries `reqJob 2`, so unlike the wand it cannot be worn by a character who has
/// not actually advanced. Listed because a staff is what a player expects to reach for.
const WOODEN_STAFF: Piece = Piece {
    item_id: 1_382_000,
    name: "Wooden Staff",
    kind: PieceKind::Weapon(WeaponClass::Staff),
    quantity: 1,
    req: Requirements {
        level: 10,
        intelligence: 20,
        job_mask: JOB_BIT_MAGICIAN,
        ..Requirements::NONE
    },
    unlocks: &[],
    why: "Lower incMAD than the wand (24 vs 27) and adds a reqJob bit. Kept as the second \
          option because a staff is the obvious thing to reach for.",
};

// ---------------------------------------------------------------------------------------
// 300 Bowman
// ---------------------------------------------------------------------------------------

/// `1452000` **War Bow**, `gm-handbook/items.txt`. `reqLevel 10, reqDEX 25, reqJob 4`,
/// `incWAT 30`, `attackSpeed 6`. **[L]**
///
/// **The cheapest bow in this client, and there is no free one** - all 13 bows carry
/// `reqJob 4` and the lowest `reqLevel` among them is 10.
const WAR_BOW: Piece = Piece {
    item_id: 1_452_000,
    name: "War Bow",
    kind: PieceKind::Weapon(WeaponClass::Bow),
    quantity: 1,
    req: Requirements { level: 10, dexterity: 25, job_mask: JOB_BIT_BOWMAN, ..Requirements::NONE },
    unlocks: &[3_001_001, 3_001_002, 3_001_003],
    why: "weapon=45 on all three Bowman attack skills. The cheapest of the 13 bows; every \
          one of them is reqJob 4 and none is below reqLevel 10.",
};

/// `2060000` **Arrows for Bows**, `gm-handbook/items.txt`. **No requirement node of any
/// kind** - its whole `info` is `price 0, slotMax 1000`. **[L]** `slotMax 1000` is also in
/// `gm-handbook/itemdata.txt`, so 1000 lands in one slot.
const ARROWS_FOR_BOWS: Piece = Piece {
    item_id: 2_060_000,
    name: "Arrows for Bows",
    kind: PieceKind::Ammunition,
    quantity: 1000,
    req: Requirements::NONE,
    unlocks: &[3_001_001, 3_001_002],
    why: "bulletConsume 1 on Arrow Blow and 2 on Double Shot. The only free ammunition in \
          the client - no arrow carries a requirement, where every throwing star carries \
          reqLevel 10. Goes in the USE tab; !item already routes it there.",
};

/// `1462000` **Crossbow** and `2061000` **Arrows for Crossbows** - the `weapon2 = 46` route.
const CROSSBOW: Piece = Piece {
    item_id: 1_462_000,
    name: "Crossbow",
    kind: PieceKind::Weapon(WeaponClass::Crossbow),
    quantity: 1,
    req: Requirements { level: 10, dexterity: 25, job_mask: JOB_BIT_BOWMAN, ..Requirements::NONE },
    unlocks: &[3_001_001, 3_001_002, 3_001_003],
    why: "weapon2=46 on all three Bowman attack skills, so a crossbow satisfies every gate a \
          bow does. Same requirements as the War Bow. Needs 2061000, NOT 2060000.",
};

/// See [`CROSSBOW`]. `info` is `price 0, slotMax 1000` and nothing else. **[L]**
const ARROWS_FOR_CROSSBOWS: Piece = Piece {
    item_id: 2_061_000,
    name: "Arrows for Crossbows",
    kind: PieceKind::Ammunition,
    quantity: 1000,
    req: Requirements::NONE,
    unlocks: &[3_001_001, 3_001_002],
    why: "A crossbow does not fire 2060000. Free, exactly as the bow arrows are.",
};

/// The Bowman branch, job 300.
pub const BOWMAN: Loadout = Loadout {
    job: 300,
    job_name: "Archer",
    pieces: &[WAR_BOW, ARROWS_FOR_BOWS],
    alternative: &[CROSSBOW, ARROWS_FOR_CROSSBOWS],
    skills: &[
        SkillGate { skill_id: 3_000_000, name: "Critical Shot", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 3_000_001, name: "The Eye of Amazon", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 3_001_000, name: "Focus", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 3_001_001, name: "Arrow Blow", weapon_codes: &[45, 46], bullet_consume: Some(1), bullet_count: Some(1) },
        SkillGate { skill_id: 3_001_002, name: "Double Shot", weapon_codes: &[45, 46], bullet_consume: Some(2), bullet_count: Some(2) },
        SkillGate { skill_id: 3_001_003, name: "Power Knockback", weapon_codes: &[45, 46], bullet_consume: None, bullet_count: None },
    ],
    caveat: Some(
        "Nothing in this client lets a level-1 character hold a bow: the cheapest is \
         reqLevel 10, DEX 25, reqJob 4. A Bowman advanced through jobs::advancement_for \
         clears both (LEVEL_MINIMUM 10, STAT_MINIMUM 35); one dropped into job 300 with \
         !job may not. Check with Loadout::unequippable before the run.",
    ),
};

// ---------------------------------------------------------------------------------------
// 400 Thief - the branch that needs TWO weapons
// ---------------------------------------------------------------------------------------

/// `1332000` **Razor**, `gm-handbook/items.txt`. `reqLevel 5`, **no stat requirement**,
/// `reqJob 0`, `incWAT 23`, `attackSpeed 4`. **[L]**
///
/// The cheapest dagger and the only weapon outside the sword family that asks for no stat at
/// all. It has also **already been seen working in this client**: a previous run archived in
/// `previous-runs/` shows `0x046E DropEnterField ... item 1332000 x1` followed by
/// `InventoryOperation ADD: item 1332000 into Equip slot 13`.
const RAZOR: Piece = Piece {
    item_id: 1_332_000,
    name: "Razor",
    kind: PieceKind::Weapon(WeaponClass::Dagger),
    quantity: 1,
    req: Requirements { level: 5, ..Requirements::NONE },
    unlocks: &[4_001_002],
    why: "weapon=33 on Double Stab, and 33 is Dagger. reqLevel 5 with no stat and no job \
          clause is the least demanding weapon that satisfies any first-job gate.",
};

/// `1472000` **Garnier**, `gm-handbook/items.txt`. `reqLevel 10, reqLUK 25, reqJob 8`,
/// `incWAT 10`, `attackSpeed 5`. **[L]** The cheapest of the 31 claws; every one of them is
/// `reqJob 8` and none is below `reqLevel 10`.
const GARNIER: Piece = Piece {
    item_id: 1_472_000,
    name: "Garnier",
    kind: PieceKind::Weapon(WeaponClass::Claw),
    quantity: 1,
    req: Requirements { level: 10, luck: 25, job_mask: JOB_BIT_THIEF, ..Requirements::NONE },
    unlocks: &[4_001_003],
    why: "weapon=47 on Lucky Seven, and 47 is Claw. A DIFFERENT weapon from the Razor - the \
          Thief is the only branch whose two attack skills name two different classes, so \
          this kit is two weapons and one swap mid-test.",
};

/// `2070000` **Subi Throwing Stars**, `gm-handbook/items.txt`. `reqLevel 10`, `incWAT 15`,
/// `slotMax 500`, `price 250`. **[L]** from `Item.wz/Consume/0207.img/02070000/info`.
///
/// **Every one of the 11 throwing stars in this client carries `reqLevel 10`**, so there is
/// no free one; this is the cheapest.
const SUBI_THROWING_STARS: Piece = Piece {
    item_id: 2_070_000,
    name: "Subi Throwing Stars",
    kind: PieceKind::Ammunition,
    quantity: 500,
    req: Requirements { level: 10, ..Requirements::NONE },
    unlocks: &[],
    why: "unlocks is EMPTY and that is measured, not an oversight: Lucky Seven carries \
          bulletCount 2 but NO bulletConsume, where Arrow Blow and Double Shot both carry \
          one. So Skill.wz does not gate Lucky Seven on ammunition. Included anyway because \
          a claw is a ranged class (WeaponClass::is_ranged) and whether the client refuses \
          to fire one with an empty USE tab is NOT established here - see the module docs. \
          One !item line is cheaper than finding out mid-run.",
};

/// The Thief branch, job 400. **Two weapons**, which no other branch needs.
pub const THIEF: Loadout = Loadout {
    job: 400,
    job_name: "Rogue",
    pieces: &[RAZOR, GARNIER, SUBI_THROWING_STARS],
    alternative: &[],
    skills: &[
        SkillGate { skill_id: 4_000_000, name: "Nimble Body", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 4_000_001, name: "Keen Eyes", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 4_001_000, name: "Disorder", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 4_001_001, name: "Dark Sight", weapon_codes: &[], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 4_001_002, name: "Double Stab", weapon_codes: &[33], bullet_consume: None, bullet_count: None },
        SkillGate { skill_id: 4_001_003, name: "Lucky Seven", weapon_codes: &[47], bullet_consume: None, bullet_count: Some(2) },
    ],
    caveat: Some(
        "The only branch needing two weapons: Double Stab is weapon 33 (Dagger) and Lucky \
         Seven is weapon 47 (Claw), and no single item is both. Test them as two steps with \
         a swap between, or a failed Lucky Seven will read as a broken skill when it is a \
         Razor still in the slot.",
    ),
};

// ---------------------------------------------------------------------------------------
// The table
// ---------------------------------------------------------------------------------------

/// The four branches, in `crate::jobs::FIRST_JOBS` order.
pub const LOADOUTS: [Loadout; 4] = [WARRIOR, MAGICIAN, BOWMAN, THIEF];

/// The kit for a first job. `None` for anything that is not `100`, `200`, `300` or `400`.
///
/// **Exact, not by branch.** A second-job id resolves to nothing rather than silently
/// answering with the first job's kit, because a second-job character's skills are not in
/// this table and pretending otherwise would be the kind of plausible-looking wrong answer
/// `CLAUDE.md` is about.
pub fn loadout_for(job: u16) -> Option<&'static Loadout> {
    LOADOUTS.iter().find(|l| l.job == job)
}

/// Every gate in the table, across all four branches.
pub fn all_skill_gates() -> impl Iterator<Item = &'static SkillGate> {
    LOADOUTS.iter().flat_map(|l| l.skills.iter())
}

/// The gate for one skill id.
pub fn gate_for_skill(skill_id: u32) -> Option<&'static SkillGate> {
    all_skill_gates().find(|s| s.skill_id == skill_id)
}

/// A weapon class in plain English, for a line a person reads.
///
/// The **names** are `research/damage-formula.md` §1.4's column, which is `[D]`: they were
/// derived by matching the 1H-axe arm (`2 -> 2.4`, `3 -> 1.2`) and the bow arm (`4 -> 2.5`)
/// against the meowdb table, which agrees for all eight families. The **codes** are `[L]`.
///
/// This is the one thing this module adds to [`WeaponClass`]; the mapping from code to class
/// is that enum's job and is not repeated here.
pub fn weapon_name(class: WeaponClass) -> &'static str {
    match class {
        WeaponClass::OneHandSword => "one-handed sword",
        WeaponClass::OneHandAxe => "one-handed axe",
        WeaponClass::OneHandBlunt => "one-handed blunt weapon",
        WeaponClass::Dagger => "dagger",
        WeaponClass::Wand => "wand",
        WeaponClass::Staff => "staff",
        WeaponClass::BareHands => "bare hands",
        WeaponClass::TwoHandSword => "two-handed sword",
        WeaponClass::TwoHandAxe => "two-handed axe",
        WeaponClass::TwoHandBlunt => "two-handed blunt weapon",
        WeaponClass::Spear => "spear",
        WeaponClass::Polearm => "polearm",
        WeaponClass::Bow => "bow",
        WeaponClass::Crossbow => "crossbow",
        WeaponClass::Claw => "claw",
    }
}

/// The plain-English name for a raw `Skill.wz` `weapon` code, or `None` when the code has no
/// arm in the client's weapon switch (`34`, `35`, `36`) or is outside `30..=47` entirely.
pub fn weapon_name_for_code(code: u32) -> Option<&'static str> {
    WeaponClass::from_code(code).map(weapon_name)
}

// ---------------------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -- the table's own shape -----------------------------------------------------------

    #[test]
    fn the_four_branches_are_the_four_first_jobs_in_jobs_rs_order() {
        let ids: Vec<u16> = LOADOUTS.iter().map(|l| l.job).collect();
        assert_eq!(ids, vec![100, 200, 300, 400]);
        for (l, j) in LOADOUTS.iter().zip(crate::jobs::FIRST_JOBS.iter()) {
            assert_eq!(l.job, j.job);
            assert_eq!(l.job_name, j.job_name, "job {} name must match jobs::FIRST_JOBS", l.job);
        }
        // Exact match only: a second-job or beginner id resolves to nothing rather than
        // quietly answering with its branch's first-job kit.
        for job in [0u16, 1, 110, 201, 310, 422, 500, 900] {
            assert!(loadout_for(job).is_none(), "job {job} must not resolve to a kit");
        }
        for job in [100u16, 200, 300, 400] {
            assert_eq!(loadout_for(job).map(|l| l.job), Some(job));
        }
        assert_eq!(loadout_for(300).map(|l| l.job_name), Some("Archer"));
    }

    /// 24 skills, six per branch, and each one belongs to the branch it is filed under.
    #[test]
    fn every_branch_lists_all_six_of_its_own_skills() {
        assert_eq!(all_skill_gates().count(), 24);
        for l in LOADOUTS.iter() {
            assert_eq!(l.skills.len(), 6, "job {}", l.job);
            for s in l.skills {
                assert_eq!(
                    s.skill_id / 10_000,
                    u32::from(l.job),
                    "{} ({}) is filed under job {}",
                    s.name,
                    s.skill_id,
                    l.job
                );
            }
        }
        let mut ids: Vec<u32> = all_skill_gates().map(|s| s.skill_id).collect();
        ids.sort_unstable();
        ids.dedup();
        assert_eq!(ids.len(), 24, "no duplicate skill ids");
    }

    /// Exactly five of the twenty-four are gated, and they are the five the module docs name.
    #[test]
    fn exactly_five_skills_carry_a_weapon_column() {
        let gated: Vec<u32> =
            all_skill_gates().filter(|s| !s.weapon_codes.is_empty()).map(|s| s.skill_id).collect();
        assert_eq!(gated, vec![3_001_001, 3_001_002, 3_001_003, 4_001_002, 4_001_003]);
        // and the other nineteen are castable with nothing in hand at all
        for s in all_skill_gates().filter(|s| s.weapon_codes.is_empty()) {
            assert!(s.castable_with(None), "{} should need no weapon", s.name);
            assert!(s.castable_with(Some(WeaponClass::BareHands)), "{}", s.name);
        }
    }

    /// The distinction the whole Lucky Seven hedge rests on: `bulletConsume` is present on
    /// two skills and absent on Lucky Seven, and `bulletCount` is a different column that
    /// appears on a wand spell.
    #[test]
    fn bullet_consume_and_bullet_count_are_different_columns() {
        let consumers: Vec<u32> = all_skill_gates()
            .filter(|s| s.bullet_consume.is_some())
            .map(|s| s.skill_id)
            .collect();
        assert_eq!(consumers, vec![3_001_001, 3_001_002], "only Arrow Blow and Double Shot");

        let l7 = gate_for_skill(4_001_003).unwrap();
        assert_eq!(l7.bullet_count, Some(2));
        assert_eq!(l7.bullet_consume, None, "Lucky Seven has NO bulletConsume in this client");

        // Energy Bolt is the control that proves bulletCount is not ammunition: a wand spell
        // with no weapon column, no bulletConsume, and a bulletCount all the same.
        let eb = gate_for_skill(2_001_002).unwrap();
        assert_eq!(eb.bullet_count, Some(1));
        assert_eq!(eb.bullet_consume, None);
        assert!(eb.weapon_codes.is_empty());
    }

    // -- the pieces ----------------------------------------------------------------------

    /// A weapon's declared class has to be the one its own item id implies, by the client's
    /// `itemId / 10000 - 100`. This is the check that catches a transcription slip in an id.
    #[test]
    fn every_weapon_piece_id_implies_the_class_it_claims() {
        for l in LOADOUTS.iter() {
            for p in l.pieces.iter().chain(l.alternative.iter()) {
                match p.kind {
                    PieceKind::Weapon(c) => {
                        assert_eq!(
                            WeaponClass::from_item_id(p.item_id),
                            Some(c),
                            "{} ({}) claims {:?}",
                            p.name,
                            p.item_id,
                            c
                        );
                        assert_eq!(p.quantity, 1, "{} is a weapon", p.name);
                        assert_eq!(p.inventory_tab(), Some(InventoryType::Equip), "{}", p.name);
                    }
                    PieceKind::Ammunition => {
                        assert_eq!(WeaponClass::from_item_id(p.item_id), None, "{}", p.name);
                        assert!(p.quantity > 1, "{} is a stack", p.name);
                    }
                }
            }
        }
    }

    /// The answer to "which tab does ammunition go in", pinned against the arithmetic the
    /// client's own `GetInventoryType` uses.
    #[test]
    fn all_ammunition_lands_in_the_use_tab() {
        let ammo: Vec<&Piece> = LOADOUTS
            .iter()
            .flat_map(|l| l.pieces.iter().chain(l.alternative.iter()))
            .filter(|p| p.kind == PieceKind::Ammunition)
            .collect();
        assert_eq!(ammo.len(), 3, "bow arrows, crossbow arrows, throwing stars");
        for p in ammo {
            assert_eq!(p.inventory_tab(), Some(AMMUNITION_TAB), "{}", p.name);
            assert_eq!(p.item_id / 1_000_000, 2, "FUN_1403e8af0 returns itemId / 1000000");
        }
        assert_eq!(AMMUNITION_TAB, InventoryType::Use);
        assert_eq!(AMMUNITION_TAB.as_u8(), 2);
    }

    /// Throwing stars are eight bytes longer on the wire than an ordinary stack. If a `!kit`
    /// ever builds its own item body instead of going through `net::bag`, this is the field
    /// that kills the client - so pin which of the three needs it.
    #[test]
    fn throwing_stars_carry_the_serial_and_arrows_do_not() {
        assert!(net::bag::bundle_has_serial(SUBI_THROWING_STARS.item_id));
        assert_eq!(net::bag::bundle_item_len(SUBI_THROWING_STARS.item_id), 49);
        for arrows in [ARROWS_FOR_BOWS, ARROWS_FOR_CROSSBOWS] {
            assert!(!net::bag::bundle_has_serial(arrows.item_id), "{}", arrows.name);
            assert_eq!(net::bag::bundle_item_len(arrows.item_id), 41, "{}", arrows.name);
        }
    }

    /// A piece may only claim to unlock a skill whose own `weapon` column it satisfies.
    #[test]
    fn a_piece_only_unlocks_skills_its_class_actually_satisfies() {
        for l in LOADOUTS.iter() {
            for p in l.pieces.iter().chain(l.alternative.iter()) {
                for &sid in p.unlocks {
                    let g = gate_for_skill(sid).unwrap_or_else(|| panic!("skill {sid} unknown"));
                    match p.kind {
                        PieceKind::Weapon(c) => assert!(
                            g.weapon_codes.contains(&c.code()),
                            "{} ({:?}) claims {} but its weapon codes are {:?}",
                            p.name,
                            c,
                            g.name,
                            g.weapon_codes
                        ),
                        PieceKind::Ammunition => assert!(
                            g.bullet_consume.is_some(),
                            "{} claims {}, which has no bulletConsume",
                            p.name,
                            g.name
                        ),
                    }
                }
            }
        }
    }

    /// Every gated skill has a piece in its own branch that satisfies it - i.e. the table is
    /// complete, not merely self-consistent.
    #[test]
    fn every_gated_skill_has_a_piece_in_its_branch() {
        for l in LOADOUTS.iter() {
            for g in l.gated_skills() {
                let classes: Vec<WeaponClass> =
                    l.pieces.iter().filter_map(Piece::weapon_class).collect();
                assert!(
                    classes.iter().any(|c| g.castable_with(Some(*c))),
                    "job {}: nothing in the kit satisfies {} (needs {:?}, kit has {:?})",
                    l.job,
                    g.name,
                    g.weapon_codes,
                    classes
                );
            }
        }
    }

    /// The Magician row is an explicit measurement, so assert it as one.
    #[test]
    fn the_magician_gates_nothing_but_still_needs_the_wand() {
        // **This test used to assert `needs_nothing()`, and that assertion was the bug.**
        // The owner, 2026-08-28: *"The !kit command is not useful right now since I don't get a
        // wand on my character."* Nothing is GATED - all six cast bare-handed - but
        // `crate::magic` reads `MagicTotal = floor(INT/2) + equipment incMAD`, and the wand's
        // incMAD is 27. "No weapon column" and "no weapon needed" are different claims, and
        // the row had collapsed them into one.
        assert!(!MAGICIAN.needs_nothing(), "the Magician needs a wand to do any damage");
        assert_eq!(MAGICIAN.gated_skills().count(), 0, "and yet nothing is gated");
        assert_eq!(MAGICIAN.ungated_skills().count(), 6);
        assert_eq!(MAGICIAN.pieces.len(), 1, "one wand, no ammunition");
        assert_eq!(MAGICIAN.pieces[0].item_id, WOODEN_WAND.item_id);
        // Not free, so `!kit` warns a low-INT character - which is the whole point of the
        // warning, since !job does not move ability points.
        assert!(!WOODEN_WAND.req.is_free());
        assert_eq!(WOODEN_WAND.req.intelligence, 20);
        // The staff is strictly worse for magic, so it must not have become the default.
        assert_eq!(MAGICIAN.alternative[0].item_id, WOODEN_STAFF.item_id);
    }

    /// The Thief is the only branch needing two different weapon classes.
    #[test]
    fn only_the_thief_needs_two_weapon_classes() {
        for l in LOADOUTS.iter() {
            let mut classes: Vec<WeaponClass> =
                l.pieces.iter().filter_map(Piece::weapon_class).collect();
            classes.sort();
            classes.dedup();
            // One weapon class per branch - the Magician included, since the wand joined the
            // kit - except the Thief, which needs a dagger AND a claw because no item in this
            // client is both.
            let want = if l.job == 400 { 2 } else { 1 };
            assert_eq!(classes.len(), want, "job {} weapon classes {:?}", l.job, classes);
        }
        assert_eq!(THIEF.pieces.len(), 3, "dagger, claw, stars");
    }

    // -- requirements --------------------------------------------------------------------

    #[test]
    fn the_free_items_are_the_two_this_client_actually_has() {
        assert!(SWORD.req.is_free(), "1302000 is the only completely free weapon");
        assert!(ARROWS_FOR_BOWS.req.is_free());
        assert!(ARROWS_FOR_CROSSBOWS.req.is_free());
        // and the ones that are not, are not
        for p in [WAR_BOW, CROSSBOW, GARNIER, SUBI_THROWING_STARS, RAZOR, WOODEN_WAND] {
            assert!(!p.req.is_free(), "{} asks for something", p.name);
        }
        assert_eq!(RAZOR.req, Requirements { level: 5, ..Requirements::NONE });
    }

    #[test]
    fn the_job_mask_is_a_bitmask_over_branches() {
        assert_eq!(job_bit(100), JOB_BIT_WARRIOR);
        assert_eq!(job_bit(200), JOB_BIT_MAGICIAN);
        assert_eq!(job_bit(300), JOB_BIT_BOWMAN);
        assert_eq!(job_bit(400), JOB_BIT_THIEF);
        assert_eq!(job_bit(0), 0, "a beginner satisfies only reqJob 0");
        // second-job ids resolve to their branch
        assert_eq!(job_bit(310), JOB_BIT_BOWMAN);
        assert_eq!(job_bit(422), JOB_BIT_THIEF);
        // reqJob 9 in the archive is Warrior|Thief, and both satisfy it
        let both = JOB_BIT_WARRIOR | JOB_BIT_THIEF;
        assert_eq!(both, 9);
        let r = Requirements { job_mask: both, ..Requirements::NONE };
        assert!(r.met_by(1, 100, 0, 0, 0, 0));
        assert!(r.met_by(1, 400, 0, 0, 0, 0));
        assert!(!r.met_by(1, 300, 0, 0, 0, 0), "a Bowman does not satisfy Warrior|Thief");
    }

    /// The case that actually costs a run: `!job 300` on a fresh character.
    #[test]
    fn a_bare_character_dropped_into_job_300_cannot_hold_the_bow() {
        let mut chr = Character { job: 300, level: 10, ..Character::default() };
        chr.dexterity = 4;
        let unmet = BOWMAN.unequippable(&chr);
        assert_eq!(unmet.len(), 1, "only the bow fails; the arrows are free");
        assert_eq!(unmet[0].0.item_id, WAR_BOW.item_id);
        assert!(unmet[0].1.iter().any(|c| c.starts_with("DEX 25")), "{:?}", unmet[0].1);

        // A Bowman that came through jobs::advancement_for has STAT_MINIMUM in DEX, and 35
        // clears the bow's 25. This is the [D] in the module docs, asserted rather than said.
        chr.dexterity = crate::jobs::STAT_MINIMUM;
        chr.level = crate::jobs::LEVEL_MINIMUM;
        assert!(BOWMAN.unequippable(&chr).is_empty(), "an advanced Bowman clears its own kit");

        // Compile-time, because this is an invariant between two tables rather than a fact
        // about this test's character. If `jobs::STAT_MINIMUM` is ever lowered below a
        // branch weapon's own requirement, every kit in this module silently stops being
        // equippable by a freshly advanced character - and `jobs.rs` records that the owner has
        // already asked for 25 once, which is exactly the bow's `reqDEX`.
        const { assert!(crate::jobs::STAT_MINIMUM as u32 >= WAR_BOW.req.dexterity) };
        const { assert!(crate::jobs::LEVEL_MINIMUM >= WAR_BOW.req.level) };
    }

    /// The same for the Thief, whose claw and stars both want level 10.
    #[test]
    fn an_advanced_thief_clears_its_own_kit_including_the_stars() {
        let chr = Character {
            job: 400,
            level: crate::jobs::LEVEL_MINIMUM,
            luck: crate::jobs::STAT_MINIMUM,
            ..Character::default()
        };
        assert!(THIEF.unequippable(&chr).is_empty(), "{:?}", THIEF.unequippable(&chr));
        const { assert!(crate::jobs::STAT_MINIMUM as u32 >= GARNIER.req.luck) };
        const { assert!(crate::jobs::LEVEL_MINIMUM >= SUBI_THROWING_STARS.req.level) };
        assert_eq!(SUBI_THROWING_STARS.req.level, 10, "every star in this client wants level 10");
    }

    // -- weapon names --------------------------------------------------------------------

    #[test]
    fn every_weapon_code_in_the_skill_archive_has_a_name() {
        // The distinct `weapon` values anywhere in gm-handbook/skills.txt.
        for code in [30u32, 31, 32, 33, 43, 44, 45, 46, 47] {
            assert!(weapon_name_for_code(code).is_some(), "code {code} must name a class");
        }
        // The three inside 30..=47 with no arm in the client's switch, and two outside it.
        for code in [34u32, 35, 36, 29, 48, 49] {
            assert_eq!(weapon_name_for_code(code), None, "code {code} has no class");
        }
        assert_eq!(weapon_name_for_code(45), Some("bow"));
        assert_eq!(weapon_name_for_code(33), Some("dagger"));
        assert_eq!(weapon_name_for_code(47), Some("claw"));
        for c in WeaponClass::ALL {
            assert!(!weapon_name(c).is_empty());
        }
    }

    #[test]
    fn the_gm_line_is_the_command_a_person_pastes() {
        assert_eq!(SWORD.gm_line(), "!item 1302000 1");
        assert_eq!(ARROWS_FOR_BOWS.gm_line(), "!item 2060000 1000");
        assert_eq!(
            THIEF.gm_lines(),
            vec!["!item 1332000 1", "!item 1472000 1", "!item 2070000 500"]
        );
    }

    // -- cross-checks against the generated files ----------------------------------------
    //
    // `gm-handbook/` is generated and gitignored, so these skip when it is absent - the same
    // convention `net::quest`'s requirement-table test uses. Each one proves its parse can
    // find a positive control before asserting anything, because a silent negative here
    // would be a property of the parse rather than evidence.

    fn handbook(name: &str) -> Option<String> {
        std::fs::read_to_string(std::path::Path::new("../../gm-handbook").join(name)).ok()
    }

    /// One skill's gate columns as the generated file spells them.
    type SkillRow = (String, Vec<u32>, Option<u32>, Option<u32>);

    /// Parse `skills.txt` into `skillId -> {every distinct (name, weapon..weapon4,
    /// bulletConsume, bulletCount) across that skill's levels}`, reading the column positions
    /// off the header rather than hard-coding them.
    ///
    /// **A set, not a single row, and that is a correction this test made itself.** The first
    /// version asserted these columns were level-invariant for every skill in the file and
    /// **it failed**: `3111002` Arrow Rain is `bulletConsume 7, bulletCount 7` at some levels
    /// and `8, 8` at others. That is a second-job skill, so it does not touch this table - but
    /// it means "these columns do not vary with level" is **false file-wide** and is only true
    /// for the 24 first-job skills. [`every_skill_gate_matches_the_generated_skill_archive`]
    /// asserts the invariance where this module actually relies on it and nowhere else.
    #[allow(clippy::type_complexity)]
    fn parse_skills(text: &str) -> std::collections::HashMap<u32, Vec<SkillRow>> {
        let header: Vec<&str> = text
            .lines()
            .find(|l| l.starts_with('#') && l.contains("skillId"))
            .expect("skills.txt has no header line")
            .trim_start_matches('#')
            .split(',')
            .map(str::trim)
            .collect();
        let col = |n: &str| header.iter().position(|h| *h == n).unwrap_or_else(|| panic!("no column {n}"));
        let (c_id, c_name) = (col("skillId"), col("name"));
        let (c_w, c_w2, c_w3, c_w4) = (col("weapon"), col("weapon2"), col("weapon3"), col("weapon4"));
        let (c_bc, c_bn) = (col("bulletConsume"), col("bulletCount"));

        let mut out = std::collections::HashMap::new();
        for line in text.lines().filter(|l| !l.starts_with('#') && !l.trim().is_empty()) {
            let f: Vec<&str> = line.split(',').map(str::trim).collect();
            assert_eq!(f.len(), header.len(), "row width differs from the header: {line}");
            let Ok(id) = f[c_id].parse::<u32>() else { continue };
            let weapons: Vec<u32> =
                [c_w, c_w2, c_w3, c_w4].iter().filter_map(|&c| f[c].parse::<u32>().ok()).collect();
            let row = (
                f[c_name].to_string(),
                weapons,
                f[c_bc].parse::<u32>().ok(),
                f[c_bn].parse::<u32>().ok(),
            );
            let seen: &mut Vec<SkillRow> = out.entry(id).or_default();
            if !seen.contains(&row) {
                seen.push(row);
            }
        }
        out
    }

    /// **The check this whole module rests on.** Every gate above, against the generated
    /// file, column by column.
    #[test]
    fn every_skill_gate_matches_the_generated_skill_archive() {
        let Some(text) = handbook("skills.txt") else { return };
        let table = parse_skills(&text);

        // Positive controls first: a parse that found nothing would pass every assertion
        // below by vacuity, and a wrong column index would too.
        // 176 distinct skills over 4164 rows - counted, not guessed. The first version of
        // this line asserted "> 300" from memory and failed against the real file, which is
        // the same class of mistake as every other unverified constant in this repo.
        assert!(
            table.len() >= 150,
            "skills.txt parsed to {} skills; this client has 176",
            table.len()
        );
        let three_snails = table.get(&1000).expect("skill 1000 Three Snails");
        assert_eq!(three_snails[0].0, "Three Snails");
        let bow_mastery = table.get(&3_100_000).expect("skill 3100000 Bow Mastery");
        assert_eq!(bow_mastery[0].1, vec![45], "Bow Mastery is the weapon-column control");
        // The instrument has to be able to SEE variation, or "one distinct row" below would
        // be a property of the parse. Arrow Rain is the control that it can.
        // 3111002 Arrow Rain runs bulletConsume/bulletCount 4,4 -> 5,5 -> 6,6 -> 7,7 -> 8,8
        // over its levels: five distinct rows, counted off the file.
        assert_eq!(
            table.get(&3_111_002).map(Vec::len),
            Some(5),
            "3111002 Arrow Rain varies its bullet columns with level; if this parse cannot \
             see that, it cannot see drift in the rows this module depends on either"
        );

        for l in LOADOUTS.iter() {
            for g in l.skills {
                let rows = table
                    .get(&g.skill_id)
                    .unwrap_or_else(|| panic!("{} ({}) is not in skills.txt", g.name, g.skill_id));
                assert_eq!(
                    rows.len(),
                    1,
                    "{} ({}) varies these columns with level, so a single SkillGate cannot \
                     describe it: {:?}",
                    g.name,
                    g.skill_id,
                    rows
                );
                let (name, weapons, bc, bn) = &rows[0];
                assert_eq!(name, g.name, "skill {}", g.skill_id);
                assert_eq!(weapons, &g.weapon_codes.to_vec(), "{} weapon columns", g.name);
                assert_eq!(*bc, g.bullet_consume, "{} bulletConsume", g.name);
                assert_eq!(*bn, g.bullet_count, "{} bulletCount", g.name);
            }
        }
    }

    /// Every item id in the table is a real id in this client, under exactly this name.
    #[test]
    fn every_item_id_and_name_matches_the_generated_item_list() {
        let Some(text) = handbook("items.txt") else { return };
        let mut names = std::collections::HashMap::new();
        for line in text.lines().filter(|l| !l.starts_with('#') && !l.trim().is_empty()) {
            let (id, name) = line.split_once(',').expect("items.txt row has no comma");
            if let Ok(id) = id.trim().parse::<u32>() {
                names.insert(id, name.trim().to_string());
            }
        }
        assert!(names.len() > 1000, "items.txt parsed to {} names", names.len());
        assert_eq!(names.get(&1_302_000).map(String::as_str), Some("Sword"), "positive control");

        for l in LOADOUTS.iter() {
            for p in l.pieces.iter().chain(l.alternative.iter()) {
                assert_eq!(
                    names.get(&p.item_id).map(String::as_str),
                    Some(p.name),
                    "item {} in this table is {:?}",
                    p.item_id,
                    p.name
                );
            }
        }
    }

    /// A stack bigger than the item's own `slotMax` needs more than one slot. Every
    /// ammunition quantity here is exactly one slot's worth, and this is what says so.
    #[test]
    fn every_ammunition_quantity_fits_one_slot() {
        let Some(text) = handbook("itemdata.txt") else { return };
        let mut slot_max = std::collections::HashMap::new();
        for line in text.lines().filter(|l| !l.starts_with('#') && !l.trim().is_empty()) {
            let f: Vec<&str> = line.split(',').map(str::trim).collect();
            assert_eq!(f.len(), 5, "itemdata.txt row: {line}");
            if let (Ok(id), Ok(m)) = (f[0].parse::<u32>(), f[4].parse::<u16>()) {
                slot_max.insert(id, m);
            }
        }
        assert!(slot_max.len() > 1000, "itemdata.txt parsed to {} rows", slot_max.len());
        assert_eq!(slot_max.get(&2_060_000), Some(&1000), "positive control");

        for l in LOADOUTS.iter() {
            for p in l.pieces.iter().chain(l.alternative.iter()) {
                let m = slot_max
                    .get(&p.item_id)
                    .unwrap_or_else(|| panic!("{} ({}) is not in itemdata.txt, so !item would refuse it", p.name, p.item_id));
                match p.kind {
                    // Every equip's slotMax is absent, which the generator writes as 0.
                    PieceKind::Weapon(_) => assert_eq!(*m, 0, "{} is an equip", p.name),
                    PieceKind::Ammunition => assert_eq!(
                        p.quantity, *m,
                        "{} asks for {} but slotMax is {}",
                        p.name, p.quantity, m
                    ),
                }
            }
        }
    }
}

// =======================================================================================
// WIRE IT LIKE THIS - `!kit`, and it is NOT wired
// =======================================================================================
//
// **WIRED on 2026-08-28 - this section is kept as the record of what was done.** `!kit` in
// `session::gm` calls `loadout_for`, hands each piece over through the shared `give_item`, and
// reports what the character cannot equip. The paragraph below said "nothing above is
// reachable from a running server", which was true when the agent wrote it and is not now.
//
// ## 1. `gm_item`'s body wants extracting first, and there is a precedent for saying so
//
// `session/inventory.rs`'s own header records that the give-an-item path already existed
// twice - "once for `!item` and once for a shop purchase - and the two copies had already
// drifted". Do not make a third. Lift the tail of `Session::gm_item` (everything from
// `let is_equip = ...` to the `inventory_added_replies` call) into
//
//     fn give_item(&mut self, chr_id: u32, inv: store::InventoryType, item_id: u32, count: u16)
//         -> Result<Vec<store::InvRow>, String>
//
// and have `!item` and `!kit` both call it. `!kit` then adds no new wire path at all, which
// is the point: `!item 2060000 1000` already works today and `!kit` is only a shorthand for
// three of them.
//
// ## 2. The command
//
//     "kit" => self.gm_kit(arg),                        // session/gm.rs, beside "item"
//
//     /// `!kit [jobId]` - every item this branch's first-job skills need.
//     pub(super) fn gm_kit(&mut self, arg: &str) -> Vec<Reply> {
//         let Some(chr) = self.claimed_character() else {
//             return self.gm_ack("!kit REFUSED: no character is claimed.".to_string());
//         };
//         let job = arg.trim().parse::<u16>().unwrap_or(chr.job);
//         let Some(kit) = crate::loadout::loadout_for(job) else {
//             return self.gm_ack(format!(
//                 "!kit: job {job} is not a first job. Try 100, 200, 300 or 400."));
//         };
//         if kit.needs_nothing() {
//             return self.gm_ack(format!(
//                 "{} needs nothing: not one of its six skills carries a Skill.wz weapon \
//                  column. That is measured, not an omission - see world::loadout.",
//                 kit.job_name));
//         }
//         let mut out = Vec::new();
//         for p in kit.pieces {
//             let inv = store::InventoryType::for_item(p.item_id).expect("1..5");
//             match self.give_item(chr.id, inv, p.item_id, p.quantity) { .. }
//             // one gm_ack line per piece, naming p.name, p.item_id and inv
//         }
//         // ...then the warnings in §3.
//         out
//     }
//
// Add `!kit [jobId]` to the help string in `session/mod.rs` - it is one line and it is the
// only place a person finds out the command exists.
//
// ## 3. Warn, never refuse - and there are exactly three things to warn about
//
// `CLAUDE.md`'s always-answer rule. A `!kit` that declines because a stat is low is worse
// than one that hands the item over and says so.
//
//   a. **Requirements.** `kit.unequippable(&chr)` returns every piece the character cannot
//      wear with the failing clauses already formatted. This is the `!job 300` case: a
//      character dropped into a job without the stats. Print it; still give the items.
//
//   b. **The Thief needs two weapons.** `THIEF.pieces` is Razor, Garnier and stars, and
//      Double Stab (weapon 33) and Lucky Seven (weapon 47) cannot both be satisfied by one
//      equipped item. Say "swap the weapon between the two skills" in the ack, or a failed
//      Lucky Seven will read as a broken skill when it is a Razor still in the slot.
//
//   c. **The bow and the crossbow take different arrows.** If `kit.alternative` is ever
//      handed out instead, 1462000 needs 2061000 and not 2060000.
//
// ## 4. What NOT to build
//
// * **No new packet.** Ammunition reaches the USE tab through the same
//   `inventory_added_replies` path everything else uses, and `net::bag` already emits the
//   49-byte throwing-star body (`bundle_has_serial`) rather than the 41-byte one. A `!kit`
//   that built its own item body would have to get that gate right a second time.
// * **No equip-requirement enforcement.** This server has never validated an equip and this
//   is not the place to start; `Requirements::met_by` exists to word a warning.
// * **No auto-equip.** Nothing here puts an item in the weapon slot - the owner drags it, which
//   is also the only way to observe whether the client honours `reqLevel`/`reqDEX` at all.
//   That observation is worth more than the convenience.
