[workspace]
resolver = "2"
members = ["crates/wz", "crates/grap-stub", "crates/net", "crates/store", "crates/tlspin", "crates/webhook", "crates/patchset", "crates/auth", "crates/login", "crates/world", "crates/launcher"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "PolyForm-Noncommercial-1.0.0"

[workspace.dependencies]
anyhow = "1"
thiserror = "2"
