#!/usr/bin/env python3
"""Every mob template's stats, out of the client's own `Mob.wz`.

Writes `gm-handbook/mobtemplates.txt`. Generated game data, gitignored, never hand-edited -
same contract as `tools/dump_portals.py` and `tools/dump_equips.py`.

**Why the server needs it.** `MobEnterField` carries the mob's *current* HP, and the client
turns it into the health bar with `mob+0xb60 = hp * 100 / maxHP`, where `maxHP` comes from
the template. The server was sending a flat `100` to every mob - which for a snail
(`maxHP = 30`) is 333% of its health, and for the mob on map 40 (`maxHP = 45`) is 222%. A
freshly spawned mob should be at exactly its template's `maxHP`.

That division is at `141c50502` and has **no zero guard**, so a template this table cannot
supply is a mob the server must not send at full nonsense.

    python tools/dump_mobs.py
"""
import json
import os
import subprocess
import sys

os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

MOB_ARCHIVE = os.path.join("client-patched", "Data", "Mob", "Mob_000.wz")
WZ_DUMP = os.path.abspath(
    os.path.join("target", "release", "wz-dump") + (".exe" if os.name == "nt" else "")
)

# Written in this order. Enumerated from the data rather than assumed - see the counts the
# script prints.
COLUMNS = ["maxHP", "maxMP", "level", "exp", "PADamage", "PDDamage", "MADamage", "MDDamage",
           "acc", "eva", "speed", "pushed", "bodyAttack", "undead", "boss", "summonType"]


def run(*args):
    r = subprocess.run([WZ_DUMP, *args], capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    if r.returncode != 0 or not r.stdout:
        return None
    return r.stdout


def images(archive):
    out = run("tree", archive, "1")
    if not out:
        return
    for line in out.splitlines():
        if "[IMG]" in line:
            yield line.split("[IMG]", 1)[1].split()[0]


def main():
    if not os.path.exists(WZ_DUMP):
        raise SystemExit("%s is missing - run: cargo build --release -p wz" % WZ_DUMP)
    if not os.path.exists(MOB_ARCHIVE):
        raise SystemExit("%s is missing" % MOB_ARCHIVE)

    rows, skipped = [], 0
    for image in images(MOB_ARCHIVE):
        stem = image[:-4] if image.endswith(".img") else image
        if not stem.isdigit():
            continue
        out = run("cat", MOB_ARCHIVE, image)
        if not out:
            skipped += 1
            continue
        try:
            node = json.loads(out)
        except ValueError:
            skipped += 1
            continue
        info = {
            str(k).strip(): v
            for k, v in (node.get("info") or {}).items()
            if not isinstance(v, (dict, list))
        }

        def num(key):
            v = info.get(key, 0)
            try:
                return int(float(v))
            except (TypeError, ValueError):
                return 0

        rows.append((int(stem), [num(c) for c in COLUMNS]))

    rows.sort()
    os.makedirs("gm-handbook", exist_ok=True)
    path = os.path.join("gm-handbook", "mobtemplates.txt")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# templateId, " + ", ".join(COLUMNS) + "\n")
        fh.write("# generated by tools/dump_mobs.py from the client's own Mob.wz.\n")
        for template_id, values in rows:
            fh.write("%d, %s\n" % (template_id, ", ".join(str(v) for v in values)))

    print("%s: %d mob templates" % (path, len(rows)))
    no_hp = [t for t, v in rows if v[0] <= 0]
    print("  %d have maxHP <= 0 - the health-bar divide has no zero guard" % len(no_hp))
    if no_hp[:8]:
        print("   ", no_hp[:8])
    if skipped:
        print("  (%d images could not be read)" % skipped, file=sys.stderr)


if __name__ == "__main__":
    main()
