#!/usr/bin/env python3
"""Which pets each pet equip fits, from the client's own WZ.

Writes `gm-handbook/petequips.txt`. Same shape as `tools/dump_chairs.py`: generated game data,
gitignored, never hand-edited.

    python tools/dump_petequips.py

## Why this exists

The owner, 2026-10-04, with a screenshot of Tester2's Character Info on a Lil Frieren wearing a
Blue Top Hat: *"If a pet equipment is invalid for the current pet, it should not show in pet
info"*. Their own Deco window draws that hat's cell red - the client knows it does not fit.

## What "fits" is

A pet equip's image, `Character/PetEquip/<id>.img` (the client builds that path from the
format string at `0x1432ae940`), has `info` and then **one child per pet it has art for, named
by the pet's item id** - `01802006.img` (Blue Top Hat) has `5000000`, ... and every one of
them holds the `stand0` / `move` / ... frames the pet draws the hat with. A pet with no child
has nothing to draw the hat with. **[L]** for the shape (read below with `wz-dump`); that the
client's red cell tests exactly this child is **[I]** - the predicate itself was not walked.

## A row means MEASURED

`equipId, pet pet pet ..., name`. An equip with no row is unknown, and the server then shows
it rather than guess (`world::config::load_pet_equips`).
"""
import json
import os
import subprocess
import sys

os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

ROOT = os.path.join("client-patched", "Data", "Character", "PetEquip")
OUT = os.path.join("gm-handbook", "petequips.txt")
WZ_DUMP = os.path.abspath(
    os.path.join("target", "release", "wz-dump") + (".exe" if os.name == "nt" else "")
)

# The control: the classic client alone ships ten (1802000..1802009). Fewer is a broken read,
# and an empty file over a good one would silently stop every check.
MIN_EQUIPS = 10


def run(*args):
    r = subprocess.run([WZ_DUMP, *args], capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    if r.returncode != 0 or not r.stdout:
        return None
    return r.stdout


def names():
    path = os.path.join("gm-handbook", "items.txt")
    out = {}
    if not os.path.exists(path):
        print("  ! %s is missing - names will be blank" % path, file=sys.stderr)
        return out
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            parts = line.split(",", 1)
            if len(parts) == 2 and parts[0].strip().isdigit():
                out[int(parts[0].strip())] = parts[1].strip()
    return out


def main():
    if not os.path.exists(WZ_DUMP):
        print("no wz-dump at %s - build it first: cargo build --release -p wz" % WZ_DUMP)
        return 2
    archives = sorted(
        os.path.join(ROOT, f) for f in os.listdir(ROOT)
        if f.startswith("PetEquip_") and f.endswith(".wz")
    ) if os.path.isdir(ROOT) else []
    if not archives:
        print("no PetEquip archives under %s" % ROOT)
        return 2

    item_names = names()
    rows = {}
    for archive in archives:
        tree = run("tree", archive, "1") or ""
        for line in tree.splitlines():
            if "[IMG]" not in line:
                continue
            image = line.split("[IMG]", 1)[1].split()[0]
            stem = image[:-4] if image.endswith(".img") else image
            if not stem.isdigit():
                continue
            text = run("cat", archive, image)
            if not text:
                print("  ! could not read %s/%s" % (archive, image), file=sys.stderr)
                continue
            node = json.loads(text)
            pets = sorted(int(k) for k in node if k.isdigit())
            rows[int(stem)] = pets

    if len(rows) < MIN_EQUIPS:
        print("only %d pet equips read (expected at least %d) - not writing %s"
              % (len(rows), MIN_EQUIPS, OUT))
        return 1

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# generated by tools/dump_petequips.py from the client's own\n")
        fh.write("# Character/PetEquip: equipId, the pet item ids it has art for, name\n")
        for equip in sorted(rows):
            fh.write("%d, %s, %s\n" % (equip, " ".join(str(p) for p in rows[equip]),
                                       item_names.get(equip, "")))
    print("wrote %s: %d pet equips" % (OUT, len(rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
