#!/usr/bin/env python3
"""Every chair's recovery, from the client's own WZ.

Writes `gm-handbook/chairs.txt`. Same shape as `tools/dump_itemdata.py`: generated game data,
gitignored, never hand-edited.

    python tools/dump_chairs.py

## Why this exists

The owner, 2026-09-08: *"my character just sat in a chair, but the idle recovery did not adjust to
match the chair's recovery stats."* The server had no chair support at all - it never learned
that anybody had sat down - and `gm-handbook` carried the chairs' **names** (`items.txt`) and
their price/stack (`itemdata.txt`) but nothing about what they restore.

## The three properties, and the one that is a trap

`Item/Install/Install_000.wz` -> `0301.img`, 11 chairs. Every scalar under `info`, counted:

    price       11/11      slotMax     11/11      recoveryHP  10/11
    reqLevel     8/11      tradeBlock   6/11      notSale      3/11
    recoveryMP   3/11

**`recoveryHP` is absent on one chair and that absence is the data.** The Blue Seal Cushion
(`3010008`) restores **MP only**; it has no `recoveryHP` node at all. A reader that defaults a
missing `recoveryHP` to the common value of 30 would invent HP regeneration for a chair the
client says gives none - which is this repo's "the unit, not the arithmetic" one notch down.
Absent means **0**, and this file writes the 0 explicitly so the server never has to guess.

## A row means MEASURED

Same rule as `dump_itemdata.py`: a chair with `0, 0` is a real statement - it restores nothing -
and is different from the chair not being in the client. An absent row means unknown, and the
server should refuse rather than assume.

## The instrument

A raw byte search over a `.wz` returns zero for `recoveryHP` as readily as for a name that is
really there, because WZ encodes property names. Everything here goes through `wz-dump`, and
the script fails loudly if it cannot find or run it.
"""
import json
import os
import subprocess
import sys

os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

ARCHIVE = os.path.join("client-patched", "Data", "Item", "Install", "Install_000.wz")
IMAGE = "0301.img"
OUT = os.path.join("gm-handbook", "chairs.txt")
WZ_DUMP = os.path.abspath(
    os.path.join("target", "release", "wz-dump") + (".exe" if os.name == "nt" else "")
)

COLUMNS = ["recoveryHP", "recoveryMP", "reqLevel"]

# The control. `dump_itemdata.py` records that a search over a WZ can come back empty for a
# property that is really there, so a run that finds no chairs must fail rather than write an
# empty file over a good one.
MIN_CHAIRS = 5


def main():
    if not os.path.exists(WZ_DUMP):
        print("no wz-dump at %s - build it first: cargo build --release -p wz" % WZ_DUMP)
        return 2
    if not os.path.exists(ARCHIVE):
        print("no archive at %s" % ARCHIVE)
        return 2

    r = subprocess.run([WZ_DUMP, "cat", ARCHIVE, IMAGE], capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    if r.returncode != 0 or not r.stdout:
        print("wz-dump failed: %s" % (r.stderr or "no output"))
        return 1
    tree = json.loads(r.stdout)

    names = {}
    items_txt = os.path.join("gm-handbook", "items.txt")
    if os.path.exists(items_txt):
        with open(items_txt, encoding="utf-8") as fh:
            for line in fh:
                item_id, _, name = line.partition(",")
                if name:
                    names[item_id.strip()] = name.strip()

    rows = []
    for key in sorted(tree):
        if not key.isdigit():
            continue
        info = tree[key].get("info")
        if not isinstance(info, dict):
            continue
        item_id = int(key)
        vals = []
        for col in COLUMNS:
            v = info.get(col)
            # Absent is 0 and is written as 0 - see the module docs on the Blue Seal Cushion.
            vals.append(int(v) if isinstance(v, (int, float)) else 0)
        rows.append((item_id, vals, names.get(str(item_id), "")))

    if len(rows) < MIN_CHAIRS:
        print("REFUSING TO WRITE: found %d chair(s), expected at least %d. That is the shape of"
              % (len(rows), MIN_CHAIRS))
        print("a broken read rather than of a client with no chairs. %s left untouched." % OUT)
        return 1

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# itemId, %s, name\n" % ", ".join(COLUMNS))
        fh.write("# generated by tools/dump_chairs.py from the client's own\n")
        fh.write("# Data/Item/Install/Install_000.wz `0301.img`. Never hand-edit.\n")
        fh.write("# A MISSING property is written as 0 and means the chair restores none of\n")
        fh.write("# that pool - the Blue Seal Cushion has no recoveryHP at all.\n")
        for item_id, vals, name in rows:
            fh.write("%d, %s, %s\n" % (item_id, ", ".join(str(v) for v in vals), name))

    print("wrote %s: %d chair(s)" % (OUT, len(rows)))
    hp = sum(1 for _, v, _ in rows if v[0])
    mp = sum(1 for _, v, _ in rows if v[1])
    print("  %d restore HP, %d restore MP, %d restore neither"
          % (hp, mp, sum(1 for _, v, _ in rows if not v[0] and not v[1])))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
