#!/usr/bin/env python3
"""Every mob's MP, MP-costing attacks and skills, and every mob skill level those name, out of
the client's own `Mob.wz` and `Skill/MobSkill`.

Writes `gm-handbook/mobskills.txt`. Generated game data, gitignored, never hand-edited - the
same contract as `tools/dump_mobs.py`. Read by `world::mobskills::MobSkillTable::load`.

**Why the server needs it.** A mob's move acknowledgement (`0x03E4`) carries the mob's MP,
and the client's attack chooser rules out any attack costing more than that
(`world::mobskills` has the addresses). The server used to send `0` for every mob, so no
attack with a `conMP` - King Slime's jump, and 48 others - was ever chosen, and no skill was
ever offered. The owner, 2026-09-24: *"Please solve this for all mobs with skills."*

Rows, comma separated, one kind per leading word:

    mob,    template, maxMP, mpRecovery
    attack, template, index, conMP, afterDelay
    skill,  template, skill, level
    level,  skill, level, mpCon, interval, hp, limit, summon1 summon2 ...

Only mobs with a skill or an MP-costing attack are written; every other mob's attacks are free
and its MP never matters.

    python tools/dump_mobskills.py
"""
import json
import os
import subprocess

os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

MOB_ARCHIVE = os.path.join("client-patched", "Data", "Mob", "Mob_000.wz")
SKILL_ARCHIVE = os.path.join("client-patched", "Data", "Skill", "MobSkill", "MobSkill_000.wz")
OUT = os.path.join("gm-handbook", "mobskills.txt")
WZ_DUMP = os.path.abspath(
    os.path.join("target", "release", "wz-dump") + (".exe" if os.name == "nt" else "")
)


def run(*args):
    r = subprocess.run([WZ_DUMP, *args], capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    if r.returncode != 0 or not r.stdout:
        return None
    return r.stdout


def images(archive):
    out = run("tree", archive, "1")
    for line in (out or "").splitlines():
        if "[IMG]" in line:
            yield line.split("[IMG]", 1)[1].split()[0]


def as_int(v, default=0):
    try:
        return int(v)
    except (TypeError, ValueError):
        return default


def main():
    for p in (WZ_DUMP, MOB_ARCHIVE, SKILL_ARCHIVE):
        if not os.path.exists(p):
            raise SystemExit("%s is missing" % p)

    mob_rows, attack_rows, skill_rows = [], [], []
    wanted = set()
    for image in images(MOB_ARCHIVE):
        text = run("cat", MOB_ARCHIVE, image)
        if not text:
            continue
        info = json.loads(text).get("info", {})
        template = as_int(image.split(".")[0], None)
        if template is None:
            continue
        attacks = []
        for k, a in sorted((info.get("attack") or {}).items(), key=lambda kv: as_int(kv[0])):
            if isinstance(a, dict) and as_int(a.get("conMP")) > 0:
                attacks.append((as_int(k), as_int(a.get("conMP")), as_int(a.get("afterDelay"))))
        skills = []
        for k, s in sorted((info.get("skill") or {}).items(), key=lambda kv: as_int(kv[0])):
            if isinstance(s, dict) and "skill" in s:
                skills.append((as_int(s.get("skill")), as_int(s.get("level"))))
        if not attacks and not skills:
            continue
        mob_rows.append("mob, %d, %d, %d" % (template, as_int(info.get("maxMP")), as_int(info.get("mpRecovery"))))
        attack_rows += ["attack, %d, %d, %d, %d" % (template, i, c, d) for i, c, d in attacks]
        skill_rows += ["skill, %d, %d, %d" % (template, s, l) for s, l in skills]
        wanted.update(skills)

    level_rows = []
    for skill, level in sorted(wanted):
        text = run("cat", SKILL_ARCHIVE, "%d.img" % skill)
        lv = (json.loads(text).get("level", {}) if text else {}).get(str(level))
        if lv is None:
            print("  missing: MobSkill %d level %d" % (skill, level))
            continue
        summons = [str(as_int(v)) for k, v in sorted(lv.items(), key=lambda kv: as_int(kv[0], 99))
                   if k.isdigit() and not isinstance(v, dict)]
        level_rows.append("level, %d, %d, %d, %d, %d, %d, %s" % (
            skill, level, as_int(lv.get("mpCon")), as_int(lv.get("interval")),
            as_int(lv.get("hp")), as_int(lv.get("limit")), " ".join(summons)))

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("# generated by tools/dump_mobskills.py from Mob.wz and Skill/MobSkill. Never hand-edit.\n")
        f.write("# mob, template, maxMP, mpRecovery | attack, template, index, conMP, afterDelay\n")
        f.write("# skill, template, skill, level | level, skill, level, mpCon, interval, hp, limit, summons\n")
        for row in mob_rows + attack_rows + skill_rows + level_rows:
            f.write(row + "\n")
    print("%d mobs, %d MP-costing attacks, %d skill uses, %d skill levels -> %s" % (
        len(mob_rows), len(attack_rows), len(skill_rows), len(level_rows), OUT))


if __name__ == "__main__":
    main()
