#!/usr/bin/env python3
"""Every scroll's success rate, destroy rate and stat increments, from the client's own WZ.

Writes `gm-handbook/scrolls.txt`. Same shape as `tools/dump_itemdata.py`: generated game data,
gitignored, never hand-edited.

    python tools/dump_scrolls.py

## Why this exists

The owner, 2026-09-08: *"in the gm-handbook, I cannot find scroll items, where are they stored."*
They were half there. `items.txt` has all 208 names and `itemdata.txt` has their price and
stack size - but **no file carried a scroll's effect**, which was checked by enumerating every
handbook file's column header rather than grepping for likely names. `equips.txt` has
`incSTR`/`incWAT`, but those are the stats an equip *has*, not what a scroll *grants*.

## The fields, measured across all 208 nodes of `0204.img`

    price      208/208     success    208/208     cursed      52/208
    incWAT      52/208     incPDD      23/208     incMDD      19/208
    incACC      16/208     incMHP/incMMP/incSTR/incDEX/incINT/incLUK/incMAD  12 each
    incEVA/incJump/incSpeed  8 each               incCRT/incCRD   4 each
    itemID1/2/3 52/208

`success` takes exactly three values - **100 (52 scrolls), 60 (52), 10 (104)** - which is the
Lesser / Intermediate / Advanced tiering.

**Only 52 of 208 carry `cursed` at all**, so most of these scrolls cannot destroy the item. The
obvious guess is that the 52 with `cursed` are the 52 with `incWAT`, or the 52 with
`itemID1/2/3`. **Both were checked and both are false.** Absent `cursed` is written as 0 and
means the item is never destroyed; do not derive it from anything else.

## A row means MEASURED

An all-zero increment row is a real statement about a scroll. An absent row means the id is not
in this client, which is the case where the server should refuse rather than assume.
"""
import json
import os
import subprocess
import sys

os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

ARCHIVE = os.path.join("client-patched", "Data", "Item", "Consume", "Consume_000.wz")
IMAGE = "0204.img"
OUT = os.path.join("gm-handbook", "scrolls.txt")
WZ_DUMP = os.path.abspath(
    os.path.join("target", "release", "wz-dump") + (".exe" if os.name == "nt" else "")
)

# Column order is fixed and additive: a reader that knows the first N columns keeps reading the
# same N things if more are appended. `success` and `cursed` first because they are on every
# row and every row's behaviour turns on them.
COLUMNS = [
    "success", "cursed",
    "incSTR", "incDEX", "incINT", "incLUK",
    "incMHP", "incMMP",
    "incWAT", "incMAD", "incPDD", "incMDD",
    "incACC", "incEVA", "incSpeed", "incJump",
    "incCRT", "incCRD",
]

# The control: a WZ search can come back empty for a property that is really there, so a run
# that finds almost nothing must fail rather than overwrite a good file.
MIN_SCROLLS = 50


def main():
    if not os.path.exists(WZ_DUMP):
        print("no wz-dump at %s - build it first: cargo build --release -p wz" % WZ_DUMP)
        return 2
    if not os.path.exists(ARCHIVE):
        print("no archive at %s" % ARCHIVE)
        return 2

    r = subprocess.run([WZ_DUMP, "cat", ARCHIVE, IMAGE], capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    if r.returncode != 0 or not r.stdout:
        print("wz-dump failed: %s" % (r.stderr or "no output"))
        return 1
    tree = json.loads(r.stdout)

    names = {}
    items_txt = os.path.join("gm-handbook", "items.txt")
    if os.path.exists(items_txt):
        with open(items_txt, encoding="utf-8") as fh:
            for line in fh:
                item_id, _, name = line.partition(",")
                if name:
                    names[item_id.strip()] = name.strip()

    rows = []
    for key in sorted(tree):
        if not key.isdigit():
            continue
        info = tree[key].get("info")
        if not isinstance(info, dict):
            continue
        item_id = int(key)
        vals = []
        for col in COLUMNS:
            v = info.get(col)
            vals.append(int(v) if isinstance(v, (int, float)) else 0)
        rows.append((item_id, vals, names.get(str(item_id), "")))

    if len(rows) < MIN_SCROLLS:
        print("REFUSING TO WRITE: found %d scroll(s), expected at least %d. That is the shape"
              % (len(rows), MIN_SCROLLS))
        print("of a broken read. %s left untouched." % OUT)
        return 1

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# itemId, %s, name\n" % ", ".join(COLUMNS))
        fh.write("# generated by tools/dump_scrolls.py from the client's own\n")
        fh.write("# Data/Item/Consume/Consume_000.wz `0204.img`. Never hand-edit.\n")
        fh.write("# success and cursed are PERCENTAGES. A missing property is written as 0;\n")
        fh.write("# cursed 0 means the scroll never destroys the item, and 156 of 208 are 0.\n")
        for item_id, vals, name in rows:
            fh.write("%d, %s, %s\n" % (item_id, ", ".join(str(v) for v in vals), name))

    print("wrote %s: %d scroll(s)" % (OUT, len(rows)))
    import collections
    dist = collections.Counter(v[0] for _, v, _ in rows)
    print("  success rates: %s" % sorted(dist.items()))
    print("  %d can destroy the item (cursed > 0)" % sum(1 for _, v, _ in rows if v[1]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
