#!/usr/bin/env python3
"""Every NPC's name, dialogue and idle chatter, out of the client's own `String.wz`.

Writes `gm-handbook/npcstrings.txt`. Generated game data, gitignored, never hand-edited -
same contract as `tools/dump_portals.py`, `dump_equips.py` and `dump_mobs.py`.

`String.wz/Npc.img` has one entry per NPC template. Robin (template 8) is:

    name  Robin
    n0..n3, f0..f2, w0..w1, h0    ten lines
    d0..d1                        two lines

**The grouping is read off the data, not assumed.** A fan site lists Robin's idle chatter as
exactly `n0 n1 n2 n3 f0 f1 f2 w0 w1 h0` in that order and their spoken dialogue as `d0 d1`,
and that matches this entry key for key. The prefix order `n`, `f`, `w`, `h` is therefore
**[D]** from one worked example plus an outside list - not [L], and what the prefixes *mean*
is still open. Within a prefix the numeric suffix orders the lines.

**`#p8#` is left in the text.** It is a name-substitution token (`p` = NPC name, template 8)
and whether the client expands it is being established. Sending it raw is the cheaper
experiment: the screen says which way it went, with no guess required.

TSV, because the text contains commas, apostrophes and quotes but no tabs.

    python tools/dump_npcstrings.py
"""
import json
import os
import re
import subprocess
import sys

os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

STRING_ARCHIVE = os.path.join("client-patched", "Data", "String", "String_000.wz")
WZ_DUMP = os.path.abspath(
    os.path.join("target", "release", "wz-dump") + (".exe" if os.name == "nt" else "")
)

# The idle-chatter prefixes, in the order the lines are shown in.
#
# **Four of twelve prefixes present in the data are used, and the rest are NOT classified.**
# Running this script prints the census: n 402, d 209, c 130, s 109, f 16, w 12, h 11, and
# single digits of l, a, b, i, m. Robin has only n/f/w/h/d, which is why their ten lines match
# the outside list exactly - they cannot discriminate the others. `c` and `s` are common enough
# to be something real, and if either turns out to be chatter this table is silently short.
# Do not treat the four below as the complete set until something reads them out of the
# client.
#
# Note the generated key is `idleN`, not `cN`: the data has its own `c` prefix and reusing
# the letter would make a generated key indistinguishable from a WZ one.
CHATTER_PREFIXES = ["n", "f", "w", "h"]
# What the NPC says when talked to.
DIALOGUE_PREFIX = "d"

KEY = re.compile(r"^([a-z]+)(\d+)$")


def run(*args):
    r = subprocess.run([WZ_DUMP, *args], capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    if r.returncode != 0 or not r.stdout:
        return None
    return r.stdout


def ordered(entry, prefixes):
    """Every `<prefix><n>` value, prefix-major then numeric."""
    out = []
    for prefix in prefixes:
        keyed = []
        for key, value in entry.items():
            m = KEY.match(str(key).strip())
            if m and m.group(1) == prefix and isinstance(value, str):
                keyed.append((int(m.group(2)), value))
        out.extend(v for _, v in sorted(keyed))
    return out


def main():
    if not os.path.exists(WZ_DUMP):
        raise SystemExit("%s is missing - run: cargo build --release -p wz" % WZ_DUMP)
    out = run("cat", STRING_ARCHIVE, "Npc.img")
    if not out:
        raise SystemExit("could not read String.wz/Npc.img")
    npcs = json.loads(out)

    rows, prefixes_seen = [], {}
    for key, entry in npcs.items():
        if not str(key).isdigit() or not isinstance(entry, dict):
            continue
        template = int(key)
        name = entry.get("name")
        if isinstance(name, str) and name:
            rows.append((template, "name", name))
        for i, line in enumerate(ordered(entry, [DIALOGUE_PREFIX])):
            rows.append((template, "d%d" % i, line))
        for i, line in enumerate(ordered(entry, CHATTER_PREFIXES)):
            rows.append((template, "idle%d" % i, line))
        # The `n` group on its own. `0x0453` with nAction = -1 indexes the WZ's
        # `info/speak` list, and `info` is the animation node the `n` prefix belongs to -
        # the other three prefixes hang off `finger`, `wink` and `heart`. So a chat balloon
        # that does not change the animation can only reach these.
        for i, line in enumerate(ordered(entry, ["n"])):
            rows.append((template, "info%d" % i, line))
        for k in entry:
            m = KEY.match(str(k).strip())
            if m:
                prefixes_seen[m.group(1)] = prefixes_seen.get(m.group(1), 0) + 1

    rows.sort(key=lambda r: (r[0], r[1] != "name", r[1]))
    os.makedirs("gm-handbook", exist_ok=True)
    path = os.path.join("gm-handbook", "npcstrings.txt")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# templateId\tkey\ttext   (TAB separated)\n")
        fh.write("# generated by tools/dump_npcstrings.py from String.wz/Npc.img.\n")
        fh.write("# key: name | dN dialogue | idleN all chatter | infoN the info/speak group\n")
        fh.write("# chatter order is prefix-major n, f, w, h then numeric - see the module doc\n")
        for template, key, text in rows:
            clean = " ".join(text.split())
            fh.write("%d\t%s\t%s\n" % (template, key, clean))

    npc_count = len({r[0] for r in rows})
    print("%s: %d rows across %d NPCs" % (path, len(rows), npc_count))
    print("  prefixes present in the data, with counts:")
    for p, n in sorted(prefixes_seen.items(), key=lambda kv: -kv[1]):
        mark = "  <- used" if p in CHATTER_PREFIXES + [DIALOGUE_PREFIX] else ""
        print("    %-4s %d%s" % (p, n, mark))
    chatter = sum(1 for r in rows if r[1].startswith("idle"))
    dialogue = sum(1 for r in rows if r[1].startswith("d"))
    print("  %d idle-chatter lines, %d dialogue lines" % (chatter, dialogue))


if __name__ == "__main__":
    main()
