#!/usr/bin/env python3
r"""Every pet command the client understands, out of its own WZ.

    python tools/dump_pets.py            # -> gm-handbook/petcommands.txt

The owner, 2026-09-13: *"The pet commands are actually regular chat messages. They will still
happen as regular chat messages in the game, but if those messages match as one of the pet
commands, then the pet should respond accordingly. Please check the client WZ for the actions
that the pet can do and the lines it says."*

They are all in the client, in three places, and this joins them:

| where | what |
|---|---|
| `Item/Pet/<id>.img/interact/<n>` | `command` (`c1`..), `prob` (percent), `l0`/`l1` (the pet level range this entry serves), `inc` (closeness gained), and `success.0` / `fail.0`, each an `act` (an animation name that is also a node of the same image - `rest0`, `nap`, `cry`, `dung`, `chat`, `prone`, `rise`, `hand`, `angry`, `tedious`, `stand1`) plus numbered line KEYS |
| `String/PetCommand.img/<id>/<cN>` | the words that trigger it, pipe-separated: `bad\|no\|badgirl\|badboy` |
| `String/PetDialog.img/<id>/<key>` | the line itself, e.g. `c1_s1` -> "Bark bark!" |

So one command word maps to several `interact` entries - one per level band - and the server
picks the band the pet's level falls in, rolls `prob`, and speaks one of that outcome's lines
while the client plays `act`.

The output is one row per LINE, tab separated, because the lines contain commas and quotes:

    petId  index  words  prob  l0  l1  inc  kind  act  text

`kind` is `s` or `f`. Rows for one `(petId, index)` share everything but `kind`/`act`/`text`.
A tab or newline inside a line would break the format, so both are refused rather than escaped
- neither occurs in this client's data, and a silent mangling is worse than a loud stop.
"""
import json
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WZ_DUMP = os.path.join(REPO, "target", "release", "wz-dump" + (".exe" if os.name == "nt" else ""))
PET_ARCHIVE = os.path.join(REPO, "client-patched", "Data", "Item", "Pet", "Pet_000.wz")
STRING_ARCHIVE = os.path.join(REPO, "client-patched", "Data", "String", "String_000.wz")
OUT = os.path.join(REPO, "gm-handbook", "petcommands.txt")


def cat(archive, image):
    p = subprocess.run([WZ_DUMP, "cat", archive, image], capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    if p.returncode != 0:
        raise SystemExit("wz-dump cat %s %s failed:\n%s" % (archive, image, p.stderr.strip()))
    return json.loads(p.stdout)


def main():
    if not os.path.exists(WZ_DUMP):
        raise SystemExit("%s is missing - run: cargo build --release -p wz" % WZ_DUMP)
    commands = cat(STRING_ARCHIVE, "PetCommand.img")
    dialog = cat(STRING_ARCHIVE, "PetDialog.img")

    rows = []
    pets, skipped = 0, []
    for pet_id in sorted(commands, key=lambda k: int(k)):
        image = "%07d.img" % int(pet_id)
        try:
            tree = cat(PET_ARCHIVE, image)
        except SystemExit:
            skipped.append(pet_id)      # a pet the classic client's Pet archive does not have
            continue
        interact = tree.get("interact")
        if not isinstance(interact, dict):
            skipped.append(pet_id)
            continue
        words_of = commands.get(pet_id, {})
        lines_of = dialog.get(pet_id, {})
        pets += 1
        for index in sorted(interact, key=lambda k: int(k)):
            node = interact[index]
            command = node.get("command")
            words = words_of.get(command)
            if not command or not words:
                continue                # an interact entry no word reaches
            for kind, key in (("s", "success"), ("f", "fail")):
                outcome = (node.get(key) or {}).get("0")
                if not isinstance(outcome, dict):
                    continue
                act = outcome.get("act", "")
                for slot in sorted((k for k in outcome if k.isdigit()), key=int):
                    text = lines_of.get(outcome[slot])
                    if not text:
                        continue
                    if "\t" in text or "\n" in text or "\r" in text:
                        raise SystemExit("pet %s %s carries a tab or newline: %r" % (pet_id, outcome[slot], text))
                    rows.append((int(pet_id), int(index), words, int(node.get("prob", 0)),
                                 int(node.get("l0", 1)), int(node.get("l1", 30)),
                                 int(node.get("inc", 0)), kind, act, text))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# petId\tindex\twords\tprob\tl0\tl1\tinc\tkind\tact\ttext\n")
        fh.write("# generated by tools/dump_pets.py from the client's own Item/Pet + String/PetCommand + String/PetDialog.\n")
        fh.write("# One row per LINE. `words` is pipe-separated and matched against a chat message;\n")
        fh.write("# `index` is the interact entry, which is what the pet action packet carries.\n")
        for r in rows:
            fh.write("\t".join(str(x) for x in r) + "\n")
    print("dump_pets.py         %d rows for %d pets -> %s%s" % (
        len(rows), pets, os.path.relpath(OUT, REPO),
        (" (no interact node: %s)" % ",".join(skipped)) if skipped else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
