#!/usr/bin/env python3
"""Bake the two item RESTRICTIONS into crates/store/src/inventory.rs.

    python tools/dump_itemdata.py     # first: extract from the client's WZ
    python tools/gen_item_rules.py    # then: bake the two id lists into the store crate

## What this generates, and why it is committed when itemdata.txt is not

`gm-handbook/itemdata.txt` is generated game data and gitignored - the repo carries the code
to regenerate it, not the content. That is the right call for a 2785-row table of prices,
stack sizes and ids.

It is the wrong call for a **rule**. The owner set two:

    "Please do not allow untradeable items to be stored."
    "Please do not allow quest items to be sold."

`crates/store` enforces the first at its own API, the same way it enforces password hashing
rather than trusting callers. A rule that silently stops being enforced when a gitignored file
is absent is not a rule - it fails OPEN, and an untradeable item quietly reaching storage is
exactly the failure nothing downstream would ever report. `crates/world` can afford to load
itemdata.txt at runtime because a missing shop is visible on screen; a missing restriction is
not.

So this writes the two **id lists** - the rules, about 160 integers, no prices, no names, no
stats - into a marked region of `crates/store/src/inventory.rs`. Everything else stays in the
gitignored dump. A test in that file (`the_baked_item_rules_still_match_the_clients_own_table`)
re-derives both lists from `itemdata.txt` whenever it is present, so this going stale is caught
by `cargo test` rather than by a player losing an item.

## The instrument, and how to tell it is lying

Reading zero rows and writing two empty lists would look exactly like "this client blocks
nothing", and every deposit would then be allowed. So this REFUSES to write a file when it
parses no rows, and prints the census it found. The numbers to expect, from
`tools/dump_itemdata.py`'s own summary and from STATUS.md goal F:

    2785 items, 39 with tradeBlock, 119 with quest

A run that prints different numbers is either a regenerated WZ dump or a broken parse. Check
which before committing the result.
"""
import os
import sys

os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

SOURCE = os.path.join("gm-handbook", "itemdata.txt")
TARGET = os.path.join("crates", "store", "src", "inventory.rs")

BEGIN = "    // --- BEGIN GENERATED by tools/gen_item_rules.py - do not edit by hand ---"
END = "    // --- END GENERATED ---"

# Column order written by tools/dump_itemdata.py: itemId, price, quest, tradeBlock, slotMax
QUEST = 2
TRADE_BLOCK = 3
COLUMNS = 5


def read_items():
    rows = []
    with open(SOURCE, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            cells = [c.strip() for c in line.split(",")]
            if len(cells) != COLUMNS:
                continue
            try:
                rows.append([int(c) for c in cells])
            except ValueError:
                continue
    return rows


def rust_list(ids):
    """One id per line is 160 lines of noise; eight per line stays diffable."""
    if not ids:
        return "&[]"
    per_line = 8
    lines = []
    for i in range(0, len(ids), per_line):
        lines.append("        " + " ".join("%d," % n for n in ids[i:i + per_line]))
    return "&[\n" + "\n".join(lines) + "\n    ]"


def main():
    if not os.path.exists(SOURCE):
        raise SystemExit(
            "%s is missing. It is generated and gitignored; run:\n"
            "    python tools/dump_itemdata.py" % SOURCE
        )

    rows = read_items()
    blocked = sorted(r[0] for r in rows if r[TRADE_BLOCK])
    quest = sorted(r[0] for r in rows if r[QUEST])

    print("%s: %d items" % (SOURCE, len(rows)))
    print("  %4d carry tradeBlock - these may NOT be stored" % len(blocked))
    print("  %4d carry quest      - these may NOT be sold" % len(quest))

    # A parse that read nothing would write two empty lists, and every deposit would then be
    # allowed. Refuse rather than ship a rule that permits everything.
    if not rows:
        raise SystemExit(
            "read 0 items from %s - refusing to write empty rule lists, which would allow "
            "every untradeable item into storage. Regenerate the dump first." % SOURCE
        )
    if not blocked:
        raise SystemExit(
            "read %d items but NONE carries tradeBlock. That is a broken parse or a changed "
            "column order, not a client with no untradeable items - refusing to write." % len(rows)
        )

    with open(TARGET, encoding="utf-8") as fh:
        text = fh.read()
    if BEGIN not in text or END not in text:
        raise SystemExit("the generated markers are missing from %s" % TARGET)

    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)

    body = "\n".join([
        BEGIN,
        "    /// How many item rows the lists below were distilled from. Provenance only; a"
        " test",
        "    /// compares it against the live `gm-handbook/itemdata.txt` when that file exists.",
        "    pub const GENERATED_FROM_ITEMS: usize = %d;" % len(rows),
        "    /// Item ids with `info/tradeBlock` set, ascending.",
        "    pub const TRADE_BLOCKED: &'static [u32] = %s;" % rust_list(blocked),
        "    /// Item ids with `info/quest` set, ascending.",
        "    pub const QUEST_ITEMS: &'static [u32] = %s;" % rust_list(quest),
        END,
    ])

    with open(TARGET, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(head + body + tail)
    print()
    print("wrote the two id lists into %s" % TARGET)
    print("run `cargo test -p store` - the drift test re-derives them from the dump")


if __name__ == "__main__":
    main()
