<#
.SYNOPSIS
    Reach character select with a character in the list, and capture what the character
    creation screen sends.

.DESCRIPTION
    Wraps test-one.ps1 with the four-part recipe that gets the client to a usable login
    screen, and answers its 0x0080 with a world entry, the terminator, and a login result
    that carries a real character list.

    The reply bodies are generated by `packet-hex`, never typed. The world-list hex was
    once two characters too long on a command line and the only reason it was caught is
    that a test happened to compare against the builder; this removes the hand-typing
    entirely.

    Two things are being measured, and the second is the point:

      1. Does character select draw the character? That is the first time any of the
         record layout has been on the wire.
      2. What does the creation screen send? The create request is Themida-virtualised
         and cannot be read statically. The OK button sends 0x0081 and the create request
         back to back in one click, so both land in probe.log.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File "C:\MapleCW\tools\test-charselect.ps1"
    powershell -ExecutionPolicy Bypass -File "C:\MapleCW\tools\test-charselect.ps1" -Stop
#>
[CmdletBinding()]
param(
    [switch]$Stop,
    # Names to put in the character list. No names sends an empty list, which is the
    # control: it is what every previous run has effectively been doing.
    [string[]]$Characters = @('Maple'),
    # Shown on the login screen. Server-supplied - the client cannot compute it, so leaving
    # 0x0000 out of the sequence makes the field go blank, which is exactly what happened
    # on the first character-list run.
    [string]$LoginName = 'maplecw',
    [string]$AccountName = 'wisp****@example.com',
    # The name of the character the create reply hands back. The harness cannot read the
    # name out of the request, so type this one in the client and the screen stays
    # coherent - type another and the transaction still completes, it just visibly
    # comes from the server rather than from what was asked for.
    [string]$NewCharacterName = 'Hello',
    # Seconds between keepalive packets. This was a hypothesis - that the client wants a
    # heartbeat - and it is disproven: the 2026-08-17 run logged two keepalives going out,
    # the last 6.8s before the close, and the client still exited. Kept on because it costs
    # nothing and rules the idle path out of every future run at a glance. Set 0 to drop it.
    [double]$Keepalive = 10,
    # Watch targets, comma separated, four slots. The first has to stay: without it the
    # "trouble logging in" dialog blocks the tick that enables the Login button, and the
    # run never reaches character select at all.
    #
    # The other two are aimed at the ~25 second exit, which is the priority. Everything
    # that runs *inside* the process on the way out has already been ruled out with
    # verified breakpoints - RtlExitUserProcess, NtTerminateProcess, and any fault a
    # vectored handler can see - so the two survivors are an external kill, which executes
    # no client code at all, and the last thread ending, which executes exactly these:
    #
    #   ntdll!RtlExitUserThread - every thread that returns from its start routine
    #   ntdll!NtTerminateThread - the syscall under that, and under TerminateThread
    #
    # :hits=200 raises the per-target log cap from the default 32. The default is there so
    # a per-frame function cannot fill the disk, and it is exactly wrong here: if the client
    # recycles threads, the cap would be spent long before the exit and the watch would
    # disarm itself, which reads identically to a function that never ran. Silence on both,
    # with the cap demonstrably not reached, means nothing inside the client ended it.
    #
    # 141b36a10:peek=1c0 held this slot to read the world id the create-result handler
    # compares ours against. It measured 0 on 2026-08-17 and matched, so the slot is free.
    [string]$Probe = 'watch@141b2a280:rdx=0,ntdll!RtlExitUserThread:hits=200,ntdll!NtTerminateThread:hits=200',
    # 'mode=2,create=on' calls FUN_140c9e230 after the login result, which sets the
    # protected flag that gates the "Create a character" button. A watch measured
    # FUN_140c9e3f0 returning zero on every click, and the only setter that writes 1 has no
    # caller in .text - the real service enables this from virtualised code. THIS IS A
    # CLIENT PATCH. Use 'mode=2' alone to reproduce the dead button.
    [string]$Session = 'mode=2,create=on',
    [int]$Port = 8484,
    # Strip every client patch: no dispatcher hook, no int3 watches, no session patching.
    # The client is left byte-identical to the installed copy, so the only difference from
    # a stock run is our grap64.dll stub and the firewall.
    #
    # This is the control for the ~36.9s __fastfail. That deadline is anchored to process
    # start - 36.96s and 36.89s across two runs, 0.07s apart, while the interval from the
    # login result moved by 3.2s - so it is not a reaction to anything on the wire. A
    # process-anchored deadline is exactly what an integrity check over our own patched
    # .text would produce, and this run removes those patches to test it.
    #
    # There is no hook log in this mode, by construction. client-exit.log carries the
    # answer: the EXIT code line and the lifetime.
    [switch]$NoPatch,
    # Aim every watch slot at the CRT fatal paths that can raise the __fastfail.
    #
    # Ghidra found exactly 8 real `int 0x29` instructions in .text - a raw byte scan
    # reported 63, because x86 is variable-length and the scan is not instruction-aligned -
    # and they all sit in the MSVC CRT's own machinery, each behind the standard
    # `IsProcessorFeaturePresent(0x17)` preamble. The reason code names the path: 7 is
    # FATAL_APP_EXIT (abort), 5 is INVALID_ARG (the invalid-parameter handler), 2 is a
    # stack cookie failure. So this is an ordinary runtime fatal error, not a bespoke
    # anticheat kill, and an entry to any of these four names which one.
    #
    # No session patch and no dialog patch: the client dies at the same ~36.7s stuck behind
    # the "trouble logging in" dialog as it does at character select, so the protocol path
    # is irrelevant here and fewer patches makes a cleaner run.
    [switch]$FastFail
)

$ErrorActionPreference = 'Stop'
$here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
$root = Split-Path -Parent $here
$testOne = Join-Path $here 'test-one.ps1'

if ($Stop) {
    & powershell -ExecutionPolicy Bypass -File $testOne -Stop
    exit $LASTEXITCODE
}

function Get-Packet {
    param([string[]]$PacketArgs)
    # packet-hex prints "OPCODE:HEX" on stdout and the byte count on stderr, so only
    # stdout is captured here. A build failure must not be pasted onto the wire as hex.
    Push-Location $root
    try {
        $out = & cargo run --release -q -p net --bin packet-hex -- @PacketArgs
        if ($LASTEXITCODE -ne 0) { throw "packet-hex failed for: $($PacketArgs -join ' ')" }
    }
    finally { Pop-Location }
    $line = ($out | Where-Object { $_ -match '^[0-9a-f]{4}:' } | Select-Object -First 1)
    if (-not $line) { throw "packet-hex printed no packet for: $($PacketArgs -join ' ')" }
    return $line.Trim()
}

# Rebuilding grap-stub does not update the client: cargo writes target/release/grap64.dll
# and the client loads client-patched/grap64.dll. Skipping this is the most expensive kind
# of failure here, because the run looks normal and the new hook code simply is not there.
Push-Location $root
try {
    & cargo build --release -p grap-stub
    if ($LASTEXITCODE -ne 0) { throw 'grap-stub failed to build' }
}
finally { Pop-Location }
& powershell -ExecutionPolicy Bypass -File (Join-Path $here 'setup-client.ps1')
if ($LASTEXITCODE -ne 0) { throw 'setup-client.ps1 failed - the client would run the old hook' }

$accountInfo = Get-Packet @('account-info', $LoginName, $AccountName)
$worldEntry = Get-Packet @('world-entry', 'Scania')
$worldEnd = Get-Packet @('world-end')
$loginResult = Get-Packet (@('login-result') + $Characters)

# Account first: the name it carries is drawn on the login screen, which the client is
# still showing when this sequence lands.
$replySeq = "$accountInfo,$worldEntry,$worldEnd,$loginResult"
# Standing answers - both fire every time, because both are things the user can click
# repeatedly and a one-shot would look like the button breaking after the first use.
#
#   0x00A8 -> 0x05F4   "Create a character": the placeholder-PIC check. 0 opens NewChar.
#   0x0081 -> 0x0014   the name check. The reply must quote the name that was asked about,
#                      hence <req>, which splices the request's payload in; the trailing
#                      00 is CharNameResult 0 = available.
$enterCreation = Get-Packet @('enter-creation')
$createResult = Get-Packet @('create-result', $NewCharacterName)
# One semicolon-separated string, not an array: these scripts are invoked through
# `powershell -File`, which flattens an array into separate command-line words, so the
# second entry bound positionally to -Variant and killed the run at parameter binding.
#
#   0x008A -> 0x0015   the create request, measured off the wire. Its builder is
#                      virtualised, so the opcode could only ever have come from a capture.
$answers = "00a8=$enterCreation;0081=0014:<req>00;008a=0015:$($createResult -replace '^0015:','')"
Write-Host "account name on the login screen: $AccountName"
Write-Host "characters in the list: $(if ($Characters) { $Characters -join ', ' } else { '(none)' })"
Write-Host "reply sequence is $($replySeq.Length) characters"

# Built as a list rather than a backtick-continued call so -NoPatch can leave the three
# patch parameters off entirely. Passing them as empty strings would also work, but an
# empty argument through `powershell -File` is exactly the kind of quoting detail that has
# already cost one launch here, and omitting them cannot go wrong.
$testOneArgs = @(
    '-Reply', 'ping', '-Opcode', '0x0032', '-Body', '00',
    '-PingFirst', '0x0032', '-PingBody', '00', '-QuietBefore', '4',
    '-ReplyTo', '0x0080', '-ReplySeq', $replySeq, '-Answer', $answers,
    '-Keepalive', "$Keepalive", '-Port', "$Port"
)
if ($FastFail) {
    # abort(7), _invoke_watson(5), __report_gsfailure(2), and the generic __fastfail(code)
    # wrapper. Each logs its caller and a stack scan, which is what names the path.
    # 142e9ebd0 is the function that actually failed, found by the first -FastFail run:
    # __report_gsfailure fired 226ms before the exit, called from 142e9fe03, which .pdata
    # puts inside 142e9ebd0..142e9fe0c. It homes four arguments, allocates 0x410, plants the
    # /GS cookie at [RSP+0x400], and then tail-jumps into .themida - so its body is
    # virtualised and only its frame is readable. Something in that body writes past the
    # 0x200-byte local at [RSP+0x200] and into the cookie.
    #
    # Watching its entry logs the arguments on every call, and the watch dereferences rcx
    # and rdx as both bytes and UTF-16, so a format string or a name shows up directly. The
    # question it answers: is this called repeatedly and only fails at ~36.6s - in which
    # case compare the arguments - or called once, on a timer.
    #
    # The three CRT paths stay armed so a different route is not mistaken for this one.
    $ffProbe = 'watch@142e9ebd0:hits=40,142ef3e44:hits=8,142f048cc:hits=8,142f04834:hits=8'
    $testOneArgs += @('-HookLog', 'on', '-Probe', $ffProbe)
    Write-Host ''
    Write-Host 'FastFail: watching 142e9ebd0 - the function whose stack cookie was clobbered -'
    Write-Host 'plus the three CRT fatal paths that can raise int 0x29.'
    Write-Host 'The client will sit behind the "trouble logging in" dialog and die at ~36.7s;'
    Write-Host 'that is expected. Do not click anything. The answer is the WATCH line in'
    Write-Host '  client-patched\maplecw-hook.log'
    Write-Host 'and its called-from, plus any "C++ THROW" lines logged after +25s.'
}
elseif (-not $NoPatch) {
    $testOneArgs += @('-HookLog', 'on', '-Session', $Session, '-Probe', $Probe)
}
else {
    Write-Host ''
    Write-Host 'NoPatch: no dispatcher hook, no int3 watches, no session patch.'
    Write-Host 'The client will show the "trouble logging in" dialog and will not reach'
    Write-Host 'character select - that is expected. The only question this run answers is'
    Write-Host 'whether it still dies at ~36.9 seconds. Do not click anything.'
}
& powershell -ExecutionPolicy Bypass -File $testOne @testOneArgs

Write-Host ''
Write-Host 'On screen:'
Write-Host '  1. is the account name back on the login screen?'
Write-Host '  2. click Login - is there a character called "Maple"?'
Write-Host "  3. Create a character -> spend all 25 points, name it '$NewCharacterName',"
Write-Host '     Check, then OK, then confirm. It should land back on character select'
Write-Host '     with a second character in the list.'
Write-Host ''
Write-Host 'Do not close the client by hand - let it exit on its own. How it dies is the'
Write-Host 'measurement, and a manual close overwrites the answer with our own.'
Write-Host ''
Write-Host 'Then run this script with -Stop. The answers are in'
Write-Host '  client-exit.log                   (how the client died - read this one first)'
Write-Host '  client-patched\maplecw-hook.log   (not hook.log, and not the repo root)'
Write-Host '  - "SESSION called FUN_140c9e230" confirms the create flag was patched on'
Write-Host '  - a WATCH on 141b282d0 means the create handler finally ran'
Write-Host '  and probe.log shows whether 0x00A8 went out.'
