<#
.SYNOPSIS
    Reach character select with a character in the list, and capture what the character
    creation screen sends.

.DESCRIPTION
    Wraps test-one.ps1 with the four-part recipe that gets the client to a usable login
    screen, and answers its 0x0080 with a world entry, the terminator, and a login result
    that carries a real character list.

    The reply bodies are generated by `packet-hex`, never typed. The world-list hex was
    once two characters too long on a command line and the only reason it was caught is
    that a test happened to compare against the builder; this removes the hand-typing
    entirely.

    Two things are being measured, and the second is the point:

      1. Does character select draw the character? That is the first time any of the
         record layout has been on the wire.
      2. What does the creation screen send? The create request is Themida-virtualised
         and cannot be read statically. The OK button sends 0x0081 and the create request
         back to back in one click, so both land in probe.log.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File "C:\MapleCW\tools\test-charselect.ps1"
    powershell -ExecutionPolicy Bypass -File "C:\MapleCW\tools\test-charselect.ps1" -Stop
#>
[CmdletBinding()]
param(
    [switch]$Stop,
    # Names to put in the character list. No names sends an empty list, which is the
    # control: it is what every previous run has effectively been doing.
    [string[]]$Characters = @('Maple'),
    # Shown on the login screen. Server-supplied - the client cannot compute it, so leaving
    # 0x0000 out of the sequence makes the field go blank, which is exactly what happened
    # on the first character-list run.
    [string]$LoginName = 'maplecw',
    [string]$AccountName = 'wisp****@example.com',
    [int]$Port = 8484
)

$ErrorActionPreference = 'Stop'
$here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
$root = Split-Path -Parent $here
$testOne = Join-Path $here 'test-one.ps1'

if ($Stop) {
    & powershell -ExecutionPolicy Bypass -File $testOne -Stop
    exit $LASTEXITCODE
}

function Get-Packet {
    param([string[]]$PacketArgs)
    # packet-hex prints "OPCODE:HEX" on stdout and the byte count on stderr, so only
    # stdout is captured here. A build failure must not be pasted onto the wire as hex.
    Push-Location $root
    try {
        $out = & cargo run --release -q -p net --bin packet-hex -- @PacketArgs
        if ($LASTEXITCODE -ne 0) { throw "packet-hex failed for: $($PacketArgs -join ' ')" }
    }
    finally { Pop-Location }
    $line = ($out | Where-Object { $_ -match '^[0-9a-f]{4}:' } | Select-Object -First 1)
    if (-not $line) { throw "packet-hex printed no packet for: $($PacketArgs -join ' ')" }
    return $line.Trim()
}

$accountInfo = Get-Packet @('account-info', $LoginName, $AccountName)
$worldEntry = Get-Packet @('world-entry', 'Scania')
$worldEnd = Get-Packet @('world-end')
$loginResult = Get-Packet (@('login-result') + $Characters)

# Account first: the name it carries is drawn on the login screen, which the client is
# still showing when this sequence lands.
$replySeq = "$accountInfo,$worldEntry,$worldEnd,$loginResult"
Write-Host "account name on the login screen: $AccountName"
Write-Host "characters in the list: $(if ($Characters) { $Characters -join ', ' } else { '(none)' })"
Write-Host "reply sequence is $($replySeq.Length) characters"

& powershell -ExecutionPolicy Bypass -File $testOne `
    -Reply ping -Opcode 0x0032 -Body 00 `
    -PingFirst 0x0032 -PingBody 00 -QuietBefore 4 -HookLog on `
    -Session mode=2 -Probe watch@141b2a280:rdx=0 `
    -ReplyTo 0x0080 -ReplySeq $replySeq -Port $Port

Write-Host ''
Write-Host 'On screen:'
Write-Host '  1. is the account name back on the login screen?'
Write-Host '  2. click Login - is there a character called "Maple"?'
Write-Host '  3. click "Create a character" - does it go anywhere now?'
Write-Host '  4. if it does: spend all 25 points, type a name, click OK'
Write-Host ''
Write-Host 'Then run this script with -Stop. probe.log is the record of what was sent.'
